# Generated by Django 3.2 on 2021-05-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210507_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default='Uncategorised', null=True, related_name='posts', to='blog.Category'),
        ),
    ]
