# Generated by Django 3.2 on 2021-05-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='featured_image/%Y/%m/%d/', verbose_name='featured image'),
        ),
    ]
