# Generated by Django 3.1 on 2021-07-30 19:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210628_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[700, 500], upload_to='featured_image/%Y/%m/', verbose_name='featured image'),
        ),
    ]
