test_a = {'abate': ['iota'], 'abattoir': ['okatomeno'], 'abbreviation': ['efupipiko'], 'abdomen': ['omumpanya'],
          'lower abdomen': ['oshinena'], 'abduct': ['mbemba'], 'abduction': ['embembopo'], 'ability': ['evulo'],
          'accidentally': ['ohaluka', 'pashaadhilila'], 'accomodation': ['ekalwahala'],
          'accompany': ['enda', 'thindikila'], 'according to': ['pa'], 'according to nature': ['paunshitwe'],
          'accordion': ['enambati'], 'accountability': ['eyalulo', 'uupulwankombo']}

a = {'abate': ['iota'], 'abattoir': ['okatomeno'], 'abbreviation': ['efupipiko'], 'abdomen': ['omumpanya'],
     'lower abdomen': ['oshinena'], 'abduct': ['mbemba'], 'abduction': ['embembopo'], 'ability': ['evulo'],
     'able': ['pondola'], 'nose about': ['petapeta'], 'search about': ['thimbilathimbila'], 'above': ['kombanda'],
     'abscess': ['oshitumbuka'], 'absence': ['uukeepo'], 'absent': ['ke po'], 'absorb': ['nina'], 'abstain': ['idhilika'],
     'abundance': ['eloolo', 'nuwambwa'], 'abundant': ['ha', 'hi'], 'academy': ['oakademi'], 'accelerate': ['ulumika'],
     'accent': ['oaksende'], 'accidentally': ['ohaluka', 'pashaadhilila'], 'accomodation': ['ekalwahala'],
     'accompany': ['enda', 'thindikila'], 'according to': ['pa'], 'according to nature': ['paunshitwe'],
     'accordion': ['enambati'], 'accountability': ['eyalulo', 'uupulwankombo'],
     'accurately': ['lela', 'naanaa'], 'accusation': ['elundilo'], 'accuse': ['lundila'], 'accused': ['omutamanekwa'],
     'accuser': ['omulundili', 'omutamaneki'], 'accustomed': ['igilila'], 'acrophobia': ['uugelele'],
     'actor': ['omunyandi'], 'adansonia digitata': ['omukwa'], 'adapt': ['iyikitha', 'iyigililitha', 'iyeleka'],
     'add': ['hoha', 'gwedha'], 'adding': ['egwedhelo'], 'addition': ['etulokumwe'], 'additional': ['gwedhwa po'],
     'addressee': ['omutuminwa'], 'adenoid': ['omwenge'], 'adhere': ['kakatela'], 'adjective': ['oshityalupe'],
     'adjourn': ['zimbuka'], 'adjournment': ['ezimbuko'], 'adult': ['omukuluntu'], 'adulterer': ['omuhondeli'],
     'adultery': ['oluhondelo'], 'practise adultery': ['hondela'], 'adulteress': ['omuhondeli'], 'adversity': ['omupya'],
     'advertisement': ['etseyitho', 'etseyithilo'], 'advise': ['tsa omayele', 'gandja omayele'], 'advice': ['omayele'],
     'aeroplane': ['odhila', 'ondhila'], 'aesthetic': ['uuwopali'], 'affiliate': ['hemukila', 'mumwe'],
     'affiliation': ['ehemukilomumwe'], 'Afrikaans': ['Oshimbulu'], 'after': ['konima', 'opo ihe', 'opo nduno'],
     'afternoon': ['komatango'], 'again': ['ishewe', 'natango'], 'against': ['pooha'], 'age': ['uukokele'],
     'agenda': ['oagenda', 'elandulathano'], 'agitate': ['tsa omaminimini'], 'agree': ['pitika', 'zimina', 'uvanena', 'uvathana'],
     'agreement': ['euvathano', 'euvaneno'], 'agriculture': ['uunamapya'], 'agricultural': ['kwafaalama'],
     'agronomy': ['uunongononimapya'], 'agronomist': ['omunongononimapya'], 'ahead': ['komeho'],
     'aim': ['odha', 'lalakanena', 'oshilalakanenwa'], 'air': ['ombepo', 'ewangandjo'], 'alarm': ['onkugo'],
     'albino': ['thithi'], 'albizia anihelmintica': ['omupopo'], 'album': ['oalbuma', 'embo lyomathano'],
     'alcohol': ['alkoholi'], 'alcoholic': ['iikolitha', 'onkolwe'], 'algae': ['onguwi'], 'alkali': ['oalikali', 'oshimongwa'],
     'alkaline': ['paalikali', 'pashimongwa'], 'all': ['he'], 'alliance': ['ondjuvanene', 'ehangano'], 'allurement': ['oshinge'],
     'aloe': ['endombo'], 'alone': ['ke', 'mwene'], 'alphabet': ['aambeendee'],
     'alphabetically': ['paambeendee', 'pahaanibeendee'], 'also': ['wo', 'ootu'],
     'alternative': ['epingeno'], 'although': ['nando', 'nonando'], 'aluminium': ['oaluminiuma'], 'always': ['aluhe'],
     'amateur boxer': ['omumbokisilinyanyu'], 'amazing': ['kuinithi'], 'ambassador': ['omukalelipo'], 'ambush': ['elangelo'],
     'ammonia': ['amoniaka'], 'ammonium sulphate': ['amoniumsulfate'], 'ammunition': ['oshuumbithi', 'oshiyumbithi'],
     'amnesty': ['esohenda lyoonkwatwa'], 'among': ['mokati'], 'amongst': ['mokati'], 'amount': ['omwaalu', 'omiyalu'],
     'amulet': ['oshigegeti'], 'analyse': ['vongokonona'], 'analysis': ['evongokonono'], 'anatomy': ['oanatomi'],
     'anatree': ['omuyele'], 'ancestor': ['epipi', 'omukulugonale', 'omukwampungu'], 'ancestral spirits': ['aathithi'],
     'anchor': ['hangela', 'ohangela'], 'ancient': ['uukulupe womutoko'], 'and': ['e', 'na'],
     'angel': ['omuyengeli'], 'angle': ['okolonela', 'ekuvu', 'onkuvu'], 'wild': ['oshiyamakuti'], 'ankle': ['onyugu'],
     'annex': ['tenda ko'], 'annexation': ['etendoko'], 'announce': ['imeleta', 'ilombola', 'tseitha'],
     'annoy': ['hinda', 'yemateka'], 'annual function': ['okatuthihulitho'], 'anoint': ['gwayeka'],
     'another': ['kwawo', 'lwe'], 'answer': ['yamukula', 'eyamukulo'], 'ant': ['ondhindhi', 'eteta'],
     'ant-bear': ['eyamayama'], 'ant-eater': ['ongaka'], 'ant-hill': ['oshaanda', 'oshiyanda'], 'anthrax': ['ombulwa'],
     'antibiotic': ['oshidhipagimbuto', 'omuti'], 'anticipate': ['tegamena'], 'anticipation': ['etegameno'],
     'anus': ['onufu'], 'anxiety': ['omahwilili', 'uuhwenge'], 'anxiously': ['nyulukuta'], 'anvil': ['oshikalo'],
     'any': ['kehe'], 'anyone': ['kehe ngoka'], 'anything': ['kehe shimwe'], 'anyway': ['ando'], 'aorta': ['aorta'],
     'ape': ['ondjima'], 'apoplexy': ['ombanda', 'esilombanda'], 'apparatus': ['oaparate', 'oshilongitho'],
     'apparition': ['oshihehelela', 'oshikwafa'], 'appeal': ['tsikilitha ompangu', 'etsikilompangu', 'indila', 'eindilo'],
     'appear': ['holoka', 'mbanduka', 'uluka'], 'appearance': ['ondjelo', 'eholoko', 'ombelo'], 'appendicitis': ['okiimili'],
     'appendix': ['okiimili', 'oshigwedhelwako'], 'appetite': ['omwamwa'], 'applaud': ['hakela', 'pandula'],
     'applause': ['ehakelo', 'ekugililo'], 'apple': ['oshiapula', 'oshiyapula'], 'application': ['eindilo'],
     'apply': ['longitha', 'ninga eindilo'], 'appoint': ['lenga', 'ulika'], 'appointment': ['oshilage', 'euliko'],
     'approach': ['hedha', 'engena', 'omukalo'], 'approximately': ['konyala', 'lunga'], 'April': ['Apilili'],
     'apron': ['oshitetahema'], 'aquarium': ['oakwariuma'], 'Arab': ['Omwaarabia', 'Aayarabia'], 'arbitrate': ['potokonona'],
     'arbitrator': ['omupongololi', 'omupotokononi'], 'architect': ['omuthanekingulu', 'omusindingulu', 'omusindigumbo'],
     'argue': ['tamanana'], 'argument': ['oontamanana'], 'arm': ['okwaako', 'okwooko', 'okooko'], 'armpit': ['onkwapa'],
     'armament': ['ehomato'], 'armed': ['homata'], 'around': ['omudhingoloko'], 'arrange': ['pongolola', 'longekidha'],
     'arrangement': ['elongekidho', 'eilongekidho'], 'arrest': ['kwata', 'tula miipandeko', 'manga po'],
     'arrive': ['thika'], 'arrival': ['eyo', 'ethiko'], 'arrogance': ['elundu'], 'arrow': ['oshikuti', 'omuvi'],
     'artery': ['onkandjambinzi'], 'article': ['oshinima', 'okatendo'], 'artisan': ['engomba'], 'artist': ['omunongo', 'onkulungu'],
     'art': ['uunkulungu', 'uunongo', 'uungongi'], 'as far as': ['sigo'], 'as soon as': ['hela tuu'],
     'asbestos': ['oasbesa'], 'Asia': ['Asia'], 'Asian': ['Omwaasia', 'Aayasia'], 'ash': ['omutoko'], 'aside': ['kombinga'],
     'assegai': ['egonga'], 'assembly': ['omutumba'], 'assignment': ['oshitopolwa shiilonga', 'oshitopolwailonga'],
     'assist': ['kwatha', 'ambidhidha'], 'assistant': ['omuyakuli', 'omupeha'], 'assistance': ['ekwatho', 'eambidhidho'],
     'association': ['ehangano'], 'asthma': ['oasma'], 'astonishment': ['onkumwe'], 'astonish': ['kumitha'],
     'astounding': ['kumithi'], 'at': ['p-', 'k-'], 'atom': ['oatoma'], 'atomic': ['paatoma'], 'Atlantic': ['Atlantika'],
     'atlas': ['oatilasa', 'oatlasa'], 'atmosphere': ['ombepo ', 'ongandjombepo', 'ewangando'], 'attach': ['kopeka'],
     'attack': ['umpila', 'ponokela', 'homona', 'tondokela'], 'attacker': ['omuhomoni', 'omumatukili', 'omutondokeli', 'omuponokeli'],
     'attempt': ['kambadhala', 'ekambadhalo', 'onkambadhala'], 'attend': ['sikola', 'ndhindhilika', 'hita'],
     'attention': ['eimweneneno', 'ndhindhilika'], 'attentiveness': ['oonkoto'], 'attitude': ['omikalo', 'oohedhi'],
     'attract': ['fuula', 'fuuka'], 'attraction': ['ohokwe'], 'attractive': ['hokitha'], 'auction': ['fanditha', 'ofanditha', 'elanditho'],
     'auctioneer': ['omulandithi'], 'August': ['Auguste'], 'aunt': ['kuku', 'yinagona'], 'my aunt': ['memegona'],
     'Australia': ['Australia'], 'Australian': ['Omwaaustralia', 'Aayaustralia'], 'Austria': ['Austria'],
     'Austrian': ['Omwaaustria', 'Aayaustria'], 'authority': ['oompango', 'oonkondo'], 'autumn': ['oshikufuthinge'],
     'available': ['shili po'], 'avert': ['ingila', 'yanda'], 'avocado': ['oshiavokado'], 'avoid': ['iyageka', 'yanda', 'keelela'],
     'awake': ['penduka', 'papudhuka'], 'awakening': ['ependuko'], 'aware': ['shi', 'nongela'], 'awareness': ['enongelo'],
     'away': ['yi', 'ya'], 'awl': ['oniho'], 'axe': ['ekuya'], 'axle': ['oakiseli', 'oakisa'], 'axis': ['oakiseli']}

b = {'baboon': ['ondjima', 'lunkima'], 'baby': ['okahanona', 'omuholike'], 'back': ['omugongo', 'ombunda'],
     'backbone': ['omugongo', 'esipa lyombunda'], 'backbite': ['hokola'], 'backbiter': ['omuhokoli'],
     'background': ['osindo'], 'backside': ['etako', 'konima'], 'bacteria': ['ombakiteli'], 'bad': ['ha'],
     'badge': ['oshihako', 'ombandi'], 'badly': ['nayi'], 'badness': ['uuwinayi'], 'bag': ['oshako', 'ondjato'],
     'bail': ['eimbeelomo', 'omboloha'], 'bake': ['mbaka', 'yotha'], 'bakery': ['ombeka'], 'baking-powder': ['efulika'],
     'balance': ['ontengelelo', 'oshihupe'], 'bald': ['ongwala'], 'bale': ['oshihampi'], 'ball': ['etanga'],
     'balloon': ['embalona'], 'weather': ['onkalo yombembo'], 'ballot': ['ombapila yehogololo'], 'ban': ['konda'],
     'banana': ['embanana', 'omumbanana'], 'bandolier': ['ekwamo'], 'bang': ['ngwanda'], 'bangle': ['okagondo'],
     'bank': ['pungula', 'ombaanga'], 'bankrupt': ['mbangolota'], 'bankruptcy': ['embangoloto'],
     'baobab': ['omukwa'], 'baptise': ['shasha'], 'baptiser': ['omushashi'], 'bar': ['ombaa', 'enwino'],
     'barbed hook': ['ongona'], 'barber': ['omukululi'], 'barbershop': ['okakululilo'], 'barefoot': ['ohuuna'],
     'bark': ['eyula', 'gwedha'], 'barrel': ['oluungu'], 'barter': ['pingakanitha'], 'basic': ['ekota'],
     'basin': ['oshiyaha', 'okatemba'], 'basis': ['oshimbu'], 'basket': ['ontungwa'], 'grain basket': ['eshisha', 'oshigadhi'],
     'bass': ['omugono', 'ombaatha'], 'bat': ['elimalima'], 'bathroom': ['okaiyogelo'], 'battery': ['emanya', 'opatrii'],
     'battle': ['olugodhi'], 'beach': ['omunkulofuta'], 'beak': ['omulungu', 'epakululu'], 'beam': ['omutenge', 'oonte'],
     'bean': ['ekunde'], 'bean sauce': ['oshigali'], 'bear': ['vala', 'humbata', 'ima', 'emwanka'], 'beard': ['oombenzi)'],
     'bearer': ['omuhumbati'], 'beast': ['ongombe'], 'beat': ['thekula', 'thepagula', 'dhenga'], 'beautiful': ['opala', 'wanawa'],
     'beautify': ['opaleka'], 'beauty': ['uuwopali', 'uuyogoki', 'uuwanawa'], 'because': ['oshoka', 'shaashi', 'molwashoka'],
     'beckon': ['lapa'], 'bed': ['ontala', 'ombete'], 'bedding': ['iinguma'], 'bee': ['onyushi'], 'beer': ['ombiila', 'omalovu'],
     'beestings': ['epuya'], 'beeswax': ['ezi'], 'beetle': ['ondjimbi', 'okambaambala'], 'beetroot': ['eroibiyeta'],
     'before': ['manga', 'komeho'], 'beg': ['hehela', 'indila', 'galikana'], 'begging': ['egalikano', 'eindilo', 'ehehelo'],
     'behave': ['ihumbata'], 'behaviour': ['eihumbato', 'omaihumbato', 'omikalo'], 'begin': ['tameka'], 'beginner': ['omutameki'],
     'beginning': ['etameko'], 'belief': ['eitaalo'], 'believe': ['itaala'], 'believer': ['omwiitaali'], 'belong': ['gama'],
     'below': ['pevi'], 'bell': ['ongendjo'], 'bellow': ['ula'], 'belly': ['epunda'], 'beloved': ['omuholike'],
     'belt': ['omuya', 'epaya'], 'bench': ['oshipundi'], 'bend': ['petama', 'gonya'], 'bent': ['egoli'], 'berry': ['okayimati'],
     'besides': ['kakele'], 'bestman': ['oshinkumbi'], 'betray': ['gwaaleka', 'kengelela', 'nwa po'], 'betrayer': ['omugwaaleki'],
     'better': ['hwepo'], 'beware': ['angla', 'kotoka'], 'bewitch': ['tikila', 'loga'], 'beyond': ['pombanda'],
     'Bible': ['Ombiibeli'], 'bicycle': ['okathanguthangu', 'okambasikela'], 'big': ['-nene'], 'bigamy': ['ombanda'],
     'bill': ['oongunga', 'iifuta'], 'billion': ['obiliyona'], 'billow': ['tuwalala'], 'biltong': ['oludhingu'],
     'bird': ['okadhila', 'ondhila'], 'bioscope': ['okino'], 'birth': ['vala', 'pulumutha'], 'birthday': ['esiku lyevalo'],
     'bisect': ['tateka'], 'bishop': ['omumbisofi'], 'bit': ['sha', 'okanima'], 'bite': ['lumata'], 'bitter': ['lula'],
     'bitterness': ['uululu'], 'black': ['luudhe'], 'blackboard': ['oshipelende'], 'blacken': ['luudhika', 'nyateka'],
     'blackmail': ['thina'], 'Blacks': ['Aaluudhe'], 'blacksmith': ['omuhambudhi', 'omuhambuli'], 'blade': ['efo lyomwele'],
     'bladder': ['okampunda komasita'], 'blanket': ['ekumbatha'], 'blast': ['topa'], 'blaze': ['omulilo'], 'bleat': ['lila'],
     'bleed': ['hiha'], 'bless': ['yambeka'], 'blesser': ['omuyambeki'], 'blessing': ['ehaleloyambeko', 'eyambeko'],
     'blind': ['toga', 'tsika', 'omuposi'], 'blindness': ['uuposi'], 'blister': ['epuya', 'oompekehe'], 'block': ['keelela'],
     'blood': ['ombinzi'], 'blossom': ['onsheno', 'sheneka'], 'blouse': ['ohema yoshikiintu'], 'blow': ['pepa', 'fudhila', 'fugula', 'pemba'],
     'blowlamp': ['olamba yokufikilitha'], 'blue': ['mbulau'], 'blunt': ['simpa'], 'board': ['menekela', 'embolota'],
     'boast': ['inoma'], 'boat': ['ombautu'], 'body': ['olutu'], 'boil': ['fuluka', 'ethina'], 'bomb': ['mboma', 'omboma'],
     'bombardment': ['embomo'], 'bomber': ['omumboni'], 'bone': ['esipa'], 'bonus': ['ombonasa'], 'book': ['embo', 'oshifo', 'okambo'],
     'boomslang': ['iifoyamusati'], 'boot': ['ombuta', 'ombutsa', 'thanga'], 'booth': ['okangulu'], 'border': ['ongamba'],
     'borehole': ['omboola'], 'borrow': ['hehela'], 'botany': ['obotani', 'ontseyoimeno'], 'bottle': ['ekende'],
     'bottletop': ['oshisiikilitho', 'okasiikilitho'], 'bottom': ['oshitako', 'kohi'], 'boulder': ['ethindimanya'],
     'boundary': ['ontaululi'], 'bow': ['uutati', 'uuta wanangongo'], 'bowtie': ['okakunde'], 'box': ['oshiketha', 'okapakete', 'oongonyo'],
     'boxer': ['omudhengingonyo'], 'boy': ['okamati', 'omumati'], 'boyhood': ['uumati'], 'brain': ['uuluyi'],
     'brake': ['ombiliki', 'mbilika'], 'bran': ['uuhutu'], 'branch': ['oshitayi'], 'brandy': ['ombike', 'ombelendi'],
     'brave': ['pendapala'], 'bravery': ['onyati', 'uufule'], 'bray': ['koma'], 'bread': ['omboloto', 'oshikwiila'],
     'breadth': ['omutamo'], 'break': ['pambula', 'tatula', 'teya', 'tokola', 'topola', 'kumuna', 'ngumuna', 'okafudho'],
     'breast': ['ondete', 'egundji'], 'breath': ['omufudho'], 'breathe': ['fudha'], 'breed': ['kola', 'muna'],
     'brew': ['hanga', 'dhunga'], 'brewery': ['ombuulaye'], 'bribe': ['ombumbo'], 'brick': ['ondhopi'], 'bride': ['omufuko'],
     'bridegroom': ['omufuko', 'ombushiki'], 'bridesmaid': ['oshinkumbi'], 'bridge': ['ontopa', 'kwatakanitha'], 'bridle': ['oshitomo'],
     'briefcase': ['ompunda', 'okataasi'], 'bright': ['yelele', 'adhima'], 'gnu': ['ompugulu'], 'bring': ['eta'],
     'broadcast': ['tuma mombepo'], 'brochure': ['obroshure'], 'broom': ['oluhwati', 'oshikombe'],
     'brother': ['omumwayina', 'omumwayinamati', 'mbuluta'], 'brown': ['ndjimbi', 'mbambi'], 'bubble': ['ombwimbwi', 'gwagwata'],
     'bubonic plague': ['uuvu wombuku'], 'bucket': ['eyemele', 'etenga'], 'buckle': ['ompate'], 'bud': ['shena', 'osheno'],
     'budget': ['etengenekothaneko'], 'buffalo': ['onyati'], 'build': ['tunga'], 'builder': ['omutungi'],
     'building': ['etungo', 'ongulu', 'egumbo'], 'bulb': ['ombimbo', 'etindi', 'okambiyena', 'okalamba'], 'edible': ['ongehu', 'oshikuliwa'],
     'bulge': ['umbuka'], 'bull': ['ontsenzi'], 'bulletin': ['ombuletine'], 'bump': ['nguma', 'puma'], 'bunch': ['ehila'],
     'bundle': ['oshihampi', 'oshipandi', 'okapandi', 'okahampi'], 'burn': ['fika', 'lunguna', 'pya'],
     'burn-marks': ['oondjota'], 'burrow': ['omvugo'], 'bursary': ['iimaliwa yokwiilongitha'], 'burst': ['topa', 'tenda'],
     'bury': ['fumbika', 'fumvika'], 'bus': ['ekambamba', 'ombesa'], 'bush': ['oshiheke', 'oshihwa'], 'Bushman': ['Omukwankala'],
     'business': ['uunangeshefa', 'ongeshefa'], 'businessman': ['omunangeshefa'], 'busy': ['sikuuka', 'ipyakidhila'], 'but': ['ihe', 'ndele'],
     'butcher': ['omutseli'], 'butchery': ['oshilahite'], 'butter': ['omagadhi', 'ombuta'], 'butterfly': ['embiimbili', 'okambiimbili'],
     'buttock': ['etako'], 'button': ['ombandi', 'pata'], 'buy': ['landa'], 'buyer': ['omulandi'], 'by': ['ku'],
     'bypass ': ['kunkula', 'kunduluka', 'dhingoloka']}

c = {'cabinet': ['oskopa', 'osikopa', 'okabinete'], 'cackle': ['kokola', 'tetena'], 'cake': ['oshikuki'],
     'calabash': ['ombago', 'oshikola', 'ompamba'], 'calculate': ['yalula'], 'calculation': ['eyalulo'], 'calender': ['okalindela'],
     'calf': ['ontana', 'okatana'], 'call': ['ithana', 'igidha'], 'calm': ['ngungila', 'mweneka'], 'camel': ['ongamelo'],
     'camel-thorn': ['omuthiya'], 'camera': ['efano  lyokuthaneka'], 'camp': ['yunga', 'ontanda', 'okamba'],
     'can': ['wapa', 'vula'], 'Canada': ['Kanada'], 'Canadian': ['Omukanada'], 'canal': ['omukanka'], 'Canary': ['namukuku'],
     'cancel': ['kansela'], 'cancellation': ['ekanselo'], 'cancer': ['okanker', 'ondhiya'], 'cannot': ['itashi vulika'],
     'cannikin': ['okakana'], 'cannon': ['ekanona'], 'cap': ['okagala'], 'capital': ['iimaliwa'], 'capitalism': ['uukapitali'],
     'capitalist': ['omukapitali'], 'capriciousness': ['omanganga', 'omanyami'], 'captain': ['kapitiya'],
     'captivity': ['uupika', 'uukwatwa', 'uupongekwa'], 'capture': ['kwata'], 'captured': ['sha kwatwa'], 'car': ['oshihauto'],
     'carbon dioxide': ['onkwakala'], 'card': ['okakalata'], 'cardboard': ['oshipakete'], 'care': ['hunga', 'sa oshimpwiyu'],
     'careful': ['oshimpwiyu'], 'carefully': ['nekotoko', 'noshimpwiyu'], 'caring': ['esiloshimpwiyu'],
     'carpenter': ['omuhongi gwiipilangi', 'kapindela'], 'carpet': ['ombanza'], 'carrier': ['omuhumbati'], 'carrot': ['okanakamundesha'],
     'carry': ['humbata', 'leka', 'tumba', 'kwiinina'], 'carry out': ['gwanitha'], 'carrying': ['ehumbato'], 'carrying skin': ['ondhikwa'],
     'cart': ['tuta'], 'caruncle': ['okakunde'], 'carve out': ['nega'], 'carving': ['etakelo'], 'case': ['oshiketha', 'iikoya', 'ompangu'], 
     'cash': ['okeshe', 'oshimaliwa shopeke'], 'caster-oil': ['okastololi'], 'caster-oil plant': ['olumono'],
     'castle': ['epopilongulu'], 'cat': ['kalenga', 'okambishi', 'ngato'], 'catapult': ['okatayingil'], 'catastrophies': ['iihnna'],
     'catch': ['kwata', 'fegula', 'akula', 'luga', 'shongola', 'yula'], 'catcher': ['omukwati'], 'catching': ['ekwato'],
     'catholic': ['okatolika'], 'cattle': ['oongombe'], 'cauliflower': ['ombogangala'], 'cause': ['ningitha'], 'cave in': ['kumuka', 'ngumuka'],
     'cavity': ['ekololo'], 'ceiling': ['ontala'], 'cement': ['osamende'], 'cemetery': ['eendo'], 'census': ['eyalulo lyaantu'],
     'cent': ['osenda'], 'centipede': ['embalangandja'], 'central': ['pokati', 'shopokati'], 'central committee': ['ongundumutinia'],
     'centre': ['pokati'], 'century': ['oomvula omayovi'], 'certain': ['ontumba'],
     'chaff': ['omanyami', 'olungu', 'etutu'], 'chain': ['elyenge'], 'chair': ['oshipundi'], 'chairperson': ['omunashipundi'],
     'chalk': ['ompya'], 'chameleon': ['ethimbithimbi'], 'champion': ['enyakwa'], 'chance': ['ompito', 'olweedhe'],
     'chandelier': ['oshihukikwanyeka'], 'change': ['lundulula', 'shitula'], 'change': ['elunduluko', 'elundululo'],
     'change money': ['shendja iimaliwa'], 'changeable': ['mpinyuka'], 'chapter': ['ontopolwa'], 'character': ['uukwatya'],
     'charcoal': ['ekala'], 'charge': ['nukila', 'umpila', 'ponokela', 'eumpilo', 'enukilo', 'eponoko', 'elopoto', 'etamaneko'],
     'charge': ['lopota', 'tamaneka'], 'charm': ['oshigegeti', 'omuheka'], 'chart': ['okaalita'], 'chase': ['ganda', 'tidha'],
     'chasm': ['ekulukila'], 'chat': ['popyapopya'], 'chatter': ['tyaatyaa', 'popyagula'], 'cheap': ['ombiliha'],
     'cheaper': ['ombiliha unene', 'pambiliha'], 'cheat': ['kotokela'], 'check': ['tala', 'hadha'], 'cheek': ['ompanda', 'olupanda'],
     'cheekiness': ['olundu', 'oshityani', 'omanganga'], 'cheese': ['ehini'], 'cheetah': ['etotono'], 'cheque': ['otyeke'],
     'chest': ['ontulo'], 'chew': ['taasina', 'inyangusha'], 'chewing': ['emukutulo'], 'chick': ['okayuhwena'], 'chickenpox': ['epulu'],
     'chief': ['omukwaniilwa', 'eleng'], 'chiefly': ['unene'], 'child': ['omunona'], 'childhood': ['uunona'], 'children': ['aangela', 'uunona'],
     'chili': ['ondungu'], 'chimney': ['oluungu'], 'China': ['Kina'], 'Chinese': ['Omukiina'], 'chip': ['popoka', 'oshikangwa'],
     'chips': ['ekoko'], 'chirp': ['sheketa'], 'chisel': ['omaisela'], 'chlorinated lime': ['okaalaka kokololo'], 'chlorine': ['ochiorine'],
     'choice': ['ehogololo'], 'cholera': ['kolera', 'cholera'], 'choose': ['hogolola'], 'chop': ['komangela', 'panda'], 'chord': ['elimba'],
     'chosen': ['sha hogololwa'], 'Christian': ['omukriste'], 'Christianity': ['uukriste'], 'Christmas': ['Okrismesa'], 'chunk': ['endangalati'],
     'church': ['ongeleka'], 'churn': ['hika'], 'cicada': ['enyenye'], 'cigarette': ['okasekeleta'], 'cigarette-end': ['okaictela'],
     'cilia': ['olumbatu'], 'cinema': ['okino'], 'circle': ['ongonga'], 'circumcise': ['kenka'], 'citizen': ['omukalimo'],
     'citrus': ['iisitulusa'], 'city': ['oshiando'], 'civil': ['kwashigwana'], 'civilian': ['omukwashigwana'],
     'civilisation': ['eputuko', 'uukwashigwana'], 'claim': ['pula'], 'clap': ['hakela'], 'clapping': ['ehakelomake'], 'clarity': ['uuyelele'],
     'class': ['ongundu'], 'clay': ['eloya ', 'oshiyuma', 'oshuma'], 'clean': ['yogoka', 'yela', 'opaleka', 'komba'], 'clear': ['yelele'],
     'clearing': ['ehenene'], 'cleave': ['toogonya'], 'cleft': ['ekolombongo'], 'clerk': ['okierka', 'omunambelewa'],
     'cliff': ['oshimpoko', 'etayimanya'], 'climate': ['okliima'], 'climb': ['londa', 'heluka', 'londoloka'], 'cling': ['thapila', 'kakatela'],
     'clinic': ['oklinika', 'okapangelogona'], 'clipper': ['omukululi'], 'clod': ['ekuma'], 'close': ['edhila', 'thateka'],
     'closed': ['she edhilwa'], 'cloth': ['elapi'], 'clothe': ['zala'], 'clothes': ['oonguwo', 'oonguyo'], 'clothes-basket': ['eshungu'],
     'clothing': ['oshizalomwa'], 'cloud': ['oshikogo'], 'cloudy': ['kogopala'], 'cloudiness': ['ekogopalo'], 'clout': ['enkawa', 'olupi'],
     'club': ['onkunya'], 'coagulate': ['hekela'], 'coal': ['ekala'], 'coast': ['omunkulo'], 'coat': ['elwakarn', 'ondjatha'],
     'coax': ['sisidha'], 'cobra': ['efu'], 'cock': ['ekondombolo'], 'cockiness': ['oshityani'], 'cockroach': ['epenzu', 'cpcnzi'],
     'cockscomb': ['enyaga'], 'cocky': ['lunduka', 'dhuma'], 'code': ['okoode'], 'coffee': ['okoothiwa'], 'coin': ['engwanda'],
     'coins': ['iimaliwa iikukutu'], 'cold': ['talala', 'ekunku'], 'colic': ['oshitheta'], 'collapse': ['ongotela', 'sa ombanda'],
     'collapsed': ['a sa ombanda'], 'collect': ['gongela', 'ndjagaya', 'tyaya'], 'collection': ['ongalo', 'egongelo'], 'college': ['okolidji'],
     'colon': ['enyo'], 'colony': ['okoloni'], 'colour': ['mbapeka', 'olwaala', 'ombapa'], 'coloured': ['omunalwaala', 'ombastela'],
     'column': ['ombongola', 'omukweyo'], 'comb': ['kamula', 'oshikamule', 'ompendu'], 'combination': ['ehanganitho'],
     'combine': ['hanganitha'], 'come': ['ya'], 'comedy': ['oshinyandwanyanyu'], 'comfort': ['hekeleka', 'ehekeleko'],
     'coming': ['eye'], 'command': ['lombwela', 'elombwelo'], 'commander': ['omukomandi'], 'commentator': ['omufatululi'],
     'comments': ['nega'], 'commerce': ['iipindi'], 'commercial': ['paipindi'], 'commissioner': ['komufala'], 'committee': ['okomitiye'],
     'commodities': ['iipindi', 'iilandithomwa'], 'common': ['tsa kumwe'], 'communal land': ['evi lyomuhanga'],
     'communion': ['oshililo', 'uulalelo uuyapuki'], 'communism': ['uukomonisi'], 'communist': ['omukomonisi'],
     'community hall': ['oshinyanga shaayehe'], 'community school': ['osikola yoshigwana'], 'companion': ['omuthindikili'],
     'company': ['ehangano'], 'compare': ['yelekanitha'], 'compared': ['sha yelekanithwa'], 'compete': ['thigathana'],
     'competition': ['ethigathano'], 'complain': ['yemata'], 'complaint': ['eyemato', 'enyenyeto'], 'complete': ['tsakanitha', 'mana', 'udhitha'],
     'completed': ['sha tsakana', 'sha pwa', 'shu udhithwa'], 'completely': ['thiluthilu'], 'compose': ['tota'], 'comprehension': ['etanutho'],
     'comprehension test': ['etanuthokonakono'], 'compulsory': ['tashi dhengele'], 'computer': ['okompiuta'],
     'conceahneflt': ['uuholeki', 'eholeko', 'uuholekedhi'], 'concentrate': ['itula mo', 'dhiladhila muule'], 'concentration': ['eitulomo'],
     'concept': ['oshidhumo'], 'conception': ['etanutho', 'euvoko'], 'concern': ['shi na sha'], 'concerning': ['molwa', 'kombinga'],
     'concertina': ['ongongi'], 'consciousness': ['eipangelo'], 'concrete': ['okaungulita'], 'condition': ['onkalo'], 'condone': ['dhimina'],
     'conference': ['oshigongi'], 'confess': ['hempulula'], 'confession': ['ehempululo', 'ezinuno'], 'conflict': ['eipumomumwe'],
     'confusion': ['evundakano'], 'Congo': ['Kongo'], 'Congolese': ['Omukongo'], 'congratulation': ['ehalelolago'], 'congress': ['oshiithanene'],
     'connected': ['sha kwatakanithwa'], 'connection': ['ekwatathano'], 'conquer': ['sinda'], 'conqueror': ['omusindani', 'omuwini'],
     'conscience': ['eiyuvo'], 'consent': ['epitikilo', 'ezimino'], 'conservation': ['egameno'], 'consideration': ['omaengweno'],
     'consists': ['sha thikama'], 'consolation': ['ehekeleko'], 'constipation': ['ombato'], 'constitution': ['ekotampango'],
     'construction': ['etungo'], 'consume': ['thekeka'], 'consumer': ['omulandi', 'omulongithi'],
     'contagious disease': ['olukongo', 'omukithi gwomukwawu'], 'contagiousness': ['omukwawu', 'olutapo'], 'container': ['oshikwatelwa'],
     'contain': ['shi na'], 'contamination': ['enyateko'], 'contempt': ['ondhino'], 'continent': ['okontinente'], 'continue': ['tsikila'],
     'continues': ['tashi tsikile'], 'contraception': ['oshingambeki sholuvalo'], 'contract': ['okondalaka', 'euvathano'],
     'contraction': ['eihuto'], 'contractor': ['omutungingulu'], 'contradiction': ['oombata'], 'control': ['konakona', 'kondolola'],
     'controlled': ['sha konakonwa', 'sha kondololwa'], 'conversation': ['onkundathana'], 'conversion': ['eitedhululo'], 'convert': ['itedhulula'],
     'convey': ['thikitha'], 'convulsion': ['thanganya'], 'cook': ['teleka', 'omuteleki'], 'cooked': ['pya'],
     'cooking oil': ['omagadhi gokulya'], 'cool down': ['talala', 'pola'], 'co-operation': ['elongelokumwe'], 'copper': ['ongopolo'],
     'copper anklet': ['ongondo'], 'copse': ['omuhenye'], 'copy': ['sindila', 'okopi'], 'cord': ['okaankoga'],
     'cork': ['oshisiikilitho'], 'corn': ['oshilyawala', 'omushokolo', 'iilyaalyaka','ompwe', 'oshilya'], 'corn': ['ontindo'],
     'corner': ['ompoko', 'onkotso'], 'corporation': ['ehangano'], 'corpse': ['omudhimba'], 'correct': ['pukulula', 'opaleka'],
     'corridor': ['uupandaanda'], 'corrugated iron sheet': ['oshipeleki'], 'cost': ['ondando'], 'cotton': ['oshilugu', 'ondhilewu'],
     'couch grass': ['ongwena'], 'cough': ['kolola', 'omukolo'], 'coughing': ['ekololo'], 'counting': ['eyalulo'],
     'country': ['oshilongo'], 'couple': ['haka', 'aaihokanathani'], 'courage': ['omukumo'], 'course': ['okersesa'],
     'court': ['ohofa', 'ompangu'], 'cousin': ['gwaantsezi', 'omumwaho'], 'cover': ['siikila', 'epeko'], 
     'covering': ['esiikilo'], 'covey': ['enduwa'], 'cow': ['onzinzi'], 'coward': ['omumbanda', 'omukatalume', 'ewaya'],
     'cowardice': ['uukatalume', 'uuwaya'], 'cowardly': ['gwegwembela', 'gwaala', 'lunduka'], 'crack': ['tenda', 'tyalakata', 'ehindja'],
     'cracked': ['tanduka'], 'craftsman': ['engomba'], 'cram in': ['hwela'], 'cramp': ['eyathipa'], 'crane': ['olema'],
     'crashing': ['omupaulilo'], 'crawl': ['pwedha', 'kookolola'], 'crazy': ['pwidhi'], 'creak': ['kolokota'], 'cream': ['olukawe'],
     'crease': ['gonyatala', 'egonyoto'], 'create': ['shita'], 'creation': ['eshito'], 'Creator': ['Omushiti'], 'creep': ['kookaya', 'hita'],
     'crèche': ['oshikunino', 'oshitsambe', 'uulelelo'], 'credit': ['okrediti'], 'cretin': ['eungu'],
     'crew': ['oonakulongamo'], 'cricket': ['okathangamatondo', 'okashenye', 'elindi', 'elindilindi'], 'criminal': ['omuyonaguli'],
     'cripple': ['oshilema'], 'crisis': ['oshikele'], 'criticised': ['sha tamanekwa'], 'criticism': ['etamaneko'], 'croak': ['zima'],
     'crockery': ['okatashe', 'oshitatuki', 'iikwakutatuka'], 'crocodile': ['ongandu'], 'Crombec': ['ndulumakunde'], 
     'crook': ['ontseyele', 'ompote', 'omufuthi', 'otyaka'], 'crooked': ['penga'], 'crookedness': ['iitsatsa'], 'crop': ['eteyo'],
     'cross': ['tokola', 'taaguluka', 'shigakana', 'geela', 'yala'], 'crossbar': ['ontanu', 'ohonga', 'olukambo'], 
     'crossed': ['sha shigakana', 'sha taskana', 'sha shindjakana'], 'crow': ['iga', 'ekola', 'edhilakola'],
     'crowd': ['ngundumana'], 'crown': ['oshishani'], 'crucifixion': ['eyalelo'], 'cruel': ['kolokoshi'], 'cruelty': ['uukolokoshi'],
     'crumb': ['ondjagumuke'], 'crush': ['nyanyula', 'thenga', 'takula'], 'crusher': ['oshikokota'], 'crust': ['ekoko'], 'cry': ['lila'],
     'crystal': ['ewe'], 'Cuba': ['Kuba'], 'Cuban': ['Omukuba'], 'cucumber': ['okatanga'], 'cultivate': ['gondjoka'],
     'cultural': ['paikwashigwana'], 'culture': ['iikwashigwana'], 'cumulonimbus': ['ngungumikogo', 'iityalakatakogo'], 'cumulus': ['iikumulusa'],
     'cunning': ['ondondolo'], 'cup': ['okakopi'], 'cupboard': ['osikopa'], 'curd': ['omaoteka', 'omooteka', 'omoosi', 'oshooteka'],
     'cure': ['aludha', 'panga'], 'curiosity': ['uutaledhi', 'uutalambambi'], 'curl': ['ondhinga'], 'currency': ['iimaliwa'],
     'current': ['pethimbo mpoka'], 'curse': ['thinga', 'ethingo'], 'curtains': ['omalapi gopomakende'],
     'cushion': ['oshigwilo', 'oshikuusinga'], 'customer': ['okastoma'], 'cut': ['konda', 'kulula', 'teta', 'keka', 'tenga', 'lenga', 'henda'],
     'cutting': ['eteto'], 'cutworm': ['enkandyangali'], 'Cyprus': ['Ciprus'], 'Cyprian': ['Omuciprusa'], 'Czechoslovakia': ['Czechoslovakia']}

d = {'dabchick': ['neyumbo', 'ondjumbu', 'neumbu', 'okaneumbu'], 'dagga': ['epangwe'], 'dagger': ['omwele'], 'daily': ['esiku kehe'],
     'dam': ['ondama'], 'damage': ['yonagula'], 'damn': ['thinga'], 'damp': ['omuku'], 'dance': ['nyanda', 'tanta', 'tutula', 'dhana'],
     'dancer': ['omudhani'], 'danger': ['oshiponga'], 'dangerous': ['shi na oshiponga'], 'dark': ['luudha', 'wiwila'], 'darkness': ['omulema'],
     'darn': ['lapa'], 'dash': ['nipuka', 'oshidhiladhilitho'], 'date': ['enyolwasiku', 'omuye'], 
     'daughter': ['omukadhona', 'omwanakadhona'], 'dawn': ['eluwa'], 'day': ['esiku'], 'daybreak': ['eluwa', 'momaushu', 'moontundumene'],
     'daylight': ['omutenya'], 'dead': ['sa'], 'deaf': ['thita omakutsi'], 'dealer': ['omulandithi', 'omupindiki'], 'death': ['eso'],
     'debate': ['tompathana', 'patathana', 'omuye'], 'debit': ['odebete'], 
     'debt': ['ongunga', 'onkuma', 'oshikolo'], 'decade': ['oomvuLa omulongo'], 'deceased': ['nakusa', 'omusi'], 'deceit': ['ekotokelo'],
     'deceive': ['kotokela'], 'December': ['Desemba'], 'deciduous tree': ['omuyagumuki'], 'decide': ['tokola'], 'decision': ['etokolo'],
     'decline': ['siluka', 'peguka'], 'decoration': ['uuwopali'], 'decrease': ['shonopeka'], 'decree': ['eutho'], 'deed good': ['ekwathohole'],
     'deep': ['ondeendeka'], 'defeat': ['sindana', 'esindiko'], 'defence': ['eipopilo', 'egameno'], 'defend': ['popila'],
     'deforest': ['kokola'], 'deforestation': ['onkoko'], 'degree': ['ohalate'], 'deity': ['uukalunga'], 'dejected': ['lindimana', 'iyekelela'],
     'dejection': ['elindimano', 'eiyekeielo'], 'delay': ['ugauga', 'kateka', 'eimbo', 'eugaugo'], 
     'delegate': ['omukalelipo', 'omutumwalilepo'], 'deliberately': ['owina'], 'delicacies': ['iitowale'], 'deliciousness': ['uuwanawa'],
     'delight': ['enyanyu'], 'delirious': ['adhuuka'], 'deliriousness': ['eadhuuko'], 'democracy': ['uuyuki'], 
     'democratic': ['pauyuki', 'pademokrate', 'paudemolcoli'], 'demolish': ['kumuna'], 'demolisher': ['omukumuni'], 'Dane': ['Omudenmark'],
     'Denmark': ['Denmark'], 'dense': ['thita'], 'density': ['esiti'], 'dented': ['mbanduka'], 'dentures': ['omayego gopaunkulungu'],
     'department': ['oshikondo'], 'depend': ['ikwatelela'], 'dependence': ['eikwatelelo'], 'dependent': ['omwiikwateleli'], 'deport': ['tidha'],
     'deportation': ['etidho'], 'deposit slip': ['okafilipi okumbaanga'], 'depth': ['uulehi', 'uule'], 'deputy minister': ['omupehaminista'],
     'deputy secretary': ['hangayakUh'], 'descend': ['londoloka', 'heluka', 'elondoloko'], 'describe': ['hokolola', 'tongonona'],
     'description': ['ehokololo'], 'desert': ['ombuga', 'thondola'], 'deserter': ['othondolo'], 'desire': ['haluka', 'tundudha', 'ehalo', 'okahalu'],
     'despise': ['dhina'], 'despising': ['dhinwa'], 'dessert': ['okailathitho'], 'destiny': ['ethikilo'],
     'destroy': ['nyanyula', 'hanagula', 'yona'], 'destruction': ['ehanagulo', 'eyono'], 'detective': ['omupolisi gwomalunga', 'ondiindii'],
     'determination': ['eutho'], 'determine': ['utha'], 'detest': ['nyanyala'], 'detribalised': ['omukoiwakOkathe', 'ombwiti'],
     'devaluate': ['hutuka', 'ngushuluka'], 'devaluation': ['engushuluko'], 'develop': ['huma  komeho'], 'development': ['ehumo', 'ehumokomeho'],
     'deviate': ['peguka'], 'devil': ['omutondi'], 'devils-thorn': ['ondjoho'], 'devour': ['letheka'], 'dew': ['omume'], 
     'dialect': ['onyapilaka'], 'diameter': ['ontaakano'], 'diamond': ['okawe'], 'diaphragm': ['olweedhililo'], 'diarrhoea': ['oshimela'],
     'dictate': ['leshela'], 'dictation': ['ondeshela'], 'dictator': ['kayamukulwa'], 'dictatorship': ['uukayamukulwa'], 'did': ['sha longwa'],
     'die': ['sa'], 'diesel': ['ondiisela'], 'difference': ['ondjoolola', 'eyooloko'], 'differential': ['ondefa'], 'difficult': ['dhigupaila'],
     'difficulty': ['uudhigu', 'olukongo'], 'dig': ['palela', 'papula', 'fukula'], 'digest': ['nyanyagula'], 'digestion': ['einyanko'],
     'digger': ['omufukuli'], 'digging': ['efulo', 'ehupo', 'efumbulo'], 'dignity': ['esimano'], 'diligence': ['ondjungu'],  
     'diligent': ['ndjanga'], 'dilute': ['yulika', 'hampula'], 'dim': ['dhimeya', 'tsima'], 'dimple': ['ondhigilila'], 
     'dining-room': ['oshililo'], 'dinner': ['uulalelo'], 'diplomat': ['omudiplomate'], 'diplomatic': ['paudiplomate'],
     'direct': ['wilika', 'udhika'], 'direction': ['euko', 'ombinga'], 'director': ['omuwiliki'], 'dirt': ['ondoya', 'ekako', 'edhilo'],
     'dirty': ['nyateka', 'luudhika', 'nyata', 'gagala'], 'disagreement': ['okwaatsakumwe'], 'disappear': ['thenena', 'kana', 'nena'],
     'disasters': ['iihuna'], 'disbeliever': ['omukeeneitaalo'], 'discount': ['ekuthiloko'], 'discouraged': ['tyololoka', 'sholola'],
     'discover': ['nongela'], 'discovering': ['enongelo'], 'discrimination': ['oshipungo', 'lya oshipungo'], 
     'discuss': ['kwandjagela', 'kundathana'], 'discussion': ['onkundathana', 'ekundathano'], 'disease': ['omukithi'], 'dish': ['oshiyaha'],
     'dish up': ['hukula'], 'dishearten': ['tyololoka', 'sholola'], 'dishonesty': ['omakoto'], 'disk': ['ongalo'], 'dislike': ['uugelele'],
     'dislocate': ['dhomoka', 'dharnuka'], 'disorder': ['elyalyakano', 'okwaanelandulathano'], 'dispersion': ['ehalakanitho'],
     'display': ['eulukilo', 'etalitho'], 'disregard': ['thithimana', 'dhina'], 'dissatisfied': ['yemata'], 
     'distance': ['ekaakena', 'oshikako', 'oshinano', 'elala'], 'distil': ['dhindola'], 'distribute': ['hawaleka', 'topola'],
     'distribution': ['ehawaleko', 'etopolo'], 'district': ['oshikandjo'], 'disturb': ['zizilika', 'piyaganeka'], 'disturbance': ['eziziliko'],
     'ditch': ['epwampwa'], 'divide': ['pambula', 'topola'], 'divider': ['omutopoli'], 'division': ['oshitopoiwa'], 
     'divorce': ['vekula', 'henga'], 'divorcée': ['omuhengwa'], 'divorcement': ['ehengo', 'ehengathano'], 
     'dizziness': ['oshitelele', 'oshidhungwe'], 'doctor': ['omwaaludhi', 'ondohotola'], 'dodge': ['yanda'], 'does': ['tashi ningi'],
     'dog': ['ombwa'], 'dolphin': ['ondolofine'], 'domestic': ['kwagumbo'], 'dominant': ['omuthindili kongudhi'], 
     'dominate': ['thindila kongudhi'], 'donate': ['gandja'], 'donkey': ['okasino', 'gwamululu', 'okandoongi'], 'donor': ['omugandji'],
     'door': ['omweelo', 'eyambi', 'osheelo', 'oshiyelo'], 'dormouse': ['nalufungu'], 'dot': ['oshitsa', 'okantongo'], 
     'double': ['mbalipaleka', 'ndambula'], 'doubling': ['embalipaleko', 'endambulo'], 'doubt': ['limbililwa', 'elimbililo'], 
     'dove': ['onguti'], 'down': ['pevi', 'pohi'], 'downpour': ['epoola'], 'dowry': ['omagano gehokanitho'],
     'drag': ['koka', 'kookolola', 'pwedha'], 'dragon': ['oshikoko'], 'drain': ['popola', 'kaheka'], 'drainage': ['epopolomeya', 'ekaheko'],
     'dramatic': ['pashinyandwa'], 'draught': ['enkwiya', 'omwiilambepo'], 'draw': ['faneka', 'thaneka', 'tenda', 'sinda', 'kweya'],
     'drawer': ['omuthaneki', 'omufaneki'], 'drawing': ['ethaneko'], 'dream': ['yaguma', 'ondjodhi'],
     'dreamer': ['omuyagumi'], 'dreaming': ['eyagumo'], 'dress': ['ohema'], 'dried': ['kaha', 'kukuta'], 'drift': ['onkondo', 'oshau'],
     'drill': ['mboola'], 'drilling machine': ['omboola', 'omboolamashina'], 'drink': ['indooha', 'nwa', 'oshikunuwa', 'oshinuwa'],
     'drinker': ['omunwi'], 'drinking place': ['enwino'], 'drip': ['ndonda', 'nogela'], 'drive': ['hinga'], 'driver': ['omuhingi'],
     'driving': ['ehingo', 'okuhinga'], 'drizzle': ['okanyaganye'], 'drool': ['yeya'], 'drop': ['eta'], 'dropping': ['ombundu'],
     'drought': ['uulumbu', 'oluteni', 'oshikukuta', 'ompinya', 'ekomba', 'ondjala'], 'drowse': ['kumuka', 'kotha'], 'drug': ['oshingangamithi'],
     'drum': ['ekandiina', 'ondoloma', 'endolondolo', 'ontunda'], 'drunk': ['kolwa'], 'drunkard': ['onkolwe'], 
     'drunkenness': ['uunkolwe'], 'dry': ['kukutu'], 'dryness': ['uukukutu'], 'duck': ['ombaka'], 'due': ['molwa'], 'dugout canoe': ['owato'],
     'duiker': ['ombambi'], 'dumb': ['ombolo'], 'deaf': ['ombolo'], 'dung': ['elombo'], 'during': ['pethimbo'], 'dusk': ['oshiwiwili'],
     'dust': ['pupula', 'ontsi'], 'duty': ['oshinakugwanithwa', 'oshilonga'], 'dwarf': ['okangongolo'], 'dweller': ['ombwiti'], 'dwelling': ['olukaiwa'],
     'dye': ['daya', 'efumika'], 'dynamite': ['ondilimani'], 'dysentery': ['oshitokota', 'oshimela shombinzi']}

e = {'Eagle': ['ekwatandimba'], 'earn': ['mona'], 'earning': ['emoniko', 'okumona'], 'earth': ['evi', 'uuyuni'], 'earthing': ['fila'],
     'earthquake': ['ekakamovi'], 'earthworm': ['oshiyokahi'], 'easier': ['pu unene'], 'east': ['uuzilo'],
     'Easter': ['Opaasa'], 'eastern': ['kuuzilo'], 'easy': ['pu'], 'eat': ['lya'], 'eavesdrop': ['ambela'],
     'eavesdropping': ['eambelo'], 'ebony': ['omwandi'], 'eclipse': ['eluudho'],      'economic': ['paliko'],
     'economy': ['eliko'], 'edge': ['oha', 'olungenge'], 'educate': ['putudha'], 'educated': ['putuki'],
     'education': ['elongo'], 'educational': ['palongo'], 'efficient': ['omudhiginini'], 'effort': ['onkambadhala'],
     'egg': ['eyi'], 'Egypt': ['Egipiti'], 'Egyptian': ['Omweegipiti'], 'eight': ['hetatu'], 'eighth': ['tihetatu'],
     'eighteen': ['omulongo nahetatu'], 'eland': ['ongalangombe'], 'elder': ['kakayiwa'], 'elderly': ['kokele'],
     'eldest child': ['osheeli'], 'election': ['ehogololo'], 'electric': ['gwolusheno', 'yolusheno', 'lyokolusheno'],
     'electric stove': ['esiga lyolusheno'], 'electrician': ['omunalusheno'], 'electricity': ['olusheno'],
     'element': ['oelemende'], 'elephant': ['kahenge', 'ondjamba'], 'eleven': ['omulongo nayimwe'], 'elsewhere': ['shaampoka'],
     'embarrassed': ['gugwa'], 'embassy': ['uulilepo', 'uukalelipo'], 'ember': ['ekala'], 'embrace': ['papatela'],
     'emigrant': ['omutembuki'], 'emigrate': ['tembuka'], 'emigration': ['etembuko'], 'employ': ['kuta'],
     'employee': ['omuniilonga'], 'employer': ['omuhona', 'omukuti', 'omugandji gwiilonga'],
     'employment': ['oshilonga', 'ekuto millonga'], 'empty': ['mwaa na sha'], 'encircle': ['kondeka'],
     'encircling': ['okakuwilili', 'ekondeka'], 'encourage': ['kumika', 'tsa omukumo'], 'end': ['hula'],
     'endeavour': ['lalakana', 'oshilalakanenwa'], 'enemy': ['omutondi'], 'energetic': ['noonkondo', 'oshimati', 'ondjungu'],
     'energy': ['omatha'], 'engaged': ['yaleka'], 'engine': ['oindjina'], 'engineer': ['omwiindjiniya'],
     'engineering': ['uuindjiniya'], 'England': ['Ingilanda'], 'English': ['Oshiingilisa'], 'Englishman': ['Omwiingilisa'],
     'enjoy': ['ketsula', 'nkotsola', 'tyapula'], 'enough': ['gwana'], 'enrichment': ['etanitho'], 'enslave': ['pika'],
     'entertainment': ['einyanyudho'], 'enthusiast': ['omulaadhi'], 'enthusiastic': ['ladhipala'],
     'entrance': ['omweelo', 'oshiyelo'], 'epidemic': ['ekithi'], 'epidemically': ['pakithi'], 'epilepsy': ['oshintona'],
     'equal': ['thike pamwe'], 'equality': ['uuthikepamwe'], 'equipment': ['oshilongitho'], 'equivalence': ['efaathano'],
     'eraser': ['okadhimitho'], 'erect': ['dhika', 'timba'], 'erode': ['wegula'], 'erosion': ['ekanitho', 'ekungululo'],
     'error': ['puka'], 'escape': ['iyaka'], 'especially': ['unene tuu'], 'essay': ['oshinyolwa'], 'establish': ['dhika'],
     'establishment': ['edhikopo'], 'estimate': ['tengeneka', 'fekela', 'etengeneko'], 'eternity': ['uukwaaluhe'],
     'Europe': ['Europa'], 'European': ['oshilumbu', 'omutiligane', 'Omweeuropa'], 'evaluate': ['tala ongushu'],
     'evaluation': ['etalongushu'], 'evening': ['ongulohi'], 'event': ['oshiningwanima'], 'evergreen': ['omwaayagumuki'],
     'every': ['kehe'], 'everybody': ['kehe gumwe'], 'everyday': ['kehe esiku'], 'everyone': ['kehe gumwe'],
     'everything': ['kehe shimwe'], 'everywhere': ['akuhe', 'kehe pamwe'], 'evidence': ['uumbangi', 'uunzapo'],
     'evil-doer': ['oshihwanga', 'omukolokoshi'], 'exactly': ['lelalela'], 'exaggerate': ['dhenga omutoto'],
     'examination': ['ekonakono'], 'examine': ['konakona'], 'examiner': ['omukonakoni'], 'example': ['oshiholelwa'],
     'exceed': ['lunda', 'pitilila'], 'excel': ['ladhipala'], 'except': ['kakele'], 'excrete': ['etudhi'],
     'excuse': ['dhimina po', 'eipopilo'], 'exhaust': ['gundika', 'lolola'], 'exhaustion': ['eloloko'],
     'exhibit': ['onza', 'oshuulikwa'], 'exile': ['pongeka', 'uupongekwa', 'uupika', 'uukwatwa'],
     'exit': ['uupitilo', 'pita mo', 'thiga po'], 'expand': ['fula', 'nenepala'], 'expect': ['tegelela'],
     'expectation':['etegameno'], 'experiment': ['elolelo', 'oshuuvithoko', 'lola', 'ninga omalolelo'],
     'expert': ['omutseyinawa', 'omupyokoki'], 'explain': ['fatulula', 'yelitha'], 'explanation': ['efatululo', 'eyelithilo'],
     'exploit': ['nyokoma', 'thipa ombinzi', 'longitha'], 'exploiter': ['omunyokomi', 'omuthipimbinzi'],
     'extend': ['yedha', 'gwedhela'], 'extension':['egwedhelo', 'oshigwedhwapo'], 'extinguish': ['dhima'],
     'extract': ['kula', 'thipa', 'kutha'], 'extraction': ['ethipo', 'ekutho'], 'exult': ['ligola'],
     'exultation': ['eligolo', 'ondigolo'], 'eye': ['eho', 'tala']} 
     
f = {'fable': ['olungano'], 'face': ['oshipala', 'taalela'],
     'fact': ['oshitsa', 'oshili'], 'factor': ['oshinima'], 'factory': ['ofambulika', 'ofabrika'], 'fade': ['dhimeya'],
     'fail': ['ponya', 'ndopa'], 'fair': ['-yuuki'], 'fairness':['uuyuuki'], 'faint': ['kambuka', 'dhimeya'],
     'fall down': ['mbolokota', 'gwa'], 'fall short': ['kambela'], 'family': ['aanegumbo', 'omukwanezimo', 'egumbo', 'ezimo'],
     'famine': ['uulundu', 'ompinya', 'ekomba', 'oshikukuta', 'ondjala'], 'fan': ['epepelambepo', 'pepela', 'omuholi'],
     'fang': ['ehuga'], 'far': ['kokule'], 'farewell': ['elaleko'], 'farm': ['ofaalama'], 'farmer': ['omunafaalama'],
     'farming': ['uunafaalama'], 'fat':['ondoka', 'paluka', 'omankene', 'omakagadhi','ekagadhi', 'enkene'],
     'fate': ['ethikilo'], 'father': ['tate', 'he'], 'fatherland': ['evalelwamovi'], 'fatness': ['eyondo'],
     'fatten': ['palula', 'ondodha'], 'fault': ['epuko'], 'fear': ['tila'], 'fear': ['uugelele', 'uumbanda'],
     'feast': ['oshituthi', 'oshiindingili'], 'feather': ['olwenya',], 'feature': ['oshidhimbulukiwa'], 
     'February': ['Februali'], 'feeble': ['nkundi'], 'feed': ['palutha'], 'feel': ['uva'], 'feelings': ['omaiyuvo'],
     'feet': ['oompadhi'], 'fell': ['ka', 'keka', 'teta'], 'female': ['omukiintu'],
     'fence': ['gumba', 'ongumbu', 'enkolo', 'olugumbo'], 'ferment': ['konda'], 'fermentation': ['olwani'],
     'fetch': ['teka', 'katale'], 'fever': ['ombulwa'], 'feverishness': ['olwiidhi'], 'few': ['shona'], 
     'fiancé': ['omuyaleki'], 'fiancée': ['omuyalekwa'], 'fibre': ['olundali'], 'field': ['eyana', 'epya','ehenene'],
     'fifteen': ['omulongo nantano'], 'fifth': ['titano'], 'fifty': ['omilongo ntano'], 'fig': ['onkwiyu', 'omukwiyu', 'ondhiye'],
     'fight': ['kondja', 'olugodhi'], 'fighter': ['omukondji'], 'figurative': ['pafano'], 'figure': ['olupe', 'etendwathano'],
     'file': ['elima', 'efaila'], 'fill': ['hota', 'udha', 'zila'], 'film': ['okino', 'ofilima'], 
     'filter': ['dhinda', 'dhindola', 'oshidhinditho', 'ondhindimbapila'], 'final': ['hugunini'],
     'finance': ['umaliwa', 'futila'], 'financial': ['kwamaliwa', 'paimaliwa'], 'finch': ['namusheshe', 'naangongwa'],
     'find': ['adha', 'mona'], 'finding': ['emoniko', 'okumona', 'oshizemo'], 'fine': ['wanawa', 'futitha', 'ofuto'],
     'finger': ['omunwe', 'onyala'], 'index finger':['mutanganwe', 'omuuliko'], 'little finger': ['okanwegona'], 
     'fingernail': ['oshipanyala'], 'finish': ['ndondolidha', 'mana'], 'finished': ['pwa pu', 'mana', 'manuka'],
     'fire': ['omulilo', 'ondalu yanelyanga'], 'fire-extinguisher': ['oshidhimithi'], 'fire-screen': ['omushigo gwomulilo'],
     'firewood': ['oshikuni'], 'firm': ['ofeema', 'ongeshefa', 'pama'], 'firmly': ['thiluthilu'], 'first': ['tango'],
     'firstly': ['tango'], 'fish': ['ohi', 'ndjolala', 'yula', 'yula oohi', 'kwata oohi'], 'fisherman': ['omuyulihi'],
     'boat': ['ombauto'], 'fish-hook': ['okandjolo'], 'fish-trap': ['oshishongo'], 'fist': ['ongonyo'], 'five': ['ntano'],
     'fix': ['mba', 'ukitha'], 'flag': ['epandela'], 'flake': ['weguka'], 'flame': ['hwama', 'lulumuka'], 'flame': ['omutemo'], 
     'flannel board': ['oshipelendelapi'], 'flap': ['dhakwa'], 'flare': ['onyeka'], 'flash': ['shela', 'adhiina', 'gena'],
     'flash-card': ['epakolwanyolwa'], 'flat': ['papa', 'mbugala', 'guguka'], 'flavour': ['dhogeka', 'towaleka', 'oludhi'],
     'flavouring': ['iitowaleki', 'iidhogeki'], 'flea': ['okalipi'], 'fledgling': ['okadhilona'], 'flee': ['okuya ontuku'],
     'flicker': ['welima'], 'flickering': ['omuwelimo', 'ewelimo'], 'float': ['kaama'], 'flock': ['ngundumana', 'ongundu', 'enduwa'],
     'flood': ['eyelu', 'efundja'], 'floor': ['olupanda'], 'flop': ['mbwata'], 'flour': ['uusila'], 'flow': ['kunguluka'],
     'flower': ['shena', 'sheneka', 'ongala'], 'flu': ['ekunku', 'eshikisha'], 'fly': ['tuka', 'ondhi'], 'foam': ['etutu', 'ondutu'],
     'focus': ['ukilila', 'odha'], 'fog': ['osheentsi', 'oshiyentsi'], 'fold': ['gonya', 'omutonyo', 'omugonyo'],
     'follow': ['landula'], 'follower': ['omwiigameki',  'omulanduli'], 'fontanelle': ['oluwewe'], 'food': ['iikulya', 'oondya'],
     'fool': ['egoya', 'elayi'], 'foolishness': ['uulayi', 'uugoya'], 'foot': ['ompadhi'], 'footsteps': ['iikukulilo', 'iikukulo'],
     'forbid': ['dhilika', 'ngambeka'], 'force': ['thiminika', 'thininika', 'thindila', 'ekuni', 'ethiminiko', 'ethindiloko'],
     'forcefully': ['komatha', 'keenkondo', 'paenkondo'], 'forefinger': ['omutanganwe', 'omuuliko'],  'foreign': ['-kwiilongo'],
     'foreigner': ['omukwiilongo', 'omuzaizai'], 'forelock': ['eshuku'], 'foreman': ['folomana', 'omuhona'],
     'forest': ['okuti', 'omugulu'], 'forestry': ['uutekumiti', 'uunamiti'], 'foretell': ['hunganeka'], 'forge': ['hambula', 'pula'],
     'forger': ['omuhambuli', 'omukwaanga', 'omuhambudhi'], 'forget': ['dhimbwa'], 'forgiveness': ['ekuthilo', 'edhiminepo'],
     'form': ['honga', 'tholoma', 'ofooroma', 'ofooloma', 'omutholomo', 'olupe'], 'formula': ['oformula'], 'fort': ['epopilongulu'],
     'forty': ['omilongo ne'], 'found': ['adhika'], 'foundation': ['ekankameno'], 'fountain': ['oluthithiya', 'othithiya'],
     'four': ['ne'], 'fourth': ['-tine'], 'fowl': ['ondjuhwa'], 'fox': ['ombugu'], 'fragment': ['oshitandu'], 'frame': ['oshikulo', 'olama'],
     'France': ['Fransa'], 'free': ['manguluka', 'oshali'], 'freedom': ['emanguluko'], 'freely': ['nemanguluko'],
     'freeze': ['hekela', 'kukutika'], 'French': ['Omufransa'], 'fresh': ['talala'], 'Friday': ['Etitano'], 
     'fridge': ['ofriza', 'onautalala'], 'friend': ['eume', 'kuume', 'memukwetu'], 'fright': ['uumbanda', 'ehaluko'],
     'frighten': ['halutha', 'sosa', 'tilitha'], 'frog': ['efuma'], 'frolic': ['wawanga'], 'from': ['za'],
     'frond': ['epokolo'], 'front': ['komeho'], 'front-end loader': ['embakumbaku lyokutsilika'], 'frost': ['ombambi'],
     'fruit': ['oshiimati', 'oshiyimati'], 'fry': ['kanga', 'yotha'], 'fuel': ['omahooli'], 'fugitive': ['ontauki'],
     'full': ['udha'], 'funeral': ['efumbiko', 'efumviko'], 'funnel': ['ombako'], 'furnishing': ['epoleko'], 
     'furniture': ['iiyopalekigumbo'], 'furrow': ['ofoola'], 'further': ['komeho'], 'fury': ['ongeyo'], 'fuse': ['ontopitha'],
     'future': ['onakuyiwa', 'konakuyiwa', 'komongula', 'uunawangula']}

g = {'gale': ['oshikungulu'], 'gall': ['onyango'], 'gallop': ['ndombola', 'ohalopa'], 'gamble': ['ndombela'],
     'gambol': ['wawanga'], 'game': ['omulowe', 'okatoma', 'uudhano', 'ekondjithathano'], 'gang': ['ongenga', 'ongundu'],
     'gaol': ['ondholongo', 'okakuma', 'ondjedhililo'], 'gap': ['ekolombongo', 'omwaka'], 'garage': ['ongalashe'],
     'garden': ['oshitsambe', 'oshikunino'], 'gardener': ['omunashikunino'], 'garment': ['onguwo'], 'gas': ['ohasa'],
     'gasp': ['hetha', 'fudhagana'], 'gate': ['osheelo'], 'gather': ['gongela', 'ngundumana'], 'gathering': ['oshigongi', 'egongalo'],
     'gear': ['ongela'], 'general': ['kwalukehe'], 'in general':['momumbwalangandjo'], 'generation': ['epipi'], 
     'genitals': ['uulumentu', 'uukiintu'], 'German': ['Omundowishi', 'Oshindowishi'], 'Germany': ['Ndowishi'],
     'germinate': ['mena'], 'get together': ['gongala', 'ya pamwe'], 'get up': ['penduka'], 'get well': ['aluka'],
     'ghonorrhea': ['oshinena', 'okata'], 'ghost': ['oshiluli', 'oshilulu'], 'giant': ['evukule'], 'gift': ['omagano', 'iigandjwa'],
     'gills': ['omahangu'], 'gin': ['olambika', 'ombike'], 'ginger': ['ondjindja'], 'giraffe': ['ombahe', 'onduli'],
     'girl': ['omukadhona', 'okakadhona'], 'girlhood': ['uukadhona'], 'give': ['gandja', 'pa'], 'giver': ['omugandji'],
     'gizzard': ['oshindimba'], 'glad': ['nyanyukwa'], 'gland': ['ondhi'], 'glass': ['ekende', 'ehalasa', 'okahalasa'],
     'gleam': ['adhima'], 'glide': ['telegana', 'tengela'], 'glitter': ['taima', 'adhima', 'welima', 'konita'],
     'glory': ['eadhimo', 'oshinge'], 'glow': ['hanya', 'taima'], 'glue': ['eka', 'olaima', 'onka'], 'glutton': ['omufukedhi'],
     'gluttony': ['uufukedhi'], 'gnaw': ['kunya', 'gunya'], 'gnome': ['okangongolo'], 'go': ['ya', 'inda'],
     'goal': ['okoola', 'oshilalakanenwa'], 'goat': ['newewe', 'oshikombo', 'ekombo'], 'God': ['Nampongo', 'Kalunga', 'Mpambiishita'],
     'gold': ['oshingoli'], 'good': ['-wanawa', 'nawa', 'dhingi', '-kali'], 'goodbye': ['enda po nawa', 'kala po nawa'],
     'goodness': ['uuwanawa', 'uutoye'], 'goose': ['ondjokwe'], 'gossip': ['tota omulombo', 'hokola', 'omutotolombo'],
     'govern': ['lela', 'pangela'], 'government': ['elelo', 'oholomende', 'epangelo'], 'gown': ['engauna', 'eguwo'],
     'grab': ['kwata', 'akula',  'nyekula', 'fegula'], 'grade': ['ondondo', 'ongundu', 'ngundupika', 'yoolola'],
     'grain': ['omuma'], 'granary': ['oshigandhi', 'eshisha'], 'grandfather': ['kuku', 'tatekulu', 'hekulu'],
     'grapefruit': ['opomelo', 'omupomelo'],  'grape': ['omuviinu', 'endjembele'], 'grasp': ['dhamatela', 'kamatela'],
     'grass': ['omwiidhi'], 'grasshopper': ['oshipethipethi'], 'gratitude': ['olupandu'], 'grave': ['ombila', 'eendo', 'eyendo'],
     'gravel': ['oholondo'], 'graveyard': ['omayendo'], 'gravy': ['omuhoka'], 'graze': ['litha', 'napa'],
     'grazing': ['uunapelo', 'uulithilo'], 'grease': ['lomona', 'ngilisa', 'ongilishe'], 'greave': ['oshikange'],
     'greed': ['olwiho'], 'greedy': ['-fukedhi'], 'greediness': ['omuhaka', 'uufukedhi'], 'Greek': ['Omungeleka'],
     'green': ['-zizile', 'ziza'], 'greet': ['popitha', 'kunda'], 'greeting': ['ekundo', 'epopitho'],
     'grey': ['-mbundu', '-tsimine'], 'grief': ['eyeme', 'eyemato', 'oluhodhi'], 'grievance': ['enyenyeto'], 'grind': ['nyanyula'],
     'gripes': ['oshitheta'], 'groan': ['kema', 'nona', 'omukemo'], 'groceries': ['iingolosola'], 'grope': ['ndhindhila'],
     'groundnut': ['ombundufukwa'], 'ground squirrel': ['nyanga'], 'group': ['ongundu', 'ngundupaleka'], 'growl': ['gona', 'kenya'],
     'grub': ['enkandyangali', 'enkandangali', 'ezinyo'], 'grudge': ['iikonene'], 'grumble': ['ngungutula', 'engungutulo'],
     'guard': ['tonatela', 'omutonateli'], 'guardian': ['omutonateli'], 'guava': ['ekwaava', 'omukwaava'],
     'guess': ['fekela', 'tengeneka', 'efekelo', 'etengeneko'], 'guesswork': ['efekelo', 'etengeneko'], 'guilt': ['uusama', 'ondjo'],
     'guinea-fowl': ['onkanga'], 'guitar': ['ekwangwangwa', 'oshiketala'], 'gulf': ['ekololo'], 'gun': ['ondjembo'],
     'gust': ['oshihomo'], 'gutter': ['oshiyakelikunguluki']}

h = {'habit': ['onkalelo', 'ondjigilile', 'omukalo'], 'haft': ['omupini'], 'hail': ['ompawe', 'ompagwe'], 'hair': ['omafufu', 'efufu'],
     'hairiness': ['olufufu'], 'hairdresser': ['omukamuli', 'omupandi'], 'half': ['etata'], 'hall': ['oshinyanga'],
     'hand': ['oshikaha', 'eke'], 'handbag': ['ombuluwaka', 'ondjato yopeke'], 'handicap': ['uulema'],
     'handicapped': ['oshilema', 'omunuulema'], 'handcuffs': ['oomango', 'iiketanga'], 'handle': ['okakongo', 'onkogo', 'oshikwatitho'],
     'handwriting': ['enyolwakaha', 'oshikaha'], 'hangover': ['opapalase'], 'hang': ['endjelela', 'kulumana', 'tsilika'],
     'happen': ['holoka'], 'happening': ['eholokopo', 'eholokepo', 'oshiningwanima'], 'happiness': ['olupolo', 'elago', 'enyanyu'],
     'happy': ['nyanyukwa', 'panda'], 'harbour': ['etulilo', 'etulilosikepa'], 'hare': ['onkwiyu'],  'harness': ['oshikeshele', 'kutila'],
     'harrow': ['oshihelelitho', 'etemo'], 'harvest': ['teya', 'likola', 'eteyo', 'elikolo'], 'hartebeest': ['ohumba'],
     'has': ['na'], 'hasten': ['ulumika'], 'hat': ['egala', 'embale'], 'hate': ['tonda', 'huga', 'oluhuga', 'uutondwe'],
     'hater': ['omutondi', 'omuhugi'], 'haughtiness': ['oshilundo'], 'have': ['na'], 'hawk': ['ekodhi'], 'he': ['ye'],
     'head': ['omutse', 'uka'], 'head on': ['hwanuka', 'omutse nomutse'], 'headache': ['oshipwatagula'], 'headcloth': ['oshikayiwa'],
     'heading': ['oshipalanyolo'], 'heal': ['pola', 'aludha', 'aluka'], 'healing': ['ealudho', 'ealuko'],
     'health': ['uundjolowele', 'uukalinawa'], 'heap': ['ndumbala', 'ndumbila', 'ondumba'], 'hear': ['uva'],
     'hearing': ['iihokolola'], 'heart': ['omutima'], 'heartburn': ['oshingulila'], 'hearth': ['esiga'],
     'heat': ['omuyenye', 'uupyu', 'pupyaleka'], 'heathen': ['omupagani'], 'heating': ['epupyalo'], 'heave up': ['tuna'],
     'heaven': ['egulu'], 'heavy': ['-dhigu'], 'hedgehog': ['nikitha'], 'height': ['omutumbo', 'uule'], 'heir': ['omuthigululi'],
     'heel': ['oshithi'], 'heiress': ['omuthigululi'], 'helicopter': ['edhagadhaga'], 'hell': ['ekano', 'oheli'],
     'helmet': ['ombashiya', 'egala lyombashiya', 'ekoko'], 'help': ['kwatha', 'ekwatho'],
     'helper': ['omukwathi', 'omuwateli', 'omukwatheli', 'omuyakuli'], 'helplessness': ['uukeenankondo'], 'hemorrhage': ['etiko lyombinzi'],
     'hen': ['onkadhindjuhwa'], 'herb': ['olundjangwiti', 'oshihemba'], 'herd': ['litha', 'oshigunda', 'uusita'],
     'herd boy': ['omusita', 'omulithi'], 'here': ['mpaka'], 'Herero': ['Omuherero', 'Omushimba', 'Oshiherero'], 'heritage': ['uuthiga'],
     'hero': ['ependa', 'ofule'], 'hesitate': ['ungaunga', 'kakadhala', 'kwatakwata'], 'hesitation': ['eungaungo', 'ekakadhalo', 'ekwatakwato'],
     'hide': ['holeka', 'holama'], 'high': ['-le', '-nde'], 'hijack': ['kwata ko osheenditho'], 'hill': ['oshikulundundu'], 
     'hillock': ['oshituntu'], 'himself': ['ye mwene'], 'hindrance': ['omukundu'], 'Hindu': ['Omuhindu'], 'hinge': ['ekandula'],
     'hint': ['ondunge'], 'hip': ['onto'], 'hippopotamus': ['ondjambameya', 'ongololo'], 'hire': ['thitha'],
     'his': ['ye', 'she', 'ke', 'he'], 'historian': ['omunandjokonona'], 'history': ['ondjokonona'],
     'hit': ['dhenga', 'gopola', 'thepagula', 'dhengagula', 'thandula'], 'hoarse': ['omuthitawi'], 'hoe': ['lima', 'papula', 'etemo'],
     'hole': ['oshilambo', 'ombululu', 'okwena', 'eumba', 'ombwili'], 'hold': ['papatela', 'kwata'], 'holiday': ['efudho'],
     'hollow out': ['kolola', 'hoka'], 'hollow': ['kolola', 'hoka', 'ekololo', 'omututu'], 'Holy Communion': ['Uulalelo Uuyapuki', 'Oshililo'],
     'holy': ['-yapuki'], 'homeless': ['epongo'], 'homesick': ['ponga', 'yuulukwa'], 'homestead': ['egumbo'], 'honey': ['omagadhi goonyushi'],
     'honeycomb': ['ehila lyomagadhi goonyushi'], 'honey badger': ['mbuluyamunkete', 'ndithi'], 'honour': ['simaneka', 'tumbaleka', 'esimaneko'],
     'hoof': ['ekondo'], 'hook': ['haka', 'patekena', 'ongona'], 'hoopoe': ['dhepupu'], 'hoot': ['dhenga ombenda'], 
     'hooter': ['ombenda'], 'hop': ['tanta', 'humpuka'], 'hope': ['inekela', 'tegamena', 'einekelo', 'etegameno'],
     'horizon': ['ongengegulu'], 'horn': ['oluniga', 'ombenda'], 'hornbill': ['ekoko', 'epumputu'], 'horse': ['okakambe', 'onkambe'],
     'hosepipe': ['omunino gomeya'], 'hospital': ['oshipangelo'], 'hostility': ['ontyayi', 'uutondwe'], 'hot': ['-pyu'],
     'hotel': ['ohotela'], 'hour': ['otundi', 'owili'], 'house': ['ongulu', 'egumbo', 'onganda'], 'household': ['iikwagumbo'],
     'house plan': ['omusindilogumbo'], 'how': ['ngiini', 'nkene'], 'hum': ['izizima'], 'humiliate': ['sitha ohoni'],
     'humility': ['eifupipiko'], 'hump': ['oshituntu', 'oshikulundundu', 'etunda'], 'hunch': ['kotama'],
     'hunchback': ['oshinkundundu'], 'hundred': ['ethele'], 'hunger': ['onkudhi', 'ondjala'], 'hunt': ['konga', 'yewa', 'yanga'],
     'hunter': ['omukongo'], 'hunting party': ['uukongo'], 'hurry': ['endelela', 'uluma', 'tsitsimika', 'ulumika'],
     'hurt': ['ehameka', 'tolokana', 'yemateka'], 'husband': ['omulumentu', 'omulume', 'omusamane'],
     'hyena': ['embungu', 'onkutha', 'shimbungu', 'shidhengeni'], 'hygiene': ['uukalinawa', 'uundjolowele', 'uuyogoki'],
     'hypocrite': ['omufudhime'], 'hypocrisy': ['uufudhime']}

i = {'I': ['ngame', 'ngaye'], 'ice': ['iikangwa', 'omaaisa'], 'idea': ['owino', 'ondunge', 'edhiladhilo'],
     'if': ['ngele', 'uuna', 'ando'], 'ignorance': ['uukwaashiwo'], 'iguana': ['ekakala'], 'iilegally': ['shaali paveta'],
     'ill health': ['oshigombo'], 'ill': ['ehama'], 'illegal': ['pwaa shi paveta'], 'illness': ['omukithi', 'uuwehame'],
     'image': ['oshifetha', 'ethano'], 'imagination': ['efekelo'], 'imagine': ['fekela'], 'imitate': ['holela'],
     'imitation': ['eholelo'], 'immediately': ['nziya', 'mbala'], 'immerse': ['yayeka'], 'immigrant': ['omutembuki'],
     'immigration': ['etembuko'], 'immunisation': ['etuntilo', 'otuntila'], 'immunise': ['tuntila'], 'impala': ['ompalala'],
     'impatience': ['oshinyenu'], 'impediment': ['omukundu'], 'impertinence': ['uukandala', 'omanganga'],
     'importance': ['omupondo', 'esimano'], 'important': ['simana'], 'imprint': ['kadhula', 'kodhola', 'ekodholo'],
     'improve': ['hwepopala', 'hwepopeka'], 'improvement': ['ehwepopalo', 'ehwepopeko'], 'in': ['m-'], 'incite': ['tsitsimika'],
     'inciter': ['omutsithimaminimini', 'omutsitsimiki'], 'include': ['kwatela'], 'income': ['iiyemo'],
     'increase': ['indjipala','tanitha', 'indjipaleka', 'etaneko', 'eindjipalo'], 'indefinite': ['ongandi'],
     'independent': ['sha manguluka', 'ithikamena'], 'India': ['India'], 'Indian': ['Omwiindia'], 'indictment': ['etamaneko'],
     'influence': ['enwethomo', 'nwethamo'], 'inform': ['kundaneka', 'lombwela', 'tseithila'],
     'information': ['eyelithilo', 'uuyelele'], 'inhabitant': ['omukalimo', 'omukali'], 'ink': ['otinde', 'ohinga'],
     'inlet': ['oshimpoko'], 'inquisitiveness': ['uutaledhi', 'uutalambambi', 'okatalekonawa'], 'insane': ['-pwidhi'],
     'insect': ['okapuka'], 'insecticide': ['omuti gwuupuka'], 'inservice': [ 'miilonga'], 'inside': ['meni'],
     'inspect': ['konakona'], 'inspection': ['ekonakono', 'etalelo'], 'inspector': ['omukonakoni', 'omutaleli'],
     'inspire': ['kumika', 'hokitha'], 'install': ['tula'], 'instance': ['ngaashi', 'oshiholelwa'], 'instead': ['peha'],
     'instigation': ['omaminimini', 'omangumingumi'], 'instruct': ['lombwela'], 'instruction': ['elombwelo'], 
     'instrument': ['oshilongitho', 'oshilongithwa'], 'insurance': ['etimaumbwile', 'egameno'], 'insurgent': ['omuniipotha'],
     'intelligence': ['oondunge', 'onanguwi'], 'intelligent': ['omunandunge'], 'intelligible': ['uvika', 'uvitike'],
     'interest': ['eitulomo', 'iihohela'], 'interject': ['kwata melaka'], 'interjection': ['oshityankumwe'],
     'internal': ['pokati', '-meni'], 'international': ['paigwana', 'pauyuni'], 'interrogate': ['pulidha'],
     'interview': ['konakona', 'pulapula', 'ekonanoko', 'omapulapulo'], 'intestine': ['endjandja'], 'into': ['m-'],
     'intoxicate': ['kolitha'], 'intoxicated': ['kolwa'], 'introduction': ['efalomo'], 'invest': ['pungula', 'siikilila'],
     'investigate': ['nongonona', 'konakona'], 'investigator': ['omukonakoni', 'omunongononi'], 'investment': ['epungulo'],
     'investor': ['omupunguli'], 'invisible': ['shaa wetike'], 'invitation': ['ehiyo'], 'invite': ['hiya'], 'Ireland': ['Ireland'],
     'iron': ['kangula', 'oshikangule', 'oshiyela', 'osheela', 'oshitenda'], 'irrigate': ['tekela'], 'irrigation': ['etekelo'],
     'irritate': ['piyaganeka'], 'irritation': ['etito', 'epiyaganeko'], 'island': ['ontuntu'], 'Israel': ['Israeli'],
     'Israeli': ['Omwiisraeli'], 'issue': ['gandja', 'oshikumungu'], 'it': ['sho'], 'Italian': ['Omwiitalia'], 'Italy': ['Italia'],
     'itch': ['nywa', 'nyu', 'ohwehwe'], 'item': ['oshinima'], 'itself': ['sho shene']} 

j = {'jack up': ['ndjeka'], 'jack': ['ondjeke'],
     'jackal': ['kaandje', 'ombandje'], 'jacket': ['ombayikitha'], 'jackhammer': ['omundjini'], 'January': ['Januali'],
     'Japan': ['Japan'], 'Japanese': ['Omujapan'], 'jealous': ['tsa ondumbo', 'kodhilila', 'sa efupa'],
     'jealousy': ['efupa', 'uukodhi', 'ondumbo'], 'jeep': ['ondjipa'], 'jelly': ['omayoyo', 'oyeli'], 'jerk': ['hilagula'],
     'jersey': ['ombindja', 'evole'], 'jingle': ['kelengendja'], 'job': ['oshilonga'],
     'joke': ['tegula', 'shendjula', 'omandjenga', 'omashendjo', 'oshileva', 'omategu'], 'jolt': ['puma'], 
     'journalist': ['omuniifo', 'omutoolinkundana'], 'journey': ['enda', 'oondjenda', 'olweendo'],
     'judge': ['pangula', 'omutokoli', 'omupanguli'], 'judgement': ['epangulo', 'etokolo'], 'jug': ['ekopi'], 'July': ['Juli'],
     'jump': ['ndjomboka', 'tanta', 'nuka', 'omundjomboko', 'enuko'], 'jumper': ['omunuki', 'ombindja', 'evole'],
     'June': ['Juni'], 'jurist': ['omunongompango'], 'just': ['owala', '-yuuki'], 'justice': ['uuyuki'],
     'jut': ['anduka', 'pita ko', 'pita mo']}
     
k = {'Kenya': ['Kenya'], 'key': ['oshipatululo', 'oshapi'],
     'kick': ['thanga', 'omuthi', 'oluna'], 'kicker': ['omuthangi'], 'kid': ['okakombwena', 'okanona'],
     'kidnap': ['mbemba po', 'kwata ombambyona'], 'kidnapping': ['embembopo', 'ekwatombambyona'],
     'kidney': ['oshitishanathigo', 'othigo'], 'kill': ['dhipaga'], 'killer': ['omudhipagi'], 'killing': ['edhipago'],
     'kilogram': ['okilograma'], 'kilometre': ['okilometa'], 'kind hearted': ['omunambili'], 'kindle': ['tema'],
     'king': ['omukwaniilwa', 'ngeyama'], 'kingdom': ['uuhamba'], 'kitchen': ['okombitha', 'elugo'],
     'kite': ['kayimbi', 'embiimbili'], 'knavishness': ['omakoto'], 'knee': ['ongolo'], 'kneel': ['tsa oongolo'],
     'knife': ['ombele'], 'knock': ['konkola'], 'knot': ['oshitholongonyo', 'dhitika', 'edhita'],
     'know': ['shi', 'shiwa', 'shuwa', 'tseya'], 'knowledge': ['ontseyo'], 'known': ['shiwike', 'omushiwikile'],
     'knuckle': ['onkankonya'], 'Korea': ['Korea'], 'kraal': ['oshigunda'], 'kudu': ['oholongo'],
     'Kwangali': ['Omukwangali', 'Oshikwangali'], 'Kwanyama': ['Omukwanyama', 'Oshikwanyama', 'Uukwanyama']}

l = {'laboratory': ['olabora'], 'labour': ['iilonga'], 'labourer': ['omuniilonga'], 'ladder': ['ompani', 'oshilondelo'],
     'ladle': ['ompindo', 'pinda'], 'lair': ['omvugo'], 'lake': ['etale'], 'lamb': ['okanzigona'], 'lame': ['omusilombanda'],
     'lamp': ['olamba'], 'land': ['evi', 'nambela'], 'landowner': ['mwene gwevi', 'nakulikola evi'], 'language': ['elaka'],
     'large': ['-nene'], 'last': ['hugunini', 'hugunina', 'ya za ko', 'gwa za ko'], 'last long': ['kala po ethimbo'],
     'lastly': ['hugunina'], 'late': ['laata'], 'the late': ['nakusa'], 'later': ['konima', 'nale', 'lwanima'],
     'lath': ['olunwa'], 'latrine': ['okandjugo'], 'laugh': ['yola'], 'laughter': ['eendjola'], 'lava': ['eloya epyu'],
     'law': ['oshipango', 'ompango', 'oveta'], 'lawn-mower': ['oshimwitho', 'oshitetitho shomwiidhi'],
     'lawsuit': ['iihokolola'], 'lawyer': ['omunongompango', 'ohahende'], 'lay': ['vala'],
     'laziness': ['uunyenge', 'uunye', 'uunyolowe'], 'lazy': ['omunanyalo', 'omunyenge'], 'lead': ['lela', 'pangela', 'kwatela komeho'],
     'leader': ['omuleli', 'omupangeli', 'omukwatelikomeho'], 'leadership': ['ewiliko', 'elelo'], 'leadwood': ['omukuku'],
     'leaf': ['efo'], 'leak': ['hiha', 'ziya', 'ndonda', 'ehiho', 'eziyo', 'endondo'], 'lean': ['kumbala', 'nanga', 'nama', 'egamena'],
     'leanness': ['uukumba', 'ekumbalo'], 'learn': ['ilonga'], 'learner': ['omwiilongi', 'omunasikola', 'omulongwa'],
     'leave': ['etha', 'thiga', 'efudho'], 'leech': ['ehundju'], 'left': ['olumoho', 'thiga po'], 'legist': ['omunongompango'],
     'lemon': ['ongongo', 'omugongo'], 'lender': ['omuheheli'], 'length': ['omukokomoko', 'omukonga', 'uule'],
     'lengthen': ['lepala', 'lepeka'], 'lens': ['omuni'], 'leopard': ['ongwe'], 'leper': ['omunashilundu', 'omunuulepela'],
     'leprosy': ['oshilundu', 'uulepela'], 'less': ['shona'], 'lessen': ['shonopeka', 'shonopala'], 'become less': ['shonopala'],
     'lesson': ['oshileshwa', 'oshilongwa'], 'letter': ['omukanda', 'ombilive', 'okanyolo', 'ontumwafo'], 'level': ['ondondo'],
     'lewd person': ['omuholume'], 'lewdness': ['uuholume'], 'liar': ['omuniifundja','omufundja'], 'licence': ['olisensa'],
     'licentious person': ['omuholume'], 'licentiousness': ['uumpwani'], 'lick': ['latha','itapula'],
     'licking': ['eitapulo', 'eilatho'], 'lid': ['oshisiikilitho', 'oshisiikilo', 'oshimato'], 'lie':['lala', 'fundja', 'iifundja'],
     'lies': ['omutoto', 'iifundja'], 'life': ['okukalamwenyo', 'omwenyo', 'onkalamwenyo'],
     'lift': ['leka', 'yambula', 'yelutha', 'tumba', 'embamba', 'olefa'], 'light': ['hwameka', 'tomeka', 'minikila', 'pu'],
     'lighter': ['oshitoloha'], 'lightning': ['okashelu', 'olwaadhi', 'omalwaadhi', 'oombadhi'],
     'like': ['nga', 'ngawo', 'ngaaka', 'panda', 'hole', 'fa'], 'lime': ['okaalaka'], 'limit': ['ngambeka', 'ongamba'], 
     'limp': ['tina', 'shongola'], 'line': ['omukweyo', 'omusinda'], 'lineage': ['epipi'], 'linger': ['utuuta', 'hepitha'],
     'lining': ['ofulunga'], 'lion': ['ondumbu', 'onkoshi', 'onime', 'kafute kanegaga'], 'lip': ['omulungu', 'okalungu'],
     'liquid': ['oshikunguliiki'], 'liquor': ['engandja', 'olambika', 'iikolitha', 'omalovu'], 'list': ['elandulathano'], 
     'listen': ['pulakena'], 'listener': ['omupulakeni'], 'listless': ['leela'], 'literature': ['uunamambo'], 'litre': ['olitela'],
     'little': ['kashona'], 'live': ['kala', 'lumba', 'hupa'], 'liver': ['ehuli'], 'livestock': ['oshimuna', 'iimuna'],
     'lizard': ['eyengele', 'eengele'], 'load': ['londeka', 'ofulaha'], 'loader': ['omutumbi'],
     'loaf': ['pwampwagana', 'mwamwala', 'omushi'], 'loafer': ['othondolo', 'omweendaguli'],'loan': ['hehela'],
     'loan': ['omukuli', 'gandja omukuli'], 'location': ['olukanda', 'ehala'], 'lock': ['pata', 'ekumba'],
     'locomotive': ['omutse gweshina'], 'locust': ['ombahu', 'epathipathi'], 'lodge': ['menekela', 'oloodja'],
     'loft': ['oombuli', 'oshihaya'], 'loftiness': ['olutumbo'], 'log': ['ekumbeti'], 'logo': ['epapa', 'oshilimbo'],
     'loneliness': ['uuwike', 'uuza', 'ezaza', 'owike'], 'long': ['le', 'ondeendeka'], 'long for': ['yuulukwa'],
     'longing': ['ondjuulukwe'], 'look at': ['tala', 'legalega', 'lengalenga', 'talatala', 'ugauga', 'wendjawendja'],
     'loose': ['yula', 'yegeya'], 'loot': ['oshihakanwa', 'hakana'], 'Lord': ['Omuwa'], 'lorry': ['ololi'],
     'lose': ['dhengwa', 'kanitha'], 'lost': ['kana'], 'lotion': ['omagadhi'], 'lout': ['oshintu'], 'love': ['hole', 'hola'], 
     'lovely': ['holike'], 'lowing': ['lila', 'elilo'], 'loyalty': ['evuliko', 'einekelo'], 'lubricate': ['gwayeka', 'nengeneka'],
     'lucerne': ['olusiana'], 'luck': ['elago', 'ompolo', 'olupolo'], 'luckily': ['lago enene'],
     'Lüderitz': ['Okakoveiwa', 'Oliindili'], 'luggage': ['omutsalo'], 'lukewarm': ['lomoka', 'ziluka'], 'lull': ['kotheka'],
     'lung': ['epunga'], 'lurch': ['funga'], 'lure': ['heka', 'eheko'], 'lynx': ['ehinga']}
 
m = {'machine': ['eshina'], 'madam': ['efolo', 'feelani'], 'magazine': ['engandjiina', 'oshifonkundana'], 'magnet': ['engeneta'],
     'magnetic': ['kwamangeneta'], 'magic': ['uumpulile'], 'magician': ['ompulile'], 'magistrate': ['mangestrata'],
     'maggot': ['othithi'], 'mahangu': ['omahangu', 'ehangu'], 'mail': ['opoosa', 'ontumwafo', 'ombapila'], 'maize': ['epungu'],
     'major': ['-nene'], 'make': ['ninga', 'oludhi'], 'maker': ['omuningi'], 'malaria': ['olwiidhi', 'omalaria'],
     'male': ['omulumentu', '-lumentu'], 'mamba': ['ontoka'], 'mammal': ['yamithi'], 'man': ['omulumentu', 'ekanda', 'omulume'],
     'manage': ['pondola', 'wilika', 'pangela', 'tonatela'], 'management': ['ewiliko'], 'manager': ['menindjela', 'omuwiliki'],
     'manda': ['omumafldalina', 'omulengendenge'], 'manget': ['omunkete'], 'manner': ['omuhingo', 'omukalo'],
     'manuscript': ['oshinyolwa'], 'missile': ['omisile'], 'missing': ['kani', 'kana'], 'mission': ['etumo', 'elalakano'],
     'missionary': ['omuhongi', 'omutumwa'], 'missus': ['meme'], 'mist': ['ombundu'], 'mistake': ['epuko'], 'mister': ['tate'],
     'mistiness': ['oshiyentsi', 'osheentsi'], 'mistress': ['ohonda'], 'mix': ['myanka', 'nyanga', 'pilula'],
     'mixed up': ['vundakana', 'lyalyakana', 'piyagana', 'napakana'], 'mixture': ['evundakano', 'oshipilili', 'onyanka', 'epiyagano'],
     'moan': ['kema'], 'moan': ['ekemo'], 'mock': ['sheka', 'enyonkelo', 'esheko'], 'model': ['omodela'],'moisten': ['tutika'],
     'moisture': ['oshimuto', 'uututo', 'oshitosi', 'oshimuke'], 'molar': ['etayego'], 'mole': ['othile', 'onkwi', 'ontunankwi'],
     'molecule': ['omolekule'], 'moment': ['okathimbo', 'ethimbo'], 'Monday': ['Omaandaha'], 'money': ['omambambi', 'oshimaliwa'],
     'mongoose': ['amwili'], 'many': ['-ndji'], 'map': ['okaalita'], 'marble': ['okamanya'], 'March': ['Marsa'],
     'margarine': ['omagadhi'], 'marijuana': ['epangwe'], 'marine': ['-kwafuta'], 'mark': ['ndhindhilika'],
     'mark': ['oshaala', 'oshiwawi', 'oshilwadhi'], 'market': ['oshilandelo', 'oshilandaiithilo', 'omalandithilo'],
     'marriage': ['ondjokana'], 'marrow': ['omongo'], 'marry': ['fukika', 'hokana'], 'marsh': ['edhiya'], 'marula': ['omugongo'],
     'masked weaver': ['enza'], 'material': ['oshinima', 'oshilongitho', 'oshiyata'], 'match': ['okapaiwa','uudhano', 'ethigathano'], 
     'mathematics': ['omatematika', 'omwaalu'], 'mattress': ['etalashe'], 'maw': ['oshiteta'], 'maximum': ['pombanda', 'omaksimuma'],
     'May': ['Mai'], 'me': ['ngame'], 'mayor':['mayola'], 'meal': ['uusila', 'iikulya'], 'meander': ['ngolyauka', 'dhingakana'], 'meaning': ['eityo'],
     'means': ['iisimpo', 'iimaliwa'], 'measles': ['okakwenyene'], 'measure': ['yeleka', 'ondjele'], 'measurement': ['ondjele'],
     'meat': ['onyama'], 'mechanic': ['makeninga', 'omupangeli'], 'medicine': ['omuti', 'omiti', 'uunamiti'],
     'medlar': ['ombu', 'oshimbu'], 'meet': ['tsakaneka', 'tsakanena'], 'meeting': ['oshigongi', 'etsakaneno'],
     'melodica': ['okahumba'], 'melt': ['hengumuka'], 'member': ['oshilyo'], 'membership': ['uukwashilyo'],
     'memorise': ['koneka nomutse'], 'mend': ['andeka'], 'Mercedes Benz': ['Omashete'], 'merchandise': ['ilpindi', 'iilandithomwa'],
     'merchant': ['omulandithi', 'omupindiki'], 'mercy': ['ohenda'], 'merit': ['merita', 'uukoma', 'uuhwangu'], 
     'message': ['etumwalaka', 'elaka'], 'messenger': ['omweeti', 'omufali', 'omutumwa'], 'midday': ['omutenya'],
     'middle': ['etifa', '-ati', 'oshiya'], 'midnight': ['uusikukati'], 'midwife': ['omuvalithi'], 
     'militant': ['ngenda', 'genda'], 'military': ['uukwiita'], 'milk': ['kanda', 'omahini'], 'milky-way': ['omulalawili'],
     'millet': ['ehangu'], 'million': ['omiliyona'], 'millipede': ['ongoongololo'], 'mind': ['omadhiladhio'], 'mine': ['omina', '-ndje'],
     'miner': ['omunamina'], 'minerals': ['iikwamevi', 'iikwamongwa'], 'minimum': ['-pevi'], 'minute': ['omunute', 'okashona'],
     'minutes': ['oshiningwapo', 'eeminute'], 'mirror': ['okatengelelo', 'esipili'], 'miser': ['ongundja', 'ondalapata', 'omuluya'],
     'misery': ['uukweyi'], 'misfortune': ['omupya'], 'miss': ['palutha', 'yuulukwa', 'efolo', 'yefolou'],
     'monk': ['omwiikaleli'], 'monkey': ['onkima', 'lunkima'], 'monster': ['evukule'], 'month': ['omwedhi'],
     'moody': ['oshizimbi', 'oshinyenu'], 'moon': ['omwedhi'], 'moorhen': ['onkwinkwiti'], 'mopane': ['omusati'],
     'more': ['-ndji'], 'moreover': ['nokuli'], 'morning': ['ongula'], 'morning star': ['magwila'], 'mortality': ['omaso'],
     'mosquito': ['omwe'], 'mostly': ['unene'], 'moth': ['embiimbili'], 'mother':['meme', 'yina'],
     'motor car': ['oshihauto', 'etukutuku'], 'motorcycle': ['okapakapaka'], 'motto': ['omoto'], 'mould': ['oshushi', 'tholoma'],
     'mountain': ['ondundu'], 'mourn': ['lila', 'nika oluhodhi'], 'mourner': ['omunaluhodhi', 'omulilisa'],
     'mouse': ['embundu', 'ombuku'], 'mouth': ['okana'], 'mouth organ': ['okafilita'],'move': ['tembuka', 'kuyunguta', 'inyenga'],
     'movement': ['einyengo', 'omunyengo'], 'mover': ['omutembuki'], 'move anxiously': ['nyulukuta'], 'mucus': ['omanino'],
     'mud': ['omunoko', 'enono', 'ontopo'], 'muddy': ['vongoka'], 'mudguard': ['epeko'], 'mug': ['oshitenga', 'yuga'],
     'mule': ['emulutiya', 'emwili'], 'multitude': ['uuwindji', 'engathithi'], 'mumble': ['ngungutula', 'engungutulo'],
     'mumbling': ['engungutulo'], 'mumps': ['okakombo'], 'municipality': ['muni'], 'murder': ['dhipaga', 'edhipgo'],
     'murderer': ['omudhipagi'], 'muscle': ['ontumba', 'omatha'], 'mushroom': ['okahilili'], 'music': ['oongalo', 'omaimbilo'],
     'musician': ['omuhikingalo', 'nakuhikuuhumba'], 'musk cat': ['okangungumani'], 'Muslim': ['Omumoslema'],
     'must': ['na oku'], 'mutter': ['dhilomota'], 'muzzle-loader': ['engondo']}

n = {'naturally': ['paunshitwe'], 'nature': ['uushitwe', 'uunshitwe', 'uukwatya'], 'naughtiness': ['uutsini', 'uupote'],
     'naughty': ['pota', '-tsini'], 'nausea': ['okukunkutwa'], 'nauseate': ['mbilinga'], 'navel': ['ekuvu'],
     'Ndonga': ['Oshindonga', 'Omundonga', 'Ondonga'], 'near': ['popepi'], 'nearly': ['masiku', 'konyala', 'lunga'],
     'neat': ['opala'], 'neatness': ['uuyogoki', 'uuhaya'], 'neck': ['othingo'], 'nail': ['ondungo', 'omboha', 'oshipanyala'],
     'naked': ['omudhu', 'owala'], 'Nama': ['Omunama'], 'name': ['tumbula', 'thamuna', 'tomona', 'edhina'],
     'namesake': ['mbushe'], 'Namibia': ['Namibia'], 'Namibian': ['Omunamibia', 'lyaNamibia', 'shaNamibia'],
     'nape': ['ekothi'], 'nappy': ['omunambo'], 'narrator': ['omuhokololi'], 'narrator':['hokolola'], 'narrow': ['thinana'],
     'nation': ['oshigwana'], 'National Assembly': ['Oshigongi Shopashigwana', 'Egumbo Lyopashigwana', 'Omutumba Gwopashigwana'],
     'necklace': ['okalyenge'], 'need':['hepa', 'pumbwa', 'ompumbwe', 'oluhepo'], 'needle': ['onane'],
     'negotiate':['kundathana'], 'negotiation': ['oonkundathana'], 'neighbour': ['omushiinda'],
     'neighbourhood': ['omudhingililo', 'uushiinda', 'omudhingoloko', 'omukunduko', 'uupopepi'], 'nematode': ['onematode'],
     'nephew': ['gwaantsezi'], 'nervous': ['lyalyakana', 'ngwangwana', 'mbandapala', 'tila'], 'nest': ['oshihandhila'],
     'net': ['ondjandja', 'onete'], 'netball': ['etanga lyomokambamba'], 'never': ['nande'], 'new': ['pe'],
     'newcomer': ['kashuku', 'onyuwana'], 'news': ['omulombo', 'onkundana', 'oonkundana'], 'newspaper': ['oshifonkundaneki'],
     'next': ['kooha', 'tegama', 'ontega'], 'nice': ['wanawa', 'toye'], 'niece': ['gwontsii'], 'Nigeria': ['Nigeria'],
     'Nigerian': ['Omunigeria'], 'night': ['uusiku'], 'nightjar': ['lumbamba'], 'nine': ['omugoyi'], 'nipple': ['egundji'],
     'nit': ['ondji'], 'no': ['aawe', 'aawoo'], 'nod': ['komona', 'ekomono'],
     'make noise': ['uyagana', 'kudhila', 'yogelela','yayagana', 'lokosha'],
     'noise': ['euyagano', 'ekudhilo', 'eyogelelo', 'ombuya', 'ondokosho', 'olwango','oshikwelengi', 'ewi'],
     'norms': ['oohedhi'], 'north': ['olundume', 'uukwanyamantu', 'uumbangalantu', 'onooli'],
     'northern': ['kuumbangalantu', 'kolundume', 'konooli'], 'Norway': ['Norway'], 'nose': ['eyulu'],
     'nostalgic': ['ponga', 'yuulukwa'], 'nostalgia': ['uupongo', 'ondjuulukwe'], 'not': ['ha'], 'notch': ['nega', 'nogola'],
     'note': ['ndhindhilika', 'edhindhiliko', 'efo'], 'notes': ['onota'], 'nothing': ['pwaa na sha'],
     'noun': ['oshityadhina'], 'November': ['Novomba'], 'novice': ['kashuku', 'onyuwana', 'omupe'], 'now': ['ngashingeyi'],
     'nowadays': ['ethimbo lyongashingeyi'], 'nuclear power': ['oonkondolute'], 'nucleus': ['olute'], 'nude': ['omudhu'],
     'number': ['omwaalu', 'onomola'], 'numerical': ['paeyenomola'], 'nurse': ['omupangi'],
     'nut': ['omuta', 'ofukwa', 'ombundufukwa', 'ehuku']}

o = {'obstinate': ['omuthengalali'], 'obtain': ['likola'], 'occasion': ['ompito'], 'occasionally': ['oolumwe'],
     'occiput': ['onkome'], 'occupant': ['omukaatumbi', 'omukalimo'], 'ocean': ['efuta'], 'October': ['Kotooba'],
     'offend': ['shundula', 'ehameka', 'yemateka'], 'offering': ['eyambo', 'ondjambo'], 'office':['ombelewa'],
     'officer': ['omunambelewa'], 'official': ['omukwanepangelo', 'omunambelewa'], 'officially': ['papangelo', 'pambelewa'],
     'often': ['olwindji', 'olundji'], 'oh': ['akutu'], 'oil': ['omagadhi', 'omahooli'], 'ointment': ['omugwayo'],
     'old': ['kulupa', '-nale'], 'olive': ['omono'], 'on': ['k-'], 'once': ['lumwe', 'oshita'], 'one': ['-mwe'],
     'onion': ['onyanga'], 'only': ['-ike'], 'open': ['patuluta', 'egulula', 'pashula', 'eguluka', 'patuluka'],
     'openbilled stork': ['endongo', 'endongondongo'], 'opening': ['uupitilo', 'ompito', 'ombululu'],
     'operate': ['tanda', 'longitha'], 'operation': ['etando', 'elongitho'], 'operation theatre': ['oshitandelo'],
     'operator': ['omulongithi'], 'opponent': ['omukondjithi'], 'opportunity': ['ompito', 'olweedhe', 'olufo'],
     'oppose': ['kondjitha'], 'opposite': ['ekondjithathano', 'ompinge', 'talelathana'], 
     'oppress': ['thininika', 'thindila kongudhi', 'hepeka'], 'oppression': ['othina', 'ehepeko', 'ethindilo kongudhi'],
     'opthalmic surgeon': ['ondohotola yomeho'], 'or': ['nenge'], 'orally': ['pakana'],
     'orange': ['elemuna', 'enyangwa', 'epeke'], 'order': ['lombwela', 'elombwelo', 'mbestela', 'ombestelinga'],
     'in order': ['opo'], 'ordinary': ['sha nathangwa', '-owala'], 'organ': ['okahumba', 'okafilita', 'oshilyo'],
     'organisation': ['ehangano', 'elongekidho'], 'organise': ['longekidha'], 'organism': ['okanamwenyo'],
     'oribi': ['tungu'], 'origin': ['onakuziwa', 'onzililo'], 'orphan': ['othigwa'], 'oryx': ['osino'],
     'ostrich': ['ompo', 'okampo'], 'other': ['kwao', 'lwe', 'kwawo'], 'otherwise': ['andola'],
     'otter': ['lushendje', 'luhwenge'], 'our': ['-tu'], 'outlet': ['ombululu', 'ombende', 'ostola'],
     'outside': ['pondje'], 'outspan': ['kutulula'], 'ovary': ['oshivalelo'], 'overoll': ['ekalanyana'],
     'overcome': ['pondola', 'sindi'], 'overcast': ['enzile', 'ezile', 'omuzimbi'], 'overflow': ['hunga'],
     'overhear': ['ambela'], 'overpower': ['tona', 'sinda'], 'overseas': ['kombanda yomafuta'], 'overtime': ['olutaima'],
     'overturn': ['kandoma'], 'owl': ['ehwiyu', 'ehuyu', 'ekulu'], 'owner': ['omuhona', 'mwene'], 'ownership': ['uumwene'],
     'ox': ['ondumetana', 'onkutsa', 'onani'], 'oxygen': ['oksigina', 'ofudhilwamombepo'], 'oath': ['gana', 'egano'],
     'obedient': ['vulika', '-vuliki'], 'object': ['oshiningwa', 'omuningi', 'oshinima'], 'objectionable': ['pumpa'],
     'observation': ['ekoneko', 'ekonakono'], 'obstacle': ['oshiimbi',  'omukohongo', 'einda', 'eyinda']}

p = {'painfulness': ['uuwehame'], 'painstaking': ['oshimpwiyu'], 'painter': ['omupaindi'], 'pair': ['epando'],
     'Pakistan': ['Pakistan'], 'palate': ['ondaathelokati'], 'pale': ['pemba'], 'Palestine': ['Palestina'],
     'Palestinian': ['Omupalestina'], 'palm': ['oshiyale', 'oshaale', 'iiyale', 'omulunga', 'eke'], 'palm frond': ['epokolo'],
     'palm fruit': ['ondunga'], 'palm leaf': ['olwaale', 'oombale'], 'palm tree': ['omulunga'], 'pan': ['ekango', 'oshipana'],
     'panga': ['ekatana'], 'pant': ['fudhagana'], 'pants': ['ombulukweya'], 'paper': ['ombapila'], 'parable': ['eyele'],
     'paragraph': ['okatendo'], 'parcel': ['okapakete'], 'parent': ['omuvali', 'omukuluntu'], 'parliament': ['opalemende'],
     'part': ['oshipambu ', 'oshitopolwa'], 'particular': ['-ontumba', '-ongandi'], 'pace': ['katuka', 'onkatu', 'ondapo'],
     'packet': ['oshipakete'], 'page': ['epandja', 'pandjula'], 'pail': ['etenga', 'eyemele'],
     'pain': ['ehama', 'etapato', 'uuwehame'],  'parting': ['ontaula', 'etopoko'], 'party': ['oshituthi'],
     'pass': ['tokola', 'pita po', 'enda po','pita'], 'passage': ['omukala'], 'passenger': ['omufaalelwa'],
     'Passover': ['Opaasa'], 'past tense': ['epitathimbo'], 'pasture': ['uulithilo', 'omalithilo', 'uunapelo'],
     'patch': ['ombamba', 'oshiyando', 'oshaando', 'andeka'], 'patience': ['eidhidhimiko'], 'patient': ['omuvu', '-idhidhimiki'],
     'be patient': ['idhidhimika'], 'pattern': ['epi', 'ompatolona'], 'paunch': ['epunda', 'ela'], 'pauper': ['omuthigona'],
     'pause': ['efudho', 'fudha po'], 'paw': ['olunyala', 'enyala'], 'pawpaw': ['epapaya'], 
     'pay': ['futa', 'ondjambi', 'ofuto'], 'payment': ['ofuto', 'efutoko'], 'pea': ['ofukwa'], 'peace': ['ombili'],
     'peaceful': ['nambili', '-ombili'], 'peak': ['ondungu', 'ohulo'], 'pearl': ['egwe'], 'pebble': ['okamanya'],
     'peck up': ['shomona'], 'peck': ['shomona'], 'pedal': ['ompadhi', 'epoha', 'otrapa'],
     'peel': ['yuguna', 'kunkula', 'wegula', 'iipeta'], 'peep': ['ontamena'], 'peevishness': ['oshinyenu'],
     'pelican': ['onyundu'], 'peltophorum africanum': ['omupalala'], 'pen': ['opena', 'shanga', 'nyola'], 
     'pencil': ['opena yekala'], 'penis': ['ondha'], 'pension': ['openzela'], 'people': ['aantu'], 'pepper': ['opepela'],
     'per': ['pa'], 'percentage': ['opersenda'], 'perhaps': ['pamwe', 'ngiika', 'andola', 'sikulimwe', 'mbela aniwa', 'inga'],
     'period': ['elala', 'uulethimbo', 'oshitsa'], 'periodical': ['oshifo shoshikakothimbo'], 'permission': ['epitikilo'],
     'perpendicular': ['ongalate', 'pangalate'], 'persevere': ['dhiginina'], 'perseverance': ['uudhiginini'],
     'person': ['omuntu'], 'personality': ['uuntu'], 'personification': ['emwenyeko', 'entuupeko'],
     'perspiration': ['omazigudhe', 'epupyu'], 'perspire': ['pusha'], 'pessimist': ['omumoninayi'],
     'persuade': ['tompola', 'itaalitha'], 'pest': ['okapuka'], 'pestle': ['omuhi'], 'pet': ['oshitekulwanamwenyo'],
     'petal': ['oshishaningala'], 'petrified': ['kunkwa'], 'petrol': ['opetololi'], 'pharmacy': ['oapoteka'],
     'philologist': ['omutseyi'], 'phonetics': ['elongomawi'], 'photo': ['efano'],
     'photograph': ['faneka', 'thaneka', 'ethano', 'efano'], 'photographer': ['omufaneki', 'omuthaneki'],
     'pick': ['ombike', 'tona', 'toonona', 'fona', 'toola', 'hogolola'], 'piece': ['oshintimbu', 'oshipambu', 'oshikangwa', 'oshitelele'],
     'pierce': ['ulula'], 'pig': ['oshingulu'], 'pill': ['opela'], 'pillar': ['ongudhi'], 'pillow': ['oshigwilo', 'oshikuusinga'],
     'pimple': ['ombulwa', 'oshipulu'], 'pin': ['osipela'], 'pincers': ['oshange'], 'pinch': ['nyata'], 'pink': ['ndjokahi', 'yokahi'],
     'pioneer': ['omukokoli', 'kokola', 'tota', 'tameka'], 'pipe': ['omuligu', 'omunino'], 'smoking pipe': ['ombiga yomakaya'],
     'pistol': ['ombistoli'], 'pitfall': ['ekelo'], 'pity': ['olukeno', 'ohenda'], 'place': ['ehala', 'tula', 'tenteka'],
     'pip': ['ontanga'], 'pupa': ['oshikalakala'], 'pupil': ['omulongwa', 'omwiilongi', 'omuni'], 'plague': ['okapuka'],
     'plain': ['olushandja', 'ekango', 'oshana'], 'plait': ['panda', 'epando'], 'plan': ['ompangela', 'oplana'],
     'plane': ['heula', 'oshiheule', 'ondhila'], 'planet': ['opulanete'], 'plank': ['oshipilangi'], 
     'plant': ['tsika', 'kuna', 'oshimeno'], 'plaster': ['kolonga', 'omunoko', 'opleistela'], 'plasterer': ['omukolongi'],
     'plastering': ['ekolongo'], 'plastic': ['oshifwagalala', 'oshifaganyana'], 'plate': ['etiti', 'oshiyaha', 'okayaha'],
     'play': ['dhana', 'oshinyandwa'], 'player': ['omudhani'], 'please': ['alikana'], 'pleasure': ['enyanyu'],
     'plentiful': ['pumbulukwa'], 'plenty': ['-ndji'], 'pliers': ['oshange', 'onkwato'], 'plodding': ['kambadhali'],
     'plosive': ['oshikwelengi shomutopo'], 'plot': ['ofoola', 'ehala'], 'plough': ['pulula', 'oshipululo'],
     'pluck': ['thula'], 'plum': ['ombyu'], 'plumber': ['omupangeliminino'], 'plumber-line': ['ondjelekingalate'], 
     'plume': ['olundelelwenya'], 'plural': ['olupe luuwindji'], 'plus': ['na', 'pwa gwedhwa'], 
     'plus sign': ['endhindhilikotulokumwe'], 'pneumonia': ['oshitsa', 'oshihoya'], 'pocket': ['ondjepela', 'ondjato'],
     'pod': ['eyakashala', 'ekunde'], 'poet': ['omutoti gwiitewo'], 'poetry': ['uukwatewo'], 'point': ['ulika', 'oshitsa'],
     'poison': ['uuzigo'], 'poisoning': ['ezigopaleko'], 'poisonous': ['shi na uuzigo'], 'Poland': ['Poland'], 
     'pole': ['edhigwati', 'oshiti', 'opaala'], 'police': ['omiya dhashinana', 'omupolisi', 'opolisi'],
     'police station': ['opolisi', 'osasiyona yopolisi'], 'polish': ['mboona', 'kusha', 'pusha'], 'polite': ['pamikalo'], 'politics': ['oopolotika'],
     'political': ['papolotika', 'opolotika'], 'politician': ['omunapolotika'], 'pollard': ['ombulu'],
     'pollution': ['enyateko'], 'pool': ['ondombe', 'olutha', 'okatha'], 'poor': ['ohepele', '-nkundi'], 'pope': ['omupapa'],
     'population': ['oshigwana'], 'porch': ['oshiwalanda'], 'porcupine': ['eningu', 'shiningu'], 
     'porridge': ['epoolisa', 'oshimbombo', 'oshithima'], 'Portugal': ['Oputu'], 'Portuguese': ['Omuputu', 'Kandjala'],
     'position': ['ehala'], 'possess': ['likola'], 'possession': ['eliko', 'emona'], 'possessions': ['iiniwe'],
     'possessive': ['oshityamwene'], 'possible': ['vulika', 'shiwa'], 'cattle post': ['ohambo'], 
     'poster': ['epakolwa', 'epulakata'], 'post office': ['opoosa', 'ombelewa yopoosa'], 'postpone': ['tsilika', 'kaleka'],
     'pot': ['ombiga', 'okayuli'], 'potato': ['okatoofola', 'oshihakautu'], 'potion': ['oshigegeti'],'potsplinter': ['okakangwa'],
     'potter': ['omuhongi gwiiyuma'], 'pound': ['tsu'], 'pounding block': ['oshini'], 'pour': ['tila', 'tula', 'pimpa', 'zila'],
     'poverty': ['oluhepo', 'ompumbwe', 'uuhepele'], 'powder': ['uusila'], 'power': ['oonkondo', 'olusheno'],
     'power station': ['ohaiveleka', 'osasiyona yolusheno'], 'powerful': ['-na oonkondo'], 'powerlessness': ['uukeenankondo'],
     'praise': ['tanga', 'simaneka', 'pandula', 'hambelela', 'tumbaleka'], 'praising': ['ehambelelo', 'etumbaleko'],
     'pray': ['galikana'], 'prayer': ['egalikano'], 'praying mantis': ['namukokolambiga'], 'preach': ['uvitha'], 'preacher': ['omuuvithi'],
     'preaching': ['euvitho'], 'precipice': ['ekulukila'], 'predicate': ['oshitomoni'], 'predicative': ['pashitomoni'],
     'predict': ['hunganeka'], 'prediction': ['ehunganeko'], 'prefix': ['oshitetekeli'], 'pregnancy': ['uusimba'], 
     'pregnant': ['omusimba'], 'premier': ['omuprima', '-pombanda'], 'preparation': ['elongekidho'], 'prepare': ['longekidha'],
     'presence': ['uulipo', 'ekalepo', 'ekalopo'], 'present': ['omagano', '-lipo'], 'present tense': ['ethimbo lyongashingeyi'],
     'president': ['omupresidende'], 'press': ['kama', 'thinda'], 'pressure': ['ethindakano'], 'prevent': ['imba', 'keelela', 'kandeka'],
     'price': ['ondando'], 'pride': ['uuntsa', 'einenepeko'], 'priest': ['omusaseri', 'omuyambi', 'omupristeli'], 
     'primary school': ['oprimaskola'], 'prime minister': ['omuprima ', 'oministeli yotango'], 'print': ['nyanyangidha'],
     'printer': ['omunyanyangidhi', 'oshinyanyangidhi'], 'priority': ['oshinakugwanithwatango'], 'prison': ['ondholongo'],
     'prison cell': ['okandjugondjedhililo'], 'prisoner': ['onkwatwa', 'omunandholongo'], 'private': ['paumwene', 'ponto'], 
     'privilege': ['ompitolago', 'uuthembalago'], 'problem': ['uudhigu', 'omukundu', 'oshidhiladhilwa'], 
     'problematic': ['-pyakadhi'], 'proceed': ['tauka'], 'process': ['omuyo'], 'professor': ['omuprofesa'], 'profit': ['ohehela', 'ovenisa'],
     'programme': ['elandulathano', 'oprograma'], 'progress': ['ehumokomeho', 'eyokomeho'], 'prohibit': ['indika'],
     'prohibition': ['eindiko'], 'project': ['oproyeka'], 'projector': ['oprojeka'], 'promise': ['uvaneka', 'euvaneko'],
     'promote': ['yela'], 'prompt': ['tsitsimika', 'ulumika'], 'pronoun': ['oshityapeha'], 'propaganda': ['opropahanda'], 
     'property': ['emona ', 'eliko'], 'prophesy': ['hunganeka', 'ehunganeko'], 'prophet': ['omuhunganeki', 'omuprofeti'],
     'proposal': ['ethaneko'], 'proposer': ['omweetipo'], 'prostitute': ['ombwanda'], 'prostitution': ['uumbwanda'], 'protect': ['gamena'],
     'protection': ['egameno'], 'protector': ['omugameni'], 'protein': ['oproteine', 'oshitungilutu'], 'protrude': ['anduka', 'tsinuka'],
     'proverb': ['eyeletumbulo'], 'province': ['oshikandjo'], 'provisions': ['onguta'], 'prune': ['ombeke'], 'public': ['oshigwana'],
     'Public Service Commission': ['Okomisi ylilonga yEpangelo'], 'published': ['holoka', 'nyanyangidhwa'], 'puff adder': ['epili'],
     'pugnacious': ['ngenda', 'genda'], 'pull': ['nana', 'hila', 'hmonona'], 'pulse': ['pupa', 'omupupo'], 'pulverise': ['ndanda'], 
     'pumpkin': ['oshihenda', 'etanga', 'enyangwa'], 'purify': ['yogola', 'yeleka', 'yelitha'], 'purple': ['mbulautiligane'],
     'purpose': ['etompelo', 'elalakano'], 'purposely': ['owina'], 'pus': ['ontsika'], 'push': ['undula'], 'put away': ['pungula'],
     'putty': ['opati', 'onka', 'eka'], 'python': ['ombome'], 'python vine': ['enongo']}

# print(len(d))
# b_words = [i.strip() for i in a]
# for word in b_words:
#      if word.isupper():
#           print(word)

# Check for Oshindonga words startig with caps
# input_var = d
# for word in input_var:
#      for osh_word in input_var[word]:
#           if osh_word[0].isupper():
#                print(osh_word)
# print("Done checking!")

# Check for English words startig with caps
# input_var = d
# for word in input_var:
#      if word[0].isupper():
#           print(word)
# print("Done checking!")

words = [i for i in d]
for i in words:
     if words.count(i) > 1:
          print(i)
# print(words)