test_a = {'abate': ['iota'], 'abattoir': ['okatomeno'], 'abbreviation': ['efupipiko'], 'abdomen': ['omumpanya'],
          'lower abdomen': ['oshinena'], 'abduct': ['mbemba'], 'abduction': ['embembopo'], 'ability': ['evulo'],
          'accidentally': ['ohaluka', 'pashaadhilila'], 'accomodation': ['ekalwahala'],
          'accompany': ['enda', 'thindikila'], 'according to': ['pa'], 'according to nature': ['paunshitwe'],
          'accordion': ['enambati'], 'accountability': ['eyalulo', 'uupulwankombo']}

a = {'abate': ['iota'], 'abattoir': ['okatomeno'], 'abbreviation': ['efupipiko'], 'abdomen': ['omumpanya'],
     'lower abdomen': ['oshinena'], 'abduct': ['mbemba'], 'abduction': ['embembopo'], 'ability': ['evulo'],
     'able': ['pondola'], 'nose about': ['petapeta'], 'search about': ['thimbilathimbila'], 'above': ['kombanda'],
     'abscess': ['oshitumbuka'], 'absence': ['uukeepo'], 'absent': ['ke po'], 'absorb': ['nina'], 'abstain': ['idhilika'],
     'abundance': ['eloolo', 'nuwambwa'], 'abundant': ['ha', 'hi'], 'academy': ['oakademi'], 'accelerate': ['ulumika'],
     'accent': ['oaksende'], 'accidentally': ['ohaluka', 'pashaadhilila'], 'accomodation': ['ekalwahala'],
     'accompany': ['enda', 'thindikila'], 'according to': ['pa'], 'according to nature': ['paunshitwe'],
     'accordion': ['enambati'], 'accountability': ['eyalulo', 'uupulwankombo'],
     'accurately': ['lela', 'naanaa'], 'accusation': ['elundilo'], 'accuse': ['lundila'], 'accused': ['omutamanekwa'],
     'accuser': ['omulundili', 'omutamaneki'], 'accustomed': ['igilila'], 'acrophobia': ['uugelele'],
     'actor': ['omunyandi'], 'adansonia digitata': ['omukwa'], 'adapt': ['iyikitha', 'iyigililitha', 'iyeleka'],
     'add': ['hoha', 'gwedha'], 'adding': ['egwedhelo'], 'addition': ['etulokumwe'], 'additional': ['gwedhwa po'],
     'addressee': ['omutuminwa'], 'adenoid': ['omwenge'], 'adhere': ['kakatela'], 'adjective': ['oshityalupe'],
     'adjourn': ['zimbuka'], 'adjournment': ['ezimbuko'], 'adult': ['omukuluntu'], 'adulterer': ['omuhondeli'],
     'adultery': ['oluhondelo'], 'practise adultery': ['hondela'], 'adulteress': ['omuhondeli'], 'adversity': ['omupya'],
     'advertisement': ['etseyitho', 'etseyithilo'], 'advise': ['tsa omayele', 'gandja omayele'], 'advice': ['omayele'],
     'aeroplane': ['odhila', 'ondhila'], 'aesthetic': ['uuwopali'], 'affiliate': ['hemukila', 'mumwe'],
     'affiliation': ['ehemukilomumwe'], 'Afrikaans': ['Oshimbulu'], 'after': ['konima', 'opo ihe', 'opo nduno'],
     'afternoon': ['komatango'], 'again': ['ishewe', 'natango'], 'against': ['pooha'], 'age': ['uukokele'],
     'agenda': ['oagenda', 'elandulathano'], 'agitate': ['tsa omaminimini'], 'agree': ['pitika', 'zimina', 'uvanena', 'uvathana'],
     'agreement': ['euvathano', 'euvaneno'], 'agriculture': ['uunamapya'], 'agricultural': ['kwafaalama'],
     'agronomy': ['uunongononimapya'], 'agronomist': ['omunongononimapya'], 'ahead': ['komeho'],
     'aim': ['odha', 'lalakanena', 'oshilalakanenwa'], 'air': ['ombepo', 'ewangandjo'], 'alarm': ['onkugo'],
     'albino': ['thithi'], 'albizia anihelmintica': ['omupopo'], 'album': ['oalbuma', 'embo lyomathano'],
     'alcohol': ['alkoholi'], 'alcoholic': ['iikolitha', 'onkolwe'], 'algae': ['onguwi'], 'alkali': ['oalikali', 'oshimongwa'],
     'alkaline': ['paalikali', 'pashimongwa'], 'all': ['he'], 'alliance': ['ondjuvanene', 'ehangano'], 'allurement': ['oshinge'],
     'aloe': ['endombo'], 'alone': ['ke', 'mwene'], 'alphabet': ['aambeendee'],
     'alphabetically': ['paambeendee', 'pahaanibeendee'], 'also': ['wo', 'ootu'],
     'alternative': ['epingeno'], 'although': ['nando', 'nonando'], 'aluminium': ['oaluminiuma'], 'always': ['aluhe'],
     'amateur boxer': ['omumbokisilinyanyu'], 'amazing': ['kuinithi'], 'ambassador': ['omukalelipo'], 'ambush': ['elangelo'],
     'ammonia': ['amoniaka'], 'ammonium sulphate': ['amoniumsulfate'], 'ammunition': ['oshuumbithi', 'oshiyumbithi'],
     'amnesty': ['esohenda lyoonkwatwa'], 'among': ['mokati'], 'amongst': ['mokati'], 'amount': ['omwaalu', 'omiyalu'],
     'amulet': ['oshigegeti'], 'analyse': ['vongokonona'], 'analysis': ['evongokonono'], 'anatomy': ['oanatomi'],
     'anatree': ['omuyele'], 'ancestor': ['epipi', 'omukulugonale', 'omukwampungu'], 'ancestral spirits': ['aathithi'],
     'anchor': ['hangela', 'ohangela'], 'ancient': ['uukulupe womutoko'], 'and': ['e', 'na'],
     'angel': ['omuyengeli'], 'angle': ['okolonela', 'ekuvu', 'onkuvu'], 'wild': ['oshiyamakuti'], 'ankle': ['onyugu'],
     'annex': ['tenda ko'], 'annexation': ['etendoko'], 'announce': ['imeleta', 'ilombola', 'tseitha'],
     'annoy': ['hinda', 'yemateka'], 'annual function': ['okatuthihulitho'], 'anoint': ['gwayeka'],
     'another': ['kwawo', 'lwe'], 'answer': ['yamukula', 'eyamukulo'], 'ant': ['ondhindhi', 'eteta'],
     'ant-bear': ['eyamayama'], 'ant-eater': ['ongaka'], 'ant-hill': ['oshaanda', 'oshiyanda'], 'anthrax': ['ombulwa'],
     'antibiotic': ['oshidhipagimbuto', 'omuti'], 'anticipate': ['tegamena'], 'anticipation': ['etegameno'],
     'anus': ['onufu'], 'anxiety': ['omahwilili', 'uuhwenge'], 'anxiously': ['nyulukuta'], 'anvil': ['oshikalo'],
     'any': ['kehe'], 'anyone': ['kehe ngoka'], 'anything': ['kehe shimwe'], 'anyway': ['ando'], 'aorta': ['aorta'],
     'ape': ['ondjima'], 'apoplexy': ['ombanda', 'esilombanda'], 'apparatus': ['oaparate', 'oshilongitho'],
     'apparition': ['oshihehelela', 'oshikwafa'], 'appeal': ['tsikilitha ompangu', 'etsikilompangu', 'indila', 'eindilo'],
     'appear': ['holoka', 'mbanduka', 'uluka'], 'appearance': ['ondjelo', 'eholoko', 'ombelo'], 'appendicitis': ['okiimili'],
     'appendix': ['okiimili', 'oshigwedhelwako'], 'appetite': ['omwamwa'], 'applaud': ['hakela', 'pandula'],
     'applause': ['ehakelo', 'ekugililo'], 'apple': ['oshiapula', 'oshiyapula'], 'application': ['eindilo'],
     'apply': ['longitha', 'ninga eindilo'], 'appoint': ['lenga', 'ulika'], 'appointment': ['oshilage', 'euliko'],
     'approach': ['hedha', 'engena', 'omukalo'], 'approximately': ['konyala', 'lunga'], 'April': ['Apilili'],
     'apron': ['oshitetahema'], 'aquarium': ['oakwariuma'], 'Arab': ['Omwaarabia', 'Aayarabia'], 'arbitrate': ['potokonona'],
     'arbitrator': ['omupongololi', 'omupotokononi'], 'architect': ['omuthanekingulu', 'omusindingulu', 'omusindigumbo'],
     'argue': ['tamanana'], 'argument': ['oontamanana'], 'arm': ['okwaako', 'okwooko', 'okooko'], 'armpit': ['onkwapa'],
     'armament': ['ehomato'], 'armed': ['homata'], 'around': ['omudhingoloko'], 'arrange': ['pongolola', 'longekidha'],
     'arrangement': ['elongekidho', 'eilongekidho'], 'arrest': ['kwata', 'tula miipandeko', 'manga po'],
     'arrive': ['thika'], 'arrival': ['eyo', 'ethiko'], 'arrogance': ['elundu'], 'arrow': ['oshikuti', 'omuvi'],
     'artery': ['onkandjambinzi'], 'article': ['oshinima', 'okatendo'], 'artisan': ['engomba'], 'artist': ['omunongo', 'onkulungu'],
     'art': ['uunkulungu', 'uunongo', 'uungongi'], 'as far as': ['sigo'], 'as soon as': ['hela tuu'],
     'asbestos': ['oasbesa'], 'Asia': ['Asia'], 'Asian': ['Omwaasia', 'Aayasia'], 'ash': ['omutoko'], 'aside': ['kombinga'],
     'assegai': ['egonga'], 'assembly': ['omutumba'], 'assignment': ['oshitopolwa shiilonga', 'oshitopolwailonga'],
     'assist': ['kwatha', 'ambidhidha'], 'assistant': ['omuyakuli', 'omupeha'], 'assistance': ['ekwatho', 'eambidhidho'],
     'association': ['ehangano'], 'asthma': ['oasma'], 'astonishment': ['onkumwe'], 'astonish': ['kumitha'],
     'astounding': ['kumithi'], 'at': ['p-', 'k-'], 'atom': ['oatoma'], 'atomic': ['paatoma'], 'Atlantic': ['Atlantika'],
     'atlas': ['oatilasa', 'oatlasa'], 'atmosphere': ['ombepo ', 'ongandjombepo', 'ewangando'], 'attach': ['kopeka'],
     'attack': ['umpila', 'ponokela', 'homona', 'tondokela'], 'attacker': ['omuhomoni', 'omumatukili', 'omutondokeli', 'omuponokeli'],
     'attempt': ['kambadhala', 'ekambadhalo', 'onkambadhala'], 'attend': ['sikola', 'ndhindhilika', 'hita'],
     'attention': ['eimweneneno', 'ndhindhilika'], 'attentiveness': ['oonkoto'], 'attitude': ['omikalo', 'oohedhi'],
     'attract': ['fuula', 'fuuka'], 'attraction': ['ohokwe'], 'attractive': ['hokitha'], 'auction': ['fanditha', 'ofanditha', 'elanditho'],
     'auctioneer': ['omulandithi'], 'August': ['Auguste'], 'aunt': ['kuku', 'yinagona'], 'my aunt': ['memegona'],
     'Australia': ['Australia'], 'Australian': ['Omwaaustralia', 'Aayaustralia'], 'Austria': ['Austria'],
     'Austrian': ['Omwaaustria', 'Aayaustria'], 'authority': ['oompango', 'oonkondo'], 'autumn': ['oshikufuthinge'],
     'available': ['shili po'], 'avert': ['ingila', 'yanda'], 'avocado': ['oshiavokado'], 'avoid': ['iyageka', 'yanda', 'keelela'],
     'awake': ['penduka', 'papudhuka'], 'awakening': ['ependuko'], 'aware': ['shi', 'nongela'], 'awareness': ['enongelo'],
     'away': ['yi', 'ya'], 'awl': ['oniho'], 'axe': ['ekuya'], 'axle': ['oakiseli', 'oakisa'], 'axis': ['oakiseli']}

b = {'baboon': ['ondjima', 'lunkima'], 'baby': ['okahanona', 'omuholike'], 'back': ['omugongo', 'ombunda'],
     'backbone': ['omugongo', 'esipa lyombunda'], 'backbite': ['hokola'], 'backbiter': ['omuhokoli'],
     'background': ['osindo'], 'backside': ['etako', 'konima'], 'bacteria': ['ombakiteli'], 'bad': ['ha'],
     'badge': ['oshihako', 'ombandi'], 'badly': ['nayi'], 'badness': ['uuwinayi'], 'bag': ['oshako', 'ondjato'],
     'bail': ['eimbeelomo', 'omboloha'], 'bake': ['mbaka', 'yotha'], 'bakery': ['ombeka'], 'baking-powder': ['efulika'],
     'balance': ['ontengelelo', 'oshihupe'], 'bald': ['ongwala'], 'bale': ['oshihampi'], 'ball': ['etanga'],
     'balloon': ['embalona'], 'weather': ['onkalo yombembo'], 'ballot': ['ombapila yehogololo'], 'ban': ['konda'],
     'banana': ['embanana', 'omumbanana'], 'bandolier': ['ekwamo'], 'bang': ['ngwanda'], 'bangle': ['okagondo'],
     'bank': ['pungula', 'ombaanga'], 'bankrupt': ['mbangolota'], 'bankruptcy': ['embangoloto'],
     'baobab': ['omukwa'], 'baptise': ['shasha'], 'baptiser': ['omushashi'], 'bar': ['ombaa', 'enwino'],
     'barbed hook': ['ongona'], 'barber': ['omukululi'], 'barbershop': ['okakululilo'], 'barefoot': ['ohuuna'],
     'bark': ['eyula', 'gwedha'], 'barrel': ['oluungu'], 'barter': ['pingakanitha'], 'basic': ['ekota'],
     'basin': ['oshiyaha', 'okatemba'], 'basis': ['oshimbu'], 'basket': ['ontungwa'], 'grain basket': ['eshisha', 'oshigadhi'],
     'bass': ['omugono', 'ombaatha'], 'bat': ['elimalima'], 'bathroom': ['okaiyogelo'], 'battery': ['emanya', 'opatrii'],
     'battle': ['olugodhi'], 'beach': ['omunkulofuta'], 'beak': ['omulungu', 'epakululu'], 'beam': ['omutenge', 'oonte'],
     'bean': ['ekunde'], 'bean sauce': ['oshigali'], 'bear': ['vala', 'humbata', 'ima', 'emwanka'], 'beard': ['oombenzi)'],
     'bearer': ['omuhumbati'], 'beast': ['ongombe'], 'beat': ['thekula', 'thepagula', 'dhenga'], 'beautiful': ['opala', 'wanawa'],
     'beautify': ['opaleka'], 'beauty': ['uuwopali', 'uuyogoki', 'uuwanawa'], 'because': ['oshoka', 'shaashi', 'molwashoka'],
     'beckon': ['lapa'], 'bed': ['ontala', 'ombete'], 'bedding': ['iinguma'], 'bee': ['onyushi'], 'beer': ['ombiila', 'omalovu'],
     'beestings': ['epuya'], 'beeswax': ['ezi'], 'beetle': ['ondjimbi', 'okambaambala'], 'beetroot': ['eroibiyeta'],
     'before': ['manga', 'komeho'], 'beg': ['hehela', 'indila', 'galikana'], 'begging': ['egalikano', 'eindilo', 'ehehelo'],
     'behave': ['ihumbata'], 'behaviour': ['eihumbato', 'omaihumbato', 'omikalo'], 'begin': ['tameka'], 'beginner': ['omutameki'],
     'beginning': ['etameko'], 'belief': ['eitaalo'], 'believe': ['itaala'], 'believer': ['omwiitaali'], 'belong': ['gama'],
     'below': ['pevi'], 'bell': ['ongendjo'], 'bellow': ['ula'], 'belly': ['epunda'], 'beloved': ['omuholike'],
     'belt': ['omuya', 'epaya'], 'bench': ['oshipundi'], 'bend': ['petama', 'gonya'], 'bent': ['egoli'], 'berry': ['okayimati'],
     'besides': ['kakele'], 'bestman': ['oshinkumbi'], 'betray': ['gwaaleka', 'kengelela', 'nwa po'], 'betrayer': ['omugwaaleki'],
     'better': ['hwepo'], 'beware': ['angla', 'kotoka'], 'bewitch': ['tikila', 'loga'], 'beyond': ['pombanda'],
     'Bible': ['Ombiibeli'], 'bicycle': ['okathanguthangu', 'okambasikela'], 'big': ['-nene'], 'bigamy': ['ombanda'],
     'bill': ['oongunga', 'iifuta'], 'billion': ['obiliyona'], 'billow': ['tuwalala'], 'biltong': ['oludhingu'],
     'bird': ['okadhila', 'ondhila'], 'bioscope': ['okino'], 'birth': ['vala', 'pulumutha'], 'birthday': ['esiku lyevalo'],
     'bisect': ['tateka'], 'bishop': ['omumbisofi'], 'bit': ['sha', 'okanima'], 'bite': ['lumata'], 'bitter': ['lula'],
     'bitterness': ['uululu'], 'black': ['luudhe'], 'blackboard': ['oshipelende'], 'blacken': ['luudhika', 'nyateka'],
     'blackmail': ['thina'], 'Blacks': ['Aaluudhe'], 'blacksmith': ['omuhambudhi', 'omuhambuli'], 'blade': ['efo lyomwele'],
     'bladder': ['okampunda komasita'], 'blanket': ['ekumbatha'], 'blast': ['topa'], 'blaze': ['omulilo'], 'bleat': ['lila'],
     'bleed': ['hiha'], 'bless': ['yambeka'], 'blesser': ['omuyambeki'], 'blessing': ['ehaleloyambeko', 'eyambeko'],
     'blind': ['toga', 'tsika', 'omuposi'], 'blindness': ['uuposi'], 'blister': ['epuya', 'oompekehe'], 'block': ['keelela'],
     'blood': ['ombinzi'], 'blossom': ['onsheno', 'sheneka'], 'blouse': ['ohema yoshikiintu'], 'blow': ['pepa', 'fudhila', 'fugula', 'pemba'],
     'blowlamp': ['olamba yokufikilitha'], 'blue': ['mbulau'], 'blunt': ['simpa'], 'board': ['menekela', 'embolota'],
     'boast': ['inoma'], 'boat': ['ombautu'], 'body': ['olutu'], 'boil': ['fuluka', 'ethina'], 'bomb': ['mboma', 'omboma'],
     'bombardment': ['embomo'], 'bomber': ['omumboni'], 'bone': ['esipa'], 'bonus': ['ombonasa'], 'book': ['embo', 'oshifo', 'okambo'],
     'boomslang': ['iifoyamusati'], 'boot': ['ombuta', 'ombutsa', 'thanga'], 'booth': ['okangulu'], 'border': ['ongamba'],
     'borehole': ['omboola'], 'borrow': ['hehela'], 'botany': ['obotani', 'ontseyoimeno'], 'bottle': ['ekende'],
     'bottletop': ['oshisiikilitho', 'okasiikilitho'], 'bottom': ['oshitako', 'kohi'], 'boulder': ['ethindimanya'],
     'boundary': ['ontaululi'], 'bow': ['uutati', 'uuta wanangongo'], 'bowtie': ['okakunde'], 'box': ['oshiketha', 'okapakete', 'oongonyo'],
     'boxer': ['omudhengingonyo'], 'boy': ['okamati', 'omumati'], 'boyhood': ['uumati'], 'brain': ['uuluyi'],
     'brake': ['ombiliki', 'mbilika'], 'bran': ['uuhutu'], 'branch': ['oshitayi'], 'brandy': ['ombike', 'ombelendi'],
     'brave': ['pendapala'], 'bravery': ['onyati', 'uufule'], 'bray': ['koma'], 'bread': ['omboloto', 'oshikwiila'],
     'breadth': ['omutamo'], 'break': ['pambula', 'tatula', 'teya', 'tokola', 'topola', 'kumuna', 'ngumuna', 'okafudho'],
     'breast': ['ondete', 'egundji'], 'breath': ['omufudho'], 'breathe': ['fudha'], 'breed': ['kola', 'muna'],
     'brew': ['hanga', 'dhunga'], 'brewery': ['ombuulaye'], 'bribe': ['ombumbo'], 'brick': ['ondhopi'], 'bride': ['omufuko'],
     'bridegroom': ['omufuko', 'ombushiki'], 'bridesmaid': ['oshinkumbi'], 'bridge': ['ontopa', 'kwatakanitha'], 'bridle': ['oshitomo'],
     'briefcase': ['ompunda', 'okataasi'], 'bright': ['yelele', 'adhima'], 'gnu': ['ompugulu'], 'bring': ['eta'],
     'broadcast': ['tuma mombepo'], 'brochure': ['obroshure'], 'broom': ['oluhwati', 'oshikombe'],
     'brother': ['omumwayina', 'omumwayinamati', 'mbuluta'], 'brown': ['ndjimbi', 'mbambi'], 'bubble': ['ombwimbwi', 'gwagwata'],
     'bubonic plague': ['uuvu wombuku'], 'bucket': ['eyemele', 'etenga'], 'buckle': ['ompate'], 'bud': ['shena', 'osheno'],
     'budget': ['etengenekothaneko'], 'buffalo': ['onyati'], 'build': ['tunga'], 'builder': ['omutungi'],
     'building': ['etungo', 'ongulu', 'egumbo'], 'bulb': ['ombimbo', 'etindi', 'okambiyena', 'okalamba'], 'edible': ['ongehu', 'oshikuliwa'],
     'bulge': ['umbuka'], 'bull': ['ontsenzi'], 'bulletin': ['ombuletine'], 'bump': ['nguma', 'puma'], 'bunch': ['ehila'],
     'bundle': ['oshihampi', 'oshipandi', 'okapandi', 'okahampi'], 'burn': ['fika', 'lunguna', 'pya'],
     'burn-marks': ['oondjota'], 'burrow': ['omvugo'], 'bursary': ['iimaliwa yokwiilongitha'], 'burst': ['topa', 'tenda'],
     'bury': ['fumbika', 'fumvika'], 'bus': ['ekambamba', 'ombesa'], 'bush': ['oshiheke', 'oshihwa'], 'Bushman': ['Omukwankala'],
     'business': ['uunangeshefa', 'ongeshefa'], 'businessman': ['omunangeshefa'], 'busy': ['sikuuka', 'ipyakidhila'], 'but': ['ihe', 'ndele'],
     'butcher': ['omutseli'], 'butchery': ['oshilahite'], 'butter': ['omagadhi', 'ombuta'], 'butterfly': ['embiimbili', 'okambiimbili'],
     'buttock': ['etako'], 'button': ['ombandi', 'pata'], 'buy': ['landa'], 'buyer': ['omulandi'], 'by': ['ku'],
     'bypass ': ['kunkula', 'kunduluka', 'dhingoloka']}

c = {'cabinet': ['oskopa', 'osikopa', 'okabinete'], 'cackle': ['kokola', 'tetena'], 'cake': ['oshikuki'],
     'calabash': ['ombago', 'oshikola', 'ompamba'], 'calculate': ['yalula'], 'calculation': ['eyalulo'], 'calender': ['okalindela'],
     'calf': ['ontana', 'okatana'], 'call': ['ithana', 'igidha'], 'calm': ['ngungila', 'mweneka'], 'camel': ['ongamelo'],
     'camel-thorn': ['omuthiya'], 'camera': ['efano  lyokuthaneka'], 'camp': ['yunga', 'ontanda', 'okamba'],
     'can': ['wapa', 'vula'], 'Canada': ['Kanada'], 'Canadian': ['Omukanada'], 'canal': ['omukanka'], 'Canary': ['namukuku'],
     'cancel': ['kansela'], 'cancellation': ['ekanselo'], 'cancer': ['okanker', 'ondhiya'], 'cannot': ['itashi vulika'],
     'cannikin': ['okakana'], 'cannon': ['ekanona'], 'cap': ['okagala'], 'capital': ['iimaliwa'], 'capitalism': ['uukapitali'],
     'capitalist': ['omukapitali'], 'capriciousness': ['omanganga', 'omanyami'], 'captain': ['kapitiya'],
     'captivity': ['uupika', 'uukwatwa', 'uupongekwa'], 'capture': ['kwata'], 'captured': ['sha kwatwa'], 'car': ['oshihauto'],
     'carbon dioxide': ['onkwakala'], 'card': ['okakalata'], 'cardboard': ['oshipakete'], 'care': ['hunga', 'sa oshimpwiyu'],
     'careful': ['oshimpwiyu'], 'carefully': ['nekotoko', 'noshimpwiyu'], 'caring': ['esiloshimpwiyu'],
     'carpenter': ['omuhongi gwiipilangi', 'kapindela'], 'carpet': ['ombanza'], 'carrier': ['omuhumbati'], 'carrot': ['okanakamundesha'],
     'carry': ['humbata', 'leka', 'tumba', 'kwiinina'], 'carry out': ['gwanitha'], 'carrying': ['ehumbato'], 'carrying skin': ['ondhikwa'],
     'cart': ['tuta'], 'caruncle': ['okakunde'], 'carve out': ['nega'], 'carving': ['etakelo'], 'case': ['oshiketha', 'iikoya', 'ompangu'], 
     'cash': ['okeshe', 'oshimaliwa shopeke'], 'caster-oil': ['okastololi'], 'caster-oil plant': ['olumono'],
     'castle': ['epopilongulu'], 'cat': ['kalenga', 'okambishi', 'ngato'], 'catapult': ['okatayingil'], 'catastrophies': ['iihnna'],
     'catch': ['kwata', 'fegula', 'akula', 'luga', 'shongola', 'yula'], 'catcher': ['omukwati'], 'catching': ['ekwato'],
     'catholic': ['okatolika'], 'cattle': ['oongombe'], 'cauliflower': ['ombogangala'], 'cause': ['ningitha'], 'cave in': ['kumuka', 'ngumuka'],
     'cavity': ['ekololo'], 'ceiling': ['ontala'], 'cement': ['osamende'], 'cemetery': ['eendo'], 'census': ['eyalulo lyaantu'],
     'cent': ['osenda'], 'centipede': ['embalangandja'], 'central': ['pokati', 'shopokati'], 'central committee': ['ongundumutinia'],
     'centre': ['pokati'], 'century': ['oomvula omayovi'], 'certain': ['ontumba'],
     'chaff': ['omanyami', 'olungu', 'etutu'], 'chain': ['elyenge'], 'chair': ['oshipundi'], 'chairperson': ['omunashipundi'],
     'chalk': ['ompya'], 'chameleon': ['ethimbithimbi'], 'champion': ['enyakwa'], 'chance': ['ompito', 'olweedhe'],
     'chandelier': ['oshihukikwanyeka'], 'change': ['lundulula', 'shitula'], 'change': ['elunduluko', 'elundululo'],
     'change money': ['shendja iimaliwa'], 'changeable': ['mpinyuka'], 'chapter': ['ontopolwa'], 'character': ['uukwatya'],
     'charcoal': ['ekala'], 'charge': ['nukila', 'umpila', 'ponokela', 'eumpilo', 'enukilo', 'eponoko', 'elopoto', 'etamaneko'],
     'charge': ['lopota', 'tamaneka'], 'charm': ['oshigegeti', 'omuheka'], 'chart': ['okaalita'], 'chase': ['ganda', 'tidha'],
     'chasm': ['ekulukila'], 'chat': ['popyapopya'], 'chatter': ['tyaatyaa', 'popyagula'], 'cheap': ['ombiliha'],
     'cheaper': ['ombiliha unene', 'pambiliha'], 'cheat': ['kotokela'], 'check': ['tala', 'hadha'], 'cheek': ['ompanda', 'olupanda'],
     'cheekiness': ['olundu', 'oshityani', 'omanganga'], 'cheese': ['ehini'], 'cheetah': ['etotono'], 'cheque': ['otyeke'],
     'chest': ['ontulo'], 'chew': ['taasina', 'inyangusha'], 'chewing': ['emukutulo'], 'chick': ['okayuhwena'], 'chickenpox': ['epulu'],
     'chief': ['omukwaniilwa', 'eleng'], 'chiefly': ['unene'], 'child': ['omunona'], 'childhood': ['uunona'], 'children': ['aangela', 'uunona'],
     'chili': ['ondungu'], 'chimney': ['oluungu'], 'China': ['Kina'], 'Chinese': ['Omukiina'], 'chip': ['popoka', 'oshikangwa'],
     'chips': ['ekoko'], 'chirp': ['sheketa'], 'chisel': ['omaisela'], 'chlorinated lime': ['okaalaka kokololo'], 'chlorine': ['ochiorine'],
     'choice': ['ehogololo'], 'cholera': ['kolera', 'cholera'], 'choose': ['hogolola'], 'chop': ['komangela', 'panda'], 'chord': ['elimba'],
     'chosen': ['sha hogololwa'], 'Christian': ['omukriste'], 'Christianity': ['uukriste'], 'Christmas': ['Okrismesa'], 'chunk': ['endangalati'],
     'church': ['ongeleka'], 'churn': ['hika'], 'cicada': ['enyenye'], 'cigarette': ['okasekeleta'], 'cigarette-end': ['okaictela'],
     'cilia': ['olumbatu'], 'cinema': ['okino'], 'circle': ['ongonga'], 'circumcise': ['kenka'], 'citizen': ['omukalimo'],
     'citrus': ['iisitulusa'], 'city': ['oshiando'], 'civil': ['kwashigwana'], 'civilian': ['omukwashigwana'],
     'civilisation': ['eputuko', 'uukwashigwana'], 'claim': ['pula'], 'clap': ['hakela'], 'clapping': ['ehakelomake'], 'clarity': ['uuyelele'],
     'class': ['ongundu'], 'clay': ['eloya ', 'oshiyuma', 'oshuma'], 'clean': ['yogoka', 'yela', 'opaleka', 'komba'], 'clear': ['yelele'],
     'clearing': ['ehenene'], 'cleave': ['toogonya'], 'cleft': ['ekolombongo'], 'clerk': ['okierka', 'omunambelewa'],
     'cliff': ['oshimpoko', 'etayimanya'], 'climate': ['okliima'], 'climb': ['londa', 'heluka', 'londoloka'], 'cling': ['thapila', 'kakatela'],
     'clinic': ['oklinika', 'okapangelogona'], 'clipper': ['omukululi'], 'clod': ['ekuma'], 'close': ['edhila', 'thateka'],
     'closed': ['she edhilwa'], 'cloth': ['elapi'], 'clothe': ['zala'], 'clothes': ['oonguwo', 'oonguyo'], 'clothes-basket': ['eshungu'],
     'clothing': ['oshizalomwa'], 'cloud': ['oshikogo'], 'cloudy': ['kogopala'], 'cloudiness': ['ekogopalo'], 'clout': ['enkawa', 'olupi'],
     'club': ['onkunya'], 'coagulate': ['hekela'], 'coal': ['ekala'], 'coast': ['omunkulo'], 'coat': ['elwakarn', 'ondjatha'],
     'coax': ['sisidha'], 'cobra': ['efu'], 'cock': ['ekondombolo'], 'cockiness': ['oshityani'], 'cockroach': ['epenzu', 'cpcnzi'],
     'cockscomb': ['enyaga'], 'cocky': ['lunduka', 'dhuma'], 'code': ['okoode'], 'coffee': ['okoothiwa'], 'coin': ['engwanda'],
     'coins': ['iimaliwa iikukutu'], 'cold': ['talala', 'ekunku'], 'colic': ['oshitheta'], 'collapse': ['ongotela', 'sa ombanda'],
     'collapsed': ['a sa ombanda'], 'collect': ['gongela', 'ndjagaya', 'tyaya'], 'collection': ['ongalo', 'egongelo'], 'college': ['okolidji'],
     'colon': ['enyo'], 'colony': ['okoloni'], 'colour': ['mbapeka', 'olwaala', 'ombapa'], 'coloured': ['omunalwaala', 'ombastela'],
     'column': ['ombongola', 'omukweyo'], 'comb': ['kamula', 'oshikamule', 'ompendu'], 'combination': ['ehanganitho'],
     'combine': ['hanganitha'], 'come': ['ya'], 'comedy': ['oshinyandwanyanyu'], 'comfort': ['hekeleka', 'ehekeleko'],
     'coming': ['eye'], 'command': ['lombwela', 'elombwelo'], 'commander': ['omukomandi'], 'commentator': ['omufatululi'],
     'comments': ['nega'], 'commerce': ['iipindi'], 'commercial': ['paipindi'], 'commissioner': ['komufala'], 'committee': ['okomitiye'],
     'commodities': ['iipindi', 'iilandithomwa'], 'common': ['tsa kumwe'], 'communal land': ['evi lyomuhanga'],
     'communion': ['oshililo', 'uulalelo uuyapuki'], 'communism': ['uukomonisi'], 'communist': ['omukomonisi'],
     'community hall': ['oshinyanga shaayehe'], 'community school': ['osikola yoshigwana'], 'companion': ['omuthindikili'],
     'company': ['ehangano'], 'compare': ['yelekanitha'], 'compared': ['sha yelekanithwa'], 'compete': ['thigathana'],
     'competition': ['ethigathano'], 'complain': ['yemata'], 'complaint': ['eyemato', 'enyenyeto'], 'complete': ['tsakanitha', 'mana', 'udhitha'],
     'completed': ['sha tsakana', 'sha pwa', 'shu udhithwa'], 'completely': ['thiluthilu'], 'compose': ['tota'], 'comprehension': ['etanutho'],
     'comprehension test': ['etanuthokonakono'], 'compulsory': ['tashi dhengele'], 'computer': ['okompiuta'],
     'conceahneflt': ['uuholeki', 'eholeko', 'uuholekedhi'], 'concentrate': ['itula mo', 'dhiladhila muule'], 'concentration': ['eitulomo'],
     'concept': ['oshidhumo'], 'conception': ['etanutho', 'euvoko'], 'concern': ['shi na sha'], 'concerning': ['molwa', 'kombinga'],
     'concertina': ['ongongi'], 'consciousness': ['eipangelo'], 'concrete': ['okaungulita'], 'condition': ['onkalo'], 'condone': ['dhimina'],
     'conference': ['oshigongi'], 'confess': ['hempulula'], 'confession': ['ehempululo', 'ezinuno'], 'conflict': ['eipumomumwe'],
     'confusion': ['evundakano'], 'Congo': ['Kongo'], 'Congolese': ['Omukongo'], 'congratulation': ['ehalelolago'], 'congress': ['oshiithanene'],
     'connected': ['sha kwatakanithwa'], 'connection': ['ekwatathano'], 'conquer': ['sinda'], 'conqueror': ['omusindani', 'omuwini'],
     'conscience': ['eiyuvo'], 'consent': ['epitikilo', 'ezimino'], 'conservation': ['egameno'], 'consideration': ['omaengweno'],
     'consists': ['sha thikama'], 'consolation': ['ehekeleko'], 'constipation': ['ombato'], 'constitution': ['ekotampango'],
     'construction': ['etungo'], 'consume': ['thekeka'], 'consumer': ['omulandi', 'omulongithi'],
     'contagious disease': ['olukongo', 'omukithi gwomukwawu'], 'contagiousness': ['omukwawu', 'olutapo'], 'container': ['oshikwatelwa'],
     'contain': ['shi na'], 'contamination': ['enyateko'], 'contempt': ['ondhino'], 'continent': ['okontinente'], 'continue': ['tsikila'],
     'continues': ['tashi tsikile'], 'contraception': ['oshingambeki sholuvalo'], 'contract': ['okondalaka', 'euvathano'],
     'contraction': ['eihuto'], 'contractor': ['omutungingulu'], 'contradiction': ['oombata'], 'control': ['konakona', 'kondolola'],
     'controlled': ['sha konakonwa', 'sha kondololwa'], 'conversation': ['onkundathana'], 'conversion': ['eitedhululo'], 'convert': ['itedhulula'],
     'convey': ['thikitha'], 'convulsion': ['thanganya'], 'cook': ['teleka', 'omuteleki'], 'cooked': ['pya'],
     'cooking oil': ['omagadhi gokulya'], 'cool down': ['talala', 'pola'], 'co-operation': ['elongelokumwe'], 'copper': ['ongopolo'],
     'copper anklet': ['ongondo'], 'copse': ['omuhenye'], 'copy': ['sindila', 'okopi'], 'cord': ['okaankoga'],
     'cork': ['oshisiikilitho'], 'corn': ['oshilyawala', 'omushokolo', 'iilyaalyaka','ompwe', 'oshilya'], 'corn': ['ontindo'],
     'corner': ['ompoko', 'onkotso'], 'corporation': ['ehangano'], 'corpse': ['omudhimba'], 'correct': ['pukulula', 'opaleka'],
     'corridor': ['uupandaanda'], 'corrugated iron sheet': ['oshipeleki'], 'cost': ['ondando'], 'cotton': ['oshilugu', 'ondhilewu'],
     'couch grass': ['ongwena'], 'cough': ['kolola', 'omukolo'], 'coughing': ['ekololo'], 'counting': ['eyalulo'],
     'country': ['oshilongo'], 'couple': ['haka', 'aaihokanathani'], 'courage': ['omukumo'], 'course': ['okersesa'],
     'court': ['ohofa', 'ompangu'], 'cousin': ['gwaantsezi', 'omumwaho'], 'cover': ['siikila', 'epeko'], 
     'covering': ['esiikilo'], 'covey': ['enduwa'], 'cow': ['onzinzi'], 'coward': ['omumbanda', 'omukatalume', 'ewaya'],
     'cowardice': ['uukatalume', 'uuwaya'], 'cowardly': ['gwegwembela', 'gwaala', 'lunduka'], 'crack': ['tenda', 'tyalakata', 'ehindja'],
     'cracked': ['tanduka'], 'craftsman': ['engomba'], 'cram in': ['hwela'], 'cramp': ['eyathipa'], 'crane': ['olema'],
     'crashing': ['omupaulilo'], 'crawl': ['pwedha', 'kookolola'], 'crazy': ['pwidhi'], 'creak': ['kolokota'], 'cream': ['olukawe'],
     'crease': ['gonyatala', 'egonyoto'], 'create': ['shita'], 'creation': ['eshito'], 'Creator': ['Omushiti'], 'creep': ['kookaya', 'hita'],
     'crèche': ['oshikunino', 'oshitsambe', 'uulelelo'], 'credit': ['okrediti'], 'cretin': ['eungu'],
     'crew': ['oonakulongamo'], 'cricket': ['okathangamatondo', 'okashenye', 'elindi', 'elindilindi'], 'criminal': ['omuyonaguli'],
     'cripple': ['oshilema'], 'crisis': ['oshikele'], 'criticised': ['sha tamanekwa'], 'criticism': ['etamaneko'], 'croak': ['zima'],
     'crockery': ['okatashe', 'oshitatuki', 'iikwakutatuka'], 'crocodile': ['ongandu'], 'Crombec': ['ndulumakunde'], 
     'crook': ['ontseyele', 'ompote', 'omufuthi', 'otyaka'], 'crooked': ['penga'], 'crookedness': ['iitsatsa'], 'crop': ['eteyo'],
     'cross': ['tokola', 'taaguluka', 'shigakana', 'geela', 'yala'], 'crossbar': ['ontanu', 'ohonga', 'olukambo'], 
     'crossed': ['sha shigakana', 'sha taskana', 'sha shindjakana'], 'crow': ['iga', 'ekola', 'edhilakola'],
     'crowd': ['ngundumana'], 'crown': ['oshishani'], 'crucifixion': ['eyalelo'], 'cruel': ['kolokoshi'], 'cruelty': ['uukolokoshi'],
     'crumb': ['ondjagumuke'], 'crush': ['nyanyula', 'thenga', 'takula'], 'crusher': ['oshikokota'], 'crust': ['ekoko'], 'cry': ['lila'],
     'crystal': ['ewe'], 'Cuba': ['Kuba'], 'Cuban': ['Omukuba'], 'cucumber': ['okatanga'], 'cultivate': ['gondjoka'],
     'cultural': ['paikwashigwana'], 'culture': ['iikwashigwana'], 'cumulonimbus': ['ngungumikogo', 'iityalakatakogo'], 'cumulus': ['iikumulusa'],
     'cunning': ['ondondolo'], 'cup': ['okakopi'], 'cupboard': ['osikopa'], 'curd': ['omaoteka', 'omooteka', 'omoosi', 'oshooteka'],
     'cure': ['aludha', 'panga'], 'curiosity': ['uutaledhi', 'uutalambambi'], 'curl': ['ondhinga'], 'currency': ['iimaliwa'],
     'current': ['pethimbo mpoka'], 'curse': ['thinga', 'ethingo'], 'curtains': ['omalapi gopomakende'],
     'cushion': ['oshigwilo', 'oshikuusinga'], 'customer': ['okastoma'], 'cut': ['konda', 'kulula', 'teta', 'keka', 'tenga', 'lenga', 'henda'],
     'cutting': ['eteto'], 'cutworm': ['enkandyangali'], 'Cyprus': ['Ciprus'], 'Cyprian': ['Omuciprusa'], 'Czechoslovakia': ['Czechoslovakia']}

d = {'dabchick': ['neyumbo', 'ondjumbu', 'neumbu', 'okaneumbu'], 'dagga': ['epangwe'], 'dagger': ['omwele'], 'daily': ['esiku kehe'],
     'dam': ['ondama'], 'damage': ['yonagula'], 'damn': ['thinga'], 'damp': ['omuku'], 'dance': ['nyanda', 'tanta', 'tutula', 'dhana'],
     'dancer': ['omudhani'], 'danger': ['oshiponga'], 'dangerous': ['shi na oshiponga'], 'dark': ['luudha', 'wiwila'], 'darkness': ['omulema'],
     'darn': ['lapa'], 'dash': ['nipuka', 'oshidhiladhilitho'], 'date': ['enyolwasiku', 'omuye'], 
     'daughter': ['omukadhona', 'omwanakadhona'], 'dawn': ['eluwa'], 'day': ['esiku'], 'daybreak': ['eluwa', 'momaushu', 'moontundumene'],
     'daylight': ['omutenya'], 'dead': ['sa'], 'deaf': ['thita omakutsi'], 'dealer': ['omulandithi', 'omupindiki'], 'death': ['eso'],
     'debate': ['tompathana', 'patathana', 'omuye'], 'debit': ['odebete'], 
     'debt': ['ongunga', 'onkuma', 'oshikolo'], 'decade': ['oomvuLa omulongo'], 'deceased': ['nakusa', 'omusi'], 'deceit': ['ekotokelo'],
     'deceive': ['kotokela'], 'December': ['Desemba'], 'deciduous tree': ['omuyagumuki'], 'decide': ['tokola'], 'decision': ['etokolo'],
     'decline': ['siluka', 'peguka'], 'decoration': ['uuwopali'], 'decrease': ['shonopeka'], 'decree': ['eutho'], 'deed good': ['ekwathohole'],
     'deep': ['ondeendeka'], 'defeat': ['sindana', 'esindiko'], 'defence': ['eipopilo', 'egameno'], 'defend': ['popila'],
     'deforest': ['kokola'], 'deforestation': ['onkoko'], 'degree': ['ohalate'], 'deity': ['uukalunga'], 'dejected': ['lindimana', 'iyekelela'],
     'dejection': ['elindimano', 'eiyekeielo'], 'delay': ['ugauga', 'kateka', 'eimbo', 'eugaugo'], 
     'delegate': ['omukalelipo', 'omutumwalilepo'], 'deliberately': ['owina'], 'delicacies': ['iitowale'], 'deliciousness': ['uuwanawa'],
     'delight': ['enyanyu'], 'delirious': ['adhuuka'], 'deliriousness': ['eadhuuko'], 'democracy': ['uuyuki'], 
     'democratic': ['pauyuki', 'pademokrate', 'paudemolcoli'], 'demolish': ['kumuna'], 'demolisher': ['omukumuni'], 'Dane': ['Omudenmark'],
     'Denmark': ['Denmark'], 'dense': ['thita'], 'density': ['esiti'], 'dented': ['mbanduka'], 'dentures': ['omayego gopaunkulungu'],
     'department': ['oshikondo'], 'depend': ['ikwatelela'], 'dependence': ['eikwatelelo'], 'dependent': ['omwiikwateleli'], 'deport': ['tidha'],
     'deportation': ['etidho'], 'deposit slip': ['okafilipi okumbaanga'], 'depth': ['uulehi', 'uule'], 'deputy minister': ['omupehaminista'],
     'deputy secretary': ['hangayakUh'], 'descend': ['londoloka', 'heluka', 'elondoloko'], 'describe': ['hokolola', 'tongonona'],
     'description': ['ehokololo'], 'desert': ['ombuga', 'thondola'], 'deserter': ['othondolo'], 'desire': ['haluka', 'tundudha', 'ehalo', 'okahalu'],
     'despise': ['dhina'], 'despising': ['dhinwa'], 'dessert': ['okailathitho'], 'destiny': ['ethikilo'],
     'destroy': ['nyanyula', 'hanagula', 'yona'], 'destruction': ['ehanagulo', 'eyono'], 'detective': ['omupolisi gwomalunga', 'ondiindii'],
     'determination': ['eutho'], 'determine': ['utha'], 'detest': ['nyanyala'], 'detribalised': ['omukoiwakOkathe', 'ombwiti'],
     'devaluate': ['hutuka', 'ngushuluka'], 'devaluation': ['engushuluko'], 'develop': ['huma  komeho'], 'development': ['ehumo', 'ehumokomeho'],
     'deviate': ['peguka'], 'devil': ['omutondi'], 'devils-thorn': ['ondjoho'], 'devour': ['letheka'], 'dew': ['omume'], 
     'dialect': ['onyapilaka'], 'diameter': ['ontaakano'], 'diamond': ['okawe'], 'diaphragm': ['olweedhililo'], 'diarrhoea': ['oshimela'],
     'dictate': ['leshela'], 'dictation': ['ondeshela'], 'dictator': ['kayamukulwa'], 'dictatorship': ['uukayamukulwa'], 'did': ['sha longwa'],
     'die': ['sa'], 'diesel': ['ondiisela'], 'difference': ['ondjoolola', 'eyooloko'], 'differential': ['ondefa'], 'difficult': ['dhigupaila'],
     'difficulty': ['uudhigu', 'olukongo'], 'dig': ['palela', 'papula', 'fukula'], 'digest': ['nyanyagula'], 'digestion': ['einyanko'],
     'digger': ['omufukuli'], 'digging': ['efulo', 'ehupo', 'efumbulo'], 'dignity': ['esimano'], 'diligence': ['ondjungu'],  
     'diligent': ['ndjanga'], 'dilute': ['yulika', 'hampula'], 'dim': ['dhimeya', 'tsima'], 'dimple': ['ondhigilila'], 
     'dining-room': ['oshililo'], 'dinner': ['uulalelo'], 'diplomat': ['omudiplomate'], 'diplomatic': ['paudiplomate'],
     'direct': ['wilika', 'udhika'], 'direction': ['euko', 'ombinga'], 'director': ['omuwiliki'], 'dirt': ['ondoya', 'ekako', 'edhilo'],
     'dirty': ['nyateka', 'luudhika', 'nyata', 'gagala'], 'disagreement': ['okwaatsakumwe'], 'disappear': ['thenena', 'kana', 'nena'],
     'disasters': ['iihuna'], 'disbeliever': ['omukeeneitaalo'], 'discount': ['ekuthiloko'], 'discouraged': ['tyololoka', 'sholola'],
     'discover': ['nongela'], 'discovering': ['enongelo'], 'discrimination': ['oshipungo', 'lya oshipungo'], 
     'discuss': ['kwandjagela', 'kundathana'], 'discussion': ['onkundathana', 'ekundathano'], 'disease': ['omukithi'], 'dish': ['oshiyaha'],
     'dish up': ['hukula'], 'dishearten': ['tyololoka', 'sholola'], 'dishonesty': ['omakoto'], 'disk': ['ongalo'], 'dislike': ['uugelele'],
     'dislocate': ['dhomoka', 'dharnuka'], 'disorder': ['elyalyakano', 'okwaanelandulathano'], 'dispersion': ['ehalakanitho'],
     'display': ['eulukilo', 'etalitho'], 'disregard': ['thithimana', 'dhina'], 'dissatisfied': ['yemata'], 
     'distance': ['ekaakena', 'oshikako', 'oshinano', 'elala'], 'distil': ['dhindola'], 'distribute': ['hawaleka', 'topola'],
     'distribution': ['ehawaleko', 'etopolo'], 'district': ['oshikandjo'], 'disturb': ['zizilika', 'piyaganeka'], 'disturbance': ['eziziliko'],
     'ditch': ['epwampwa'], 'divide': ['pambula', 'topola'], 'divider': ['omutopoli'], 'division': ['oshitopoiwa'], 
     'divorce': ['vekula', 'henga'], 'divorcée': ['omuhengwa'], 'divorcement': ['ehengo', 'ehengathano'], 
     'dizziness': ['oshitelele', 'oshidhungwe'], 'doctor': ['omwaaludhi', 'ondohotola'], 'dodge': ['yanda'], 'does': ['tashi ningi'],
     'dog': ['ombwa'], 'dolphin': ['ondolofine'], 'domestic': ['kwagumbo'], 'dominant': ['omuthindili kongudhi'], 
     'dominate': ['thindila kongudhi'], 'donate': ['gandja'], 'donkey': ['okasino', 'gwamululu', 'okandoongi'], 'donor': ['omugandji'],
     'door': ['omweelo', 'eyambi', 'osheelo', 'oshiyelo'], 'dormouse': ['nalufungu'], 'dot': ['oshitsa', 'okantongo'], 
     'double': ['mbalipaleka', 'ndambula'], 'doubling': ['embalipaleko', 'endambulo'], 'doubt': ['limbililwa', 'elimbililo'], 
     'dove': ['onguti'], 'down': ['pevi', 'pohi'], 'downpour': ['epoola'], 'dowry': ['omagano gehokanitho'],
     'drag': ['koka', 'kookolola', 'pwedha'], 'dragon': ['oshikoko'], 'drain': ['popola', 'kaheka'], 'drainage': ['epopolomeya', 'ekaheko'],
     'dramatic': ['pashinyandwa'], 'draught': ['enkwiya', 'omwiilambepo'], 'draw': ['faneka', 'thaneka', 'tenda', 'sinda', 'kweya'],
     'drawer': ['omuthaneki', 'omufaneki'], 'drawing': ['ethaneko'], 'dream': ['yaguma', 'ondjodhi'],
     'dreamer': ['omuyagumi'], 'dreaming': ['eyagumo'], 'dress': ['ohema'], 'dried': ['kaha', 'kukuta'], 'drift': ['onkondo', 'oshau'],
     'drill': ['mboola'], 'drilling machine': ['omboola', 'omboolamashina'], 'drink': ['indooha', 'nwa', 'oshikunuwa', 'oshinuwa'],
     'drinker': ['omunwi'], 'drinking place': ['enwino'], 'drip': ['ndonda', 'nogela'], 'drive': ['hinga'], 'driver': ['omuhingi'],
     'driving': ['ehingo', 'okuhinga'], 'drizzle': ['okanyaganye'], 'drool': ['yeya'], 'drop': ['eta'], 'dropping': ['ombundu'],
     'drought': ['uulumbu', 'oluteni', 'oshikukuta', 'ompinya', 'ekomba', 'ondjala'], 'drowse': ['kumuka', 'kotha'], 'drug': ['oshingangamithi'],
     'drum': ['ekandiina', 'ondoloma', 'endolondolo', 'ontunda'], 'drunk': ['kolwa'], 'drunkard': ['onkolwe'], 
     'drunkenness': ['uunkolwe'], 'dry': ['kukutu'], 'dryness': ['uukukutu'], 'duck': ['ombaka'], 'due': ['molwa'], 'dugout canoe': ['owato'],
     'duiker': ['ombambi'], 'dumb': ['ombolo'], 'deaf': ['ombolo'], 'dung': ['elombo'], 'during': ['pethimbo'], 'dusk': ['oshiwiwili'],
     'dust': ['pupula', 'ontsi'], 'duty': ['oshinakugwanithwa', 'oshilonga'], 'dwarf': ['okangongolo'], 'dweller': ['ombwiti'], 'dwelling': ['olukaiwa'],
     'dye': ['daya', 'efumika'], 'dynamite': ['ondilimani'], 'dysentery': ['oshitokota', 'oshimela shombinzi']}


# print(len(d))
# b_words = [i.strip() for i in a]
# for word in b_words:
#      if word.isupper():
#           print(word)

# Check for Oshindonga words startig with caps
# input_var = d
# for word in input_var:
#      for osh_word in input_var[word]:
#           if osh_word[0].isupper():
#                print(osh_word)
# print("Done checking!")

# Check for English words startig with caps
# input_var = d
# for word in input_var:
#      if word[0].isupper():
#           print(word)
# print("Done checking!")

words = [i for i in d]
for i in words:
     if words.count(i) > 1:
          print(i)
# print(words)