a = {'abate': ['iota'], 'abattoir': ['okatomeno'], 'abbreviation': ['efupipiko'], 'abdomen': ['omumpanya'], 
'lower abdomen': ['oshinena'], 'abduct': ['mbemba'], 'abduction': ['embembopo'], 'ability': ['evulo'], 
'able': ['pondola'], 'nose about': ['petapeta'], 'search about': ['thimbilathimbila'], 'above': ['kombanda'], 
'abscess': ['oshitumbuka'], 'absence': ['uukeepo'], 'absent': ['ke po'], 'absorb': ['nina'], 'abstain': ['idhilika'], 
'abundance': ['eloolo', 'nuwambwa'], 'abundant': ['ha', 'hi'], 'academy': ['oakademi'], 'accelerate': ['ulumika'], 
'accent': ['oaksende'], 'accidentally': ['ohaluka', 'pashaadhilila'], 'accomodation': ['ekalwahala'],
'accompany': ['enda', 'thindikila'], 'according to': ['pa'], 'according to nature': ['paunshitwe'], 
'accordion': ['enambati'], 'account': ['moiwa'], 'accountability': ['eyalulo', 'uupulwankombo'],
 'accurately': ['lela', 'naanaa'], 'accusation': ['elundilo'], 'accuse': ['lundila'], 'accused': ['omutamanekwa'], 
'accuser': ['omulundili', 'omutamaneki'], 'accustomed': ['igilila', 'Ieyana'], 'acrophobia': ['uugelele'], 
'actor': ['omunyandi'], 'adansonia digitata': ['omukwa'], 'adapt': ['iyikitha', 'iyigililitha', 'iyeleka'],
'add': ['hoha', 'gwedha'], 'adding': ['egwedhelo'], 'addition': ['etulokumwe'], 'additional': ['gwedhwa po'],
'addressee': ['omutuminwa'], 'adenoid': ['omwenge'], 'adhere': ['kakatela'], 'adjective': ['oshityalupe'], 
'adjourn': ['zimbuka'], 'adjournment': ['ezimbuko'], 'adult': ['omukuluntu'], 'adulterer': ['omuhondeli'], 
'adultery': ['oluhondelo'], 'practise adultery': ['hondela'], 'adulteress': ['omuhondeli'], 'adversity': ['omupya'], 
'advertisement': ['etseyitho', 'etseyithilo'],  'advise': ['tsa omayele', 'gandja omayele'], 'advice': ['omayele'], 
'aeroplane'; ['odhila', 'ondhila'], 'aesthetic': ['uuwopali'], 'affiliate': ['hemukila', 'mumwe'], 
'affiliation': ['ehemukilomumwe'], 'Afrikaans': ['Oshimbulu'], 'after': ['konima'], 'after': ['opo ihe', 'opo nduno'], 
'afternoon': ['komatango'], 'again': ['ishewe', 'natango'], 'against': ['pooha'], 'age': ['uukokele'], 
'agenda': ['oagenda' 'elandulathano'], 'agitate': ['tsa omaminimini'], 'agree': ['pitika', 'zimina', 'uvanena', 'uvathana;], 
'agreement': ['euvathano',' euvaneno'], 'agriculture': ['uunamapya'], 'agricultural': ['kwafaalama'], 
'agronomy': ['uunongononimapya'], 'agronomist': ['omunongononimapya'], 'ahead': ['komeho'], 
'aim': ['odha', 'lalakanena', 'oshilalakanenwa'], 'air': ['ombepo', 'ewangandjo'], 'alarm': ['onkugo'], 
'albino': ['thithi'], 'albizia anihelmintica': ['omupopo'], 'album': ['oalbuma', 'embo lyomathano'], 
'alcohol': ['alkoholi'], 'alcoholic': ['iikolitha', 'onkolwe'], 'algae': ['onguwi'], 'alkali': ['oalikali', 'oshimongwa], 
'alkaline': ['paalikali', 'pashimongwa'], 'all': ['he'], 'alliance': ['ondjuvanene', 'ehangano'], 'allurement': ['oshinge'], 
'aloe': ['endombo'], 'alone': ['ke'], 'alone': ['mwene '], 'alphabet': ['aambeendee'], 
'alphabetically': ['paambeendee', 'pahaanibeendee'], 'children': ['aanona'], 'also': ['wo', 'ootu'], 
'alternative': ['epingeno'], 'although': ['nando', 'nonando'], 'aluminium': ['oaluminiuma'], 'always': ['aluhe'], 
'amateur boxer'; ['omumbokisilinyanyu'], 'amazing': ['kuinithi'], 'ambassador': ['omukalelipo'], 'ambush': ['elangelo'], 
'ammonia': ['amoniaka'], 'ammonium sulphate': ['amoniumsulfate'], 'ammunition': ['oshuumbithi, 'oshiyumbithi'],
'amnesty': ['esohenda lyoonkwatwa'], 'among': ['mokati'], 'amongst': ['mokati'], 'amount': ['omwaalu', 'omiyalu'], 
'amulet': ['oshigegeti'], 'analyse': ['vongokonona'], 'analysis': ['evongokonono'],  'anatomy': ['oanatomi'], 
'anatree': ['omuyele'], 'ancestor': ['epipi', 'omukulugonale', 'omukwampungu'], 'ancestral spirits': ['aathithi'], 
'anchor': ['hangela'], 'anchor': ['ohangela'], 'ancient': ['uukulupe womutoko'], 'and': ['e', 'na'],
'angel': ['omuyengeli'], 'angle': ['okolonela', 'ekuvu,' 'onkuvu'],  'wild': '[oshiyamakuti'], 'ankle': ['onyugu'], 
'annex': ['tenda ko'], 'annexation': ['etendoko'], 'announce': ['imeleta', 'ilombola', 'tseitha'], 
'annoy': ['hinda', 'yemateka'], 'annual function': ['okatuthihulitho'], 'anoint'; ['gwayeka'],
'another': ['kwawo', 'lwe'], 'answer';  ['yamukula', 'eyamukulo'], 'ant': ['ondhindhi', 'eteta'], 
'ant-bear': ['eyamayama'], 'ant-eater': ['ongaka'], 'ant-hill': ['oshaanda', 'oshiyanda'], 'anthrax': ['ombulwa'], 
'antibiotic': ['oshidhipagimbuto', 'omuti'], 'anticipate': ['tegamena'], 'anticipation': ['etegameno'], 
'anus': ['onufu'], 'anxiety': ['omahwilili', 'uuhwenge'], 'anxiously': ['nyulukuta'], 'anvil'; ['oshikalo'], 
'any': ['kehe'], 'anyone': ['kehe ngoka'], 'anything': ['kehe shimwe'], 'anyway': ['ando'], 'aorta': ['aorta'], 
'ape': ['ondjima'], 'apoplexy': ['ombanda', 'esilombanda'], 'apparatus': ['oaparate', 'oshilongitho'], 
'apparition': ['oshihehelela', 'oshikwafa'], 'appeal': ['tsikilitha ompangu', 'etsikilompangu', 'indila', 'eindilo'], 
'appear': ['holoka', 'mbanduka', 'uluka'], 'appearance': ['ondjelo', 'eholoko', 'ombelo'], 'appendicitis': ['okiimili'], 
'appendix': ['okiimili', 'oshigwedhelwako'], 'appetite': ['omwamwa'], 'applaud': ['hakela', 'pandula'], 
'applause': ['ehakelo', 'ekugililo'], 'apple': ['oshiapula', 'oshiyapula'], 'application': ['eindilo'],  
'apply': ['longitha', 'ninga eindilo'], 'appoint': ['lenga', 'ulika'], 'appointment': ['oshilage', 'euliko'], 
'approach': ['hedha', 'engena', 'omukalo'], 'approximately': ['konyala', 'lunga'], 'April': ['Apilili'], 
'apron': ['oshitetahema'], 'aquarium': ['oakwariuma'], 'Arab': ['Omwaarabia', 'Aayarabia'], 'arbitrate': ['potokonona'], 
'arbitrator': ['omupongololi', 'omupotokononi'], 'architect': ['omuthanekingulu', 'omusindingulu', 'omusindigumbo'],  
'argue'; ['tamanana'], 'argument'; ['oontamanana'], 'arm'; ['okwaako', 'okwooko', 'okooko'], 'armpit': ['onkwapa'],
'armament': ['ehomato'], 'armed': ['homata'], 'around': ['omudhingoloko'], 'arrange': ['pongolola', longekidha], 
'arrangement': ['elongekidho', 'eilongekidho'], 'arrest': ['kwata', 'tula miipandeko', 'manga po'], 
'arrive': ['thika'], 'arrival': ['eyo', 'ethiko'], 'arrogance': ['elundu'], 'arrow'; ['oshikuti', 'omuvi'], 
'artery': ['onkandjambinzi'], 'article': ['oshinima', 'okatendo'], 'artisan': ['engomba'], 'artist': ['omunongo',  'onkulungu'], 
'art': ['uunkulungu', 'uunongo', 'uungongi'], 'as far as': ['sigo'], 'as soon as': ['hela tuu'], 
'asbestos': ['oasbesa'], 'Asia': ['Asia'], 'Asian': ['Omwaasia', 'Aayasia'], 'ash': ['omutoko'], 'aside': ['kombinga'],
'assegai': ['egonga'], 'assembly': ['omutumba'], 'assignment': ['oshitopolwa shiilonga', 'oshitopolwailonga'], 
'assist': ['kwatha', 'ambidhidha'], 'assistant': ['omuyakuli', 'omupeha'], 'assistance': ['ekwatho', 'eambidhidho'],
'association': ['ehangano'], 'asthma': ['oasma'], 'astonishment': ['onkumwe'], 'astonish': ['kumitha'], 
'astounding': ['kumithi'], 'at': ['p-', 'k-'], 'atom': ['oatoma'], 'atomic': ['paatoma'], 'Atlantic': ['Atlantika'], 
'atlas': ['oatilasa', 'oatlasa'], 'atmosphere': ['ombepo ', 'ongandjombepo', 'ewangando'], 'attach': ['kopeka'], 
'attack': ['umpila', 'ponokela', 'homona', 'tondokela'], 'attacker': ['omuhomoni', 'omumatukili', 'omutondokeli', 'omuponokeli'], 
'attempt': ['kambadhala', 'ekambadhalo', 'onkambadhala'], 'attend': ['sikola', 'ndhindhilika', 'hita'], 
'attention': ['eimweneneno', 'ndhindhilika'], 'attentiveness': ['oonkoto'], 'attitude': ['omikalo', 'oohedhi'], 
'attract': ['fuula', 'fuuka'], 'attraction': ['ohokwe'], 'attractive': ['hokitha'], 'auction': ['fanditha', 'ofanditha', 'elanditho'],
'auctioneer': ['omulandithi'], 'August': ['Auguste'], 'aunt': ['kuku', 'yinagona'], 'my aunt': ['memegona'],
'Australia': ['Australia'], 'Australian': ['Omwaaustralia', 'Aayaustralia'], 'Austria': ['Austria'}, 
'Austrian': ['Omwaaustria', 'Aayaustria'], 'authority': ['oompango', 'oonkondo'], 'autumn': ['oshikufuthinge'],
'available': ['shili po'], 'avert': ['ingila','yanda'], 'avocado': ['oshiavokado'], 'avoid': ['iyageka', 'yanda', 'keelela'], 
'awake': ['penduka', 'papudhuka'], 'awakening': ['ependuko'] 'aware': ['shi', 'nongela'], 'awareness': ['enongelo'], 
'away': ['yi', 'ya'], 'awl': ['oniho'], 'axe': ['ekuya'], 'axle': ['oakiseli', 'oakisa'], 'axis': ['oakiseli']
}

b = {'baboon':['ondjima', 'lunkima'], 'baby':['okahanona', 'omuholike'], 'back':['omugongo', 'ombunda'],
    'backbone':['omugongo', 'esipa lyombunda'], 'backbite':['hokola'], 'backbiter':['omuhokoli'],
    'background':['osindo'], 'backside':['etako', 'konima'], 'bacteria':['ombakiteli'], 'bad':['ha'],
    'badge':['oshihako', 'ombandi'], 'badly':['nayi'], 'badness':['uuwinayi'], 'bag':['oshako', 'ondjato'],
    'bail':['eimbeelomo', 'omboloha'], 'bake':['mbaka','yotha'], 'bakery':['ombeka'], 'baking-powder':['efulika'],
    'balance':['ontengelelo', 'oshihupe'], 'bald' :['ongwala'], 'bale':['oshihampi'], 'ball':['etanga'],
    'balloon':['embalona'], 'weather':['onkalo yombembo'], 'ballot':['ombapila yehogololo '], 'ban':['konda'],
    'banana':['embanana', 'omumbanana'], 'bandolier':['ekwamo'], 'bang':['ngwanda'], 'bangle':['okagondo'],
    'bank':['pungula', 'ombaanga'], 'bankrupt':['mbangolota'], 'bankruptcy':['embangoloto'],
    'baobab':['omukwa'], 'baptise':['shasha'], 'baptiser':['omushashi'], 'bar':['ombaa', 'enwino'],
    'barbed hook':['ongona'], 'barber':['omukululi'], 'barbershop':['okakululilo'], 'barefoot':['ohuuna'],
    'bark':['eyula', 'gwedha'], 'barrel':['oluungu'], 'barter':['pingakanitha'],'basic':['ekota'],
    'basin':['oshiyaha', 'okatemba'], 'basis':['oshimbu'], 'basket':['ontungwa'], 'grain basket':['eshisha', 'oshigadhi'],
    'bass' :['omugono', 'ombaatha'], 'bat':['elimalima'], 'bathroom':['okaiyogelo'], 'battery' :['emanya', 'opatrii'],
    'battle':['olugodhi'], 'beach':['omunkulofuta'], 'beak':['omulungu', 'epakululu'], 'beam':['omutenge', 'oonte'],
    'bean':['ekunde'], 'bean sauce':['oshigali'], 'bear':['vala', 'humbata', 'ima', 'emwanka'],'beard':['oombenzi)'],
    'bearer':['omuhumbati'], 'beast':['ongombe'], 'beat':['thekula', 'thepagula', 'dhenga'], 'beautiful' :['opala', 'wanawa'],
    'beautify':['opaleka'], 'beauty':['uuwopali', 'uuyogoki','uuwanawa'], 'because':['oshoka','shaashi', 'molwashoka'],
    'beckon':['lapa'], 'bed':['ontala', 'ombete'], 'bedding':['iinguma'], 'bee':['onyushi'], 'beer':['ombiila', 'omalovu'],
    'beestings':['epuya'], 'beeswax':['ezi'], 'beetle':['ondjimbi', 'okambaambala'], 'beetroot':['eroibiyeta'], 
    'before':['manga','komeho'], 'beg':['hehela','indila', 'galikana'], 'begging':['egalikano', 'eindilo', 'ehehelo'],
    'behave':['ihumbata'], 'behaviour':['eihumbato', 'omaihumbato', 'omikalo'], 'begin':['tameka'],'beginner':['omutameki'],
    'beginning':['etameko'], 'belief':['eitaalo'], 'believe':['itaala'], 'believer':['omwiitaali'], 'belong':['gama'],
    'below':['pevi'], 'bell':['ongendjo'], 'bellow':['ula'], 'belly':['epunda'], 'beloved':['omuholike'], 
    'belt':['omuya', 'epaya'], 'bench':['oshipundi'], 'bend':['petama', 'gonya'], 'bent':['egoli'], 'berry':['okayimati'],
    'besides':['kakele'], 'bestman':['oshinkumbi'], 'betray':['gwaaleka', 'kengelela', 'nwa po'], 'betrayer':['omugwaaleki'],
    'better':['hwepo'], 'beware':['angla', 'kotoka'], 'bewitch':['tikila', 'loga'], 'beyond':['pombanda'],
    'Bible':['Ombiibeli'], 'bicycle':['okathanguthangu', 'okambasikela'], 'big':['-nene'], 'bigamy':['ombanda'],
    'bill':['oongunga', 'iifuta'], 'billion':['obiliyona'], 'billow':['tuwalala'], 'biltong':['oludhingu'],
    'bird':['okadhila', 'ondhila'], 'bioscope':['okino'], 'birth':['vala', 'pulumutha'], 'birthday':['esiku lyevalo'],
    'bisect':['tateka'], 'bishop':['omumbisofi'], 'bit':['sha', 'okanima'], 'bite':['lumata'], 'bitter':['lula'],
    'bitterness':['uululu'],  'black':['luudhe'], 'blackboard':['oshipelende'], 'blacken':['luudhika', 'nyateka'],
    'blackmail':['thina'], 'Blacks':['Aaluudhe'], 'blacksmith':['omuhambudhi', 'omuhambuli'], 'blade':['efo lyomwele'],
    'bladder':['okampunda komasita'], 'blanket':['ekumbatha'], 'blast':['topa'], 'blaze':['omulilo'], 'bleat':['lila'],
    'bleed':['hiha'], 'bless':['yambeka'], 'blesser' :['omuyambeki'], 'blessing' :['ehaleloyambeko', 'eyambeko'],
    'blind':['toga', 'tsika', 'omuposi'], 'blindness':['uuposi'], 'blister':['epuya', 'oompekehe'], 'block':['keelela'],
    'blood':['ombinzi'], 'blossom' :['onsheno', 'sheneka'], 'blouse':['ohema yoshikiintu'], 'blow':['pepa', 'fudhila', 'fugula', 'pemba'],
    'blowlamp':['olamba yokufikilitha'], 'blue':['mbulau'], 'blunt':[ 'simpa'], 'board':['menekela', 'embolota'], 
    'boast':['inoma'], 'boat':['ombautu'], 'body':['olutu'], 'boil':['fuluka', 'ethina'], 'bomb':['mboma', 'omboma'],
    'bombardment':['embomo'], 'bomber' :['omumboni'], 'bone':['esipa'], 'bonus':['ombonasa'], 'book':['embo', 'oshifo', 'okambo'],
    'boomslang':['iifoyamusati'], 'boot':['ombuta', 'ombutsa', 'thanga'], 'booth':['okangulu'], 'border':['ongamba'],
    'borehole':['omboola'], 'borrow':['hehela'], 'botany':['obotani', 'ontseyoimeno'], 'bottle':['ekende'],
    'bottletop':['oshisiikilitho', 'okasiikilitho'], 'bottom':['oshitako', 'kohi'], 'boulder':['ethindimanya'],
    'boundary':['ontaululi'], 'bow':['uutati', 'uuta wanangongo'], 'bowtie':['okakunde'], 'box':['oshiketha', 'okapakete', 'oongonyo'],
    'boxer':['omudhengingonyo'], 'boy':['okamati', 'omumati'], 'boyhood':['uumati'], 'brain':['uuluyi'],
    'brake':['ombiliki', 'mbilika'], 'bran':['uuhutu'], 'branch':['oshitayi'], 'brandy':['ombike', 'ombelendi'],
    'brave':['pendapala'], 'bravery':['onyati', 'uufule'], 'bray':['koma'], 'bread':['omboloto', 'oshikwiila'],
    'breadth':['omutamo '], 'break':['pambula', 'tatula', 'teya', 'tokola', 'topola', 'kumuna', 'ngumuna', 'okafudho'],
    'breast':['ondete', 'egundji'], 'breath':['omufudho'], 'breathe':['fudha'], 'breed':['kola', 'muna'],
    'brew':['hanga', 'dhunga'], 'brewery':['ombuulaye'], 'bribe':['ombumbo'], 'brick':['ondhopi'], 'bride':['omufuko'],
    'bridegroom':['omufuko', 'ombushiki'], 'bridesmaid':['oshinkumbi'], 'bridge':['ontopa', 'kwatakanitha'], 'bridle':['oshitomo'],
    'briefcase':['ompunda', 'okataasi'], 'bright':['yelele', 'adhima'], 'gnu':['ompugulu'], 'bring':['eta'],
    'broadcast':['tuma mombepo'], 'brochure':['obroshure'], 'broom':['oluhwati', 'oshikombe'], 
    'brother':['omumwayina', 'omumwayinamati', 'mbuluta'], 'brown':['ndjimbi', 'mbambi'], 'bubble':['ombwimbwi', 'gwagwata'],
    'bubonic plague':[ 'uuvu wombuku'], 'bucket':['eyemele', 'etenga'], 'buckle':['ompate'], 'bud':['shena', 'osheno'], 
    'budget':['etengenekothaneko'], 'buffalo':['onyati'], 'build':['tunga'], 'builder':['omutungi'], 
    'building':['etungo', 'ongulu', 'egumbo'], 'bulb':['ombimbo', 'etindi', 'okambiyena', 'okalamba'], 'edible':['ongehu', 'oshikuliwa'],
    'bulge':['umbuka'], 'bull':['ontsenzi'], 'bulletin':['ombuletine'], 'bump':['nguma', 'puma'], 'bunch':['ehila'],
    'bundle':['oshihampi', 'oshipandi', 'okapandi', 'okahampi'], 'burn':['fika', 'lunguna', 'pya'],
    'burn-marks':['oondjota'], 'burrow':['omvugo'], 'bursary':['iimaliwa yokwiilongitha'], 'burst':['topa', 'tenda'],
    'bury':['fumbika', 'fumvika'], 'bus':['ekambamba', 'ombesa'], 'bush':['oshiheke', 'oshihwa'], 'Bushman':['Omukwankala'],
    'business':['uunangeshefa', 'ongeshefa'], 'businessman':['omunangeshefa'], 'busy':['sikuuka', 'ipyakidhila'], 'but':['ihe', 'ndele'],
    'butcher':['omutseli'], 'butchery':['oshilahite'], 'butter':['omagadhi','ombuta'], 'butterfly':['embiimbili', 'okambiimbili'],
    'buttock':['etako'], 'button':['ombandi', 'pata'], 'buy':['landa'], 'buyer':['omulandi'], 'by':['ku'], 
    'bypass ':['kunkula', 'kunduluka', 'dhingoloka']}
 
print(len(b))
b_words = [i.strip() for i in b]
print(b_words)