new_words = {
    "he": ["a"],
    "she": ["a"],
    "Africans": ["Aafrica", "Aafrika"],
    "Angolans": ["Aangola"],
    "Babylonians": ["Aababiloni", "Aababilonia"],
    "Beerotians": ["Aabeeroti"],
    "Belgians": ["aabelgium"],
    "Benjaminians": ["aabenjamin"],
    "boxers": ["aabokisi", "aambokisi", "aadhengingonyo", "aadhaningonyo"],
    "Chinese": ["Aachiina", "Aachina", "Aakiina"],
    "Cubans": ["Aacuba"],
    "Damascene": ["Aadamaskus"],
    "found": ["aadhamo", "adhamo", "adhele", "adhikwa", "adhiwa", "andhika"],
    "was found": ["adhikile"],
    "were found": ["adhikile"],
    "players": ["aadhani"],
    "main players": ["aadhaninkandangala"],
    "main actors": ["aadhaninkandangala"],
    "Ovazemba people": ["Aadhemba"],
    "callers": ["aadhengi"],
    "beaters": ["aadhengi"],
    "trainers": ["aadheuli", "aadhewuli"],
    "coaches": ["aadheuli", "aadhewuli"],
    "trainees": ["aadheulwa", "aadhewulwa", "aalongwa"],
    "difficult": [
        "aadhigu",
        "dhigupala",
        "dhigupale",
        "dhigupalela",
        "dhigupalele",
        "dhigupalelela",
        "dhigupalelwa",
    ],
    "was found": ["aadhika"],
    "were found": ["aadhika"],
    "slave women": ["aadhike", "aadhikekadhi"],
    "women slaves": ["aadhike", "aadhikekadhi"],
    "the forgotten": ["aadhimbiwa"],
    "the forsaken": ["aadhimbiwa"],
    "despised people": ["aadhinwa"],
    "killers": ["aadhipagi"],
    "murdrers": ["aadhipagi"],
    "vicious": ["aadhudhu"],
    "deacons": ["aadiakoni"],
    "Egytians": ["Aaegipiti", "Aayegipiti", "Aegipiti"],
    "Spaniards": ["Aaespania"],
    "Europeans": ["Aaeuropa"],
    "passengers": ["aafaalelwa", "aafalelwa", "aalondekwa"],
    "interpreters": ["aafatululi"],
    "translators": ["aafatululi"],
    "accused": ["aafekelwa", "aatamanekwa"],
    "accused persons": ["aafekelwa", "aatamanekwa"],
    "revenue collectors": ["aafendelithi"],
    "receivers of revenue": ["aafendelithi"],
    "tax collectors": ["aafendelithi"],
    "Philippians": ["Aafilippi"],
    "French": ["Aafrance"],
    "hypocrites": ["aafudhime"],
    "brides": ["aafuko"],
    "bridegrooms": ["aafuko", "aafukolume"],
    "narcissists": ["aafuli"],
    "vain people": ["aafuli"],
    "liars": ["aafundja"],
    "short": ["aafupi"],
    "thieves": ["aafuthi", "aalunga", "aayikuthili", "aayugi"],
    "payers": ["aafuti"],
    "mercenaries": ["aafutwakwiita", "aakwiitafutwa"],
    "those who pray": ["aagalikani"],
    "returnees": ["aagaluki"],
    "protectors": ["aagameni"],
    "givers": ["aagandji"],
    "advisors": ["aagandjimayele", "aagandjindunge", "aanamayele"],
    "angry people": ["aageyentu"],
    "Ghanaians": ["Aaghana"],
    "collectors": ["aagongeli"],
    "idiots": ["aagoya"],
    "youth": ["aagundjuka", "aanyasha"],
    "young people": ["aagundjuka"],
    "youngsters": ["aagundjuka", "aanyanyamagulu"],
    "young boys": ["aagundjukamati"],
    "traitors": ["aagwaaleki"],
    "healers": ["aahakuli"],
    "traders": ["aahalithi", "aapindiki"],
    "blacksmiths": ["aahambudhi"],
    "forgers": ["aahambudhi"],
    "blacksmiths": ["aahambuli"],
    "forgers": ["aahambuli"],
    "allies": ["aahangani"],
    "the untrustworthy": ["aahasha"],
    "exploiters": ["aahepeki"],
    "abusers": ["aahepeki"],
    "the exploited": ["aahepekwa"],
    "the abused": ["aahepekwa"],
    "victims": ["aahepekwa"],
    "Herero people": ["Aaherero"],
    "musicians": ["aahikingalo"],
    "Himba people": ["Aahimba"],
    "Ovahimba people": ["Aahimba"],
    "drivers": ["aahingi", "aashingi"],
    "inviters": ["aahiyi"],
    "invitees": ["aahiywa"],
    "voters": ["aahogololi"],
    "returning officers": ["aahogololithi"],
    "candidates": ["aahogololwa", "aaulikwa", "aawulikwa", "aaulikwahogololwa"],
    "the couple": ["aahokanathani", "aayihokanathani", "aayihomboli"],
    "spouses": ["aahokanathani", "aayihokanathani", "aayihomboli"],
    "married women": ["aahokanwa"],
    "gossipers": ["aahokoli"],
    "narrators": ["aahokololi"],
    "story-tellers": ["aahokololi"],
    "lovers": ["aaholathani"],
    "loverbirds": ["aaholathani"],
    "immitators": ["aaholeli"],
    "copycats": ["aaholeli"],
    "lovers": ["aaholi"],
    "likers": ["aaholi"],
    "beloveds": ["aaholike"],
    "sport lovers": ["aaholimaudhano"],
    "peace lovers": ["aaholimbili"],
    "protesters": ["aahololimadhilaadhilo", "aahololimadhiladhilo"],
    "protesters": ["aahololimadhilaadhilo", "aahololimadhiladhilo"],
    "promiscuous people": ["aaholume"],
    "promiscuous people": ["aaholume"],
    "sexually immoral people": ["aaholume"],
    "managers": ["aahona"],
    "bosses": ["aahona"],
    "adulterers": ["aahondeli"],
    "adulteresses": ["aahondelwa"],
    "tailors": ["aahondji"],
    "pastors": ["aahongi", "aasita", "aasitagongalo"],
    "tempters": ["aahongololi"],
    "last ones": ["aahugunini"],
    "nominees": ["aahulikwa", "aaulikwa", "aawulikwa"],
    "carriers": ["aahumbati"],
    "prophets": ["aahunganeki", "aaprofeti"],
    "counselors": ["aahungimwenyo"],
    "counsellors": ["aahungimwenyo"],
    "savers": ["aahupithi"],
    "redeemers": ["aahupithi"],
    "survivors": ["aahupithwa"],
    "activists": ["aahwahwameki"],
    "influencers": ["aahwahwameki"],
    "patient people": ["aaidhidhimiki"],
    "abstainers": ["aaidhiliki"],
    "modest people": ["aaifupipiki", "aayifupipiki", "aaishonopeki"],
    "students": ["aailongi", "aayilongi", "aalongwa", "aalongwasikola"],
    "singers": ["aaimbi", "aayimbi"],
    "Indians": ["Aaindia"],
    "requesters": ["aaindili"],
    "those who pray": ["aaindili"],
    "trusted people": ["aainekelwa", "aayinekelwa"],
    "trustworthy people": ["aainekelwa", "aayinekelwa"],
    "most trusted people": ["aainekelwalela"],
    "most trustyworthy people": ["aainekelwalela"],
    "conceited people": ["aainenepeki", "aayinenepeki"],
    "braggers": ["aainomi"],
    "registrants": ["aainyolithi", "aaishangithi", "aayishangithi"],
    "Iranians": ["Aairan"],
    "Israelis": ["Aaisraeli"],
    "believers": ["aaitaali"],
    "volunteers": ["aaiyambi", "aayiyambi"],
    "godless people": ["aakaanakalunga", "aakeenakonashanakalunga"],
    "the righteous": ["aakaanandjo", "aayuki", "aayuuki"],
    "righteous people": ["aakaanandjo", "aayuki", "aayuuki"],
    "tabooless people": ["aakaanashipwe"],
    "the faithless": ["aakaaneitaalo"],
    "faithless people": ["aakaaneitaalo"],
    "non-believers": ["aakaaneitaalo"],
    "nonbelievers": ["aakaaneitaalo"],
    "merciless people": ["aakaanohenda"],
    "girls": ["aakadhona"],
    "agents": ["aakalelipo"],
    "representatives": ["aakalelipo", "aapopili"],
    "the police": ["aapolisi", "aakalekipoveta"],
    "residents": ["aakali"],
    "residents": ["aakalimo"],
    "occupants": ["aakalimo"],
    "Caprivians": ["Aakaprivi"],
    "Catholic": ["Aakatoolika"],
    "Kavango people": ["Aakavango"],
    "horse riders": ["aakawilinkambe", "aakayilinkambe"],
    "offenders": ["aakawulinyanga", "aakayulinyanga"],
    "riders": ["aakayili"],
    "preventers": ["aakeeleli", "aakeleli"],
    "reckless people": ["aakeenakonasha"],
    "Christians": ["Aakelesiti", "aakriste"],
    "deceivers": ["aakengeleledhi", "aakotokeli"],
    "tricksters": ["aakengeleledhi", "aaniineya"],
    "cons": ["aakengeleledhi", "aakotokeli"],
    "fraudsters": ["aakengeleledhi", "aakengeleli"],
    "females": ["aakiintu"],
    "women": ["aakiintu", "aakintu", "aakulukadhi"],
    "ladies": ["aakiintu", "aakintu", "aakulukadhi"],
    "the elderly": ["aakokele", "aakulupe"],
    "Aakolonkadhi people": ["Aakolonkadhi"],
    "colonisers": ["aakolonyeki"],
    "leaders": ["aakomeho", "aaleli", "aawiliki", "aakwatelikomeho"],
    "communists": ["aakomunisi"],
    "investigators": ["aakonaakoni", "aakonakoni"],
    "suspects": ["aakonakonwa", "aafekelwa", "aakonenenwa"],
    "fighters": ["aakondjeli", "aakondji"],
    "freedom fighters": ["aakondjelimanguluko"],
    "opponents": ["aakondjithi"],
    "controllers": ["aakondololi"],
    "seekers": ["aakongi"],
    "hunters": ["aakongo"],
    "barbers": ["aakululi"],
    "elders": ["aakuluntu"],
    "principals": ["aakuluntusikola"],
    "managers": ["aakuluntuwiliki"],
    "former presidents": ["aakulupresidente"],
    "broadcasters": ["aakundaneki"],
    "informers": ["aakundaneki"],
    "participants": ["aakuthimbinga"],
    "soldiers": ["aakwaita", "aakwiita", "aakwiitatonateli"],
    "Aakwaluudhi people": ["Aakwaluudhi"],
    "Aakwambi people": ["Aakwambi"],
    "ancestors": ["aakwampungu"],
    "the poor": ["aakwanaluhepo"],
    "poor people": ["aakwanaluhepo"],
    "officials": ["aakwanambelewa"],
    "officers": ["aakwanambelewa", "aanambelewa"],
    "twins": ["aakwanambwiyu"],
    "congregation members": ["aakwanegongalo"],
    "members of the congregation": ["aakwanegongalo"],
    "family members": ["aakwanegumbo"],
    "members of the family": ["aakwanegumbo"],
    "relatives": ["aakwanezimo", "aakwazimo", "aakwao", "aakwawo"],
    "monarchs": ["aakwaniilwa"],
    "kings": ["aakwaniilwa"],
    "queens": ["aakwaniilwa"],
    "kings and queens": ["aakwaniilwa"],
    "Aakwanyama people": ["aakwanyama"],
    "meeting attendees": ["aakwashigongi", "aanashigongi"],
    "the public": ["aakwashigwana"],
    "members of the public": ["aakwashigwana"],
    "community members": ["aakwashigwana"],
    "insurers": ["aakwashilipaleki"],
    "nationals": ["aakwashilongo", "aanashilongo"],
    "Swapo members": ["aakwaswapo"],
    "coordinators": ["aakwatakanithi"],
    "co-ordinators": ["aakwatakanithi"],
    "assistants": ["aakwatheli"],
    "helpers": ["aakwatheli", "aakwathi", "aakwatiketi"],
    "beneficiaries": ["aakwathelwa", "aayambidhidhwa"],
    "rapists": ["aakwatinkonga"],
    "capturers": ["aakwatipo"],
    "kidnappers": ["aakwatipo"],
    "your relatives": ["aakweni"],
    "my relatives": ["aakwetu"],
    "foreigners": ["aakwiilongo", "aakwilongo", "aaniilongo", "aazaizai", "aazazayi"],
    "real soldiers": ["aakwiitalela"],
    "buyers": ["aalandi"],
    "customers": ["aalandi"],
    "sellers": ["aalandithi", "aashingithi"],
    "followers": ["aalanduli"],
    "tall": ["aale"],
    "very tall": ["aaleeleka"],
    "subjects": ["aalelwa", "aapangelwa"],
    "readers": ["aaleshi"],
    "Lybians": ["Aalibia"],
    "earners": ["aalikoli", "aaniiyemo"],
    "mourners": ["aalilasa", "aalilisa"],
    "field workers": ["aalimimapya", "aalongimapya", "aanamapya"],
    "crop farmers": ["aalimimapya", "aalongimapya", "aanamapya"],
    "organisers": ["aalongekidhi", "aaunganeki", "aawunganeki", "aayunganeki"],
    "workers": ["aalongeli", "aalongi", "aanilonga", "aanashilonga"],
    "victims": ["aalongelwamuyonena"],
    "teachers": ["aalongi", "aalongisikola", "aanongeki"],
    "rabbis": ["aalongihapu"],
    "jurists": ["aalongimpango", "aanongompango"],
    "users": ["aalongithi"],
    "road users": ["aalongithindjila"],
    "learners": ["aalongwa"],
    "learned people": ["aalongwantu"],
    "student nurses": ["aalongwapangi"],
    "blacks": ["aaludhe"],
    "men": ["aalumentu", "aasamane"],
    "males": ["aalumentu"],
    "real men": ["aalumentwelela"],
    "sinners": ["aalunde"],
    "accusers": ["aalundili", "aatamaneki"],
    "boys": ["aamati"],
    "gentlemen": ["aamati"],
    "real gentlemen": ["aamatilela"],
    "athletes": ["aamatuki", "aatondoki"],
    "sprinters": ["aamatuki", "aatondoki"],
    "runners": ["aamatuki", "aatondoki"],
    "Aambadja people": ["Aambadja"],
    "royalty": ["aambala", "aawa"],
    "Aambalantu people": ["aambalantu"],
    "bishops": ["aambiishofi", "aambiisofi", "aambishofi", "aambishopi"],
    "guys": ["aamentu"],
    "Americans": ["Aamerica"],
    "patients": ["aavu", "aamvu", "aanumvu", "aanuumvu", "aanuuvu", "aanuvu"],
    "paternal siblings": ["aamwahe"],
    "his paternal siblings": ["aamwahe"],
    "her paternal siblings": ["aamwahe"],
    "your paternal siblings": ["aamwaho"],
    "breasfeeding mothers": ["aamwali"],
    "siblings": ["aamwameme", "aamwayinathana"],
    "my siblings": ["aamwameme"],
    "our siblings": ["aamwameme"],
    "cousins": ["aamwamemegona"],
    "my cousins": ["aamwamemegona"],
    "our cousins": ["aamwamemegona"],
    "brothers": ["aamwamememati"],
    "my brothers": ["aamwamememati"],
    "our brothers": ["aamwamememati"],
    "my children": ["aamwandje"],
    "my daughters": ["aamwandjekadhona"],
    "my sons": ["aamwandjemati"],
    "your siblings": ["aamwanyoko"],
    "your sisters": ["aamwanyokokadhona"],
    "my paternal siblings": ["aamwatate"],
    "his siblings": ["aamwayina"],
    "her siblings": ["aamwayina"],
    "their siblings": ["aamwayina"],
    "his cousins": ["aamwayinagona"],
    "her cousins": ["aamwayinagona"],
    "their cousins": ["aamwayinagona"],
    "his sisters": ["aamwayinakadhona"],
    "her sisters": ["aamwayinakadhona"],
    "his brothers": ["aamwayinamati"],
    "her brothers": ["aamwayinamati"],
    "their brothers": ["aamwayinamati"],
    "your children": ["aamwoye"],
    "your daughters": ["aamwoyekadhona"],
    "your sons": ["aamwoyemati"],
    "children": ["aana", "aavalwa"],
    "prisoners": ["aanadholongo"],
    "diplomats": ["aanadiplomate", "aanadipolomate"],
    "farmers": ["aanafaalama", "aanafalama"],
    "cattle post owners": ["aanahambo"],
    "sympathisers": ["aanahenda", "aasihenda"],
    "the left-handed people": ["aanalumoho"],
    "leftists": ["aanalumoho"],
    "Nama people": ["Aanama"],
    "Namas": ["Aanama"],
    "well-known people": ["aanamadhina"],
    "geniuses": ["aanamaganolela"],
    "gifted people": ["aanamaganolela"],
    "house owners": ["aanamagumbo"],
    "stubborn people": ["aanamanganga"],
    "field owners": ["aanamapya"],
    "protective officials": ["aanambelewagameni"],
    "security officials": ["aanambelewagameni"],
    "supervisors": ["aanambelewawiliki"],
    "peaceful people": ["aanambili"],
    "Namibians": ["Aanamibia"],
    "the villagers": ["aanamikunda", "aanamukunda"],
    "living beings": ["aanamwenyo"],
    "fast runners": ["aanandapo"],
    "prisoners": ["aanandholongo"],
    "energetic people": ["aanandjungu"],
    "diligent people": ["aanandjungu"],
    "jealous people": ["aanandumbo"],
    "clever people": ["aanandunge"],
    "smart people": ["aanandunge"],
    "very smart people": ["aanandungelela"],
    "businessmen": ["aanangeshefa"],
    "cattle owners": ["aanangombe"],
    "debtors": ["aanangunga"],
    "powerful people": ["aanankondo"],
    "very powerful people": ["aanankondolela"],
    "reporters": ["aanankundana"],
    "news reporters": ["aanankundana"],
    "lazy people": ["aananyalo"],
    "politicians": ["aanapolitika", "aanapolotika"],
    "attendees": ["aanashiithanene"],
    "city dwellers": ["aanashilando"],
    "city residents": ["aanashilando"],
    "people with leprosy": ["aanashilundu"],
    "responsible people": ["aanashimpwiyu"],
    "epileptic people": ["aanashintona"],
    "event attendees": ["aanashituthi"],
    "learners": ["aanasikola", "aanaskola"],
    "pupils": ["aanasikola"],
    "experts": ["aanawino", "aanongontu", "aatseyinawa"],
    "residents of Ondangwa": ["Aandangwa"],
    "healthy people": ["aandjolowele"],
    "Aandonga people": ["Aandonga"],
    "Aandongwena people": ["aandongwena"],
    "publishers": ["aanduluki"],
    "manufacturers": ["aanduluki"],
    "lucky people": ["aanelago"],
    "big": ["aanene"],
    "very big": ["aanenenene"],
    "dignitaries": ["aanenentu"],
    "Angolans": ["Aangola"],
    "Nigerians": ["Aanigeria"],
    "vehicle owners": ["aaniihauto"],
    "car owners": ["aaniihauto"],
    "motor vehicle owners": ["aaniihauto"],
    "gardeners": ["aaniikunino"],
    "horticulturalists": ["aaniikunino"],
    "livestock owners": ["aaniimuna"],
    "employees": ["aanilonga", "aaniilonga"],
    "makers": ["aaningi"],
    "doers": ["aaningi"],
    "weaklings": ["aankundi", "aanuunkundi"],
    "young girls": ["aanonakadhona"],
    "wise men": ["aanongo"],
    "wise people": ["aanongo"],
    "legal experts": ["aanongompango"],
    "lawyers": ["aanongompango"],
    "attorneys": ["aanongompango", "aapopilikoveta"],
    "scientists": ["aanongononi", "aapopilikoveta"],
    "skilled people": ["aanongontu", "aanuunongo"],
    "the disabled": ["aanulema", "aanuulema"],
    "people with disabilities": ["aanulema", "aanuulema"],
    "disabled persons": ["aanulema", "aanuulema"],
    "disabled people": ["aanulema", "aanuulema"],
    "sick people": ["aavu", "aamvu", "aanumvu", "aanuumvu", "aanuuvu", "aanuvu"],
    "ill people": ["aavu", "aamvu", "aanumvu", "aanuumvu", "aanuuvu", "aanuvu"],
    "the sick": ["aavu", "aamvu", "aanumvu", "aanuumvu", "aanuuvu", "aanuvu"],
    "shack dwellers": ["aanuumbashu"],
    "shack owners": ["aanuumbashu"],
    "health workers": ["aanuunamiti"],
    "health professionals": ["aanuunamiti"],
    "blamers": ["aanuusama"],
    "drinkers": ["aanwi"],
    "actors": ["aanyandi"],
    "queens": ["aanyekadhi"],
    "writers": ["aanyoli", "aashangi"],
    "cleaners": ["aaopaleki", "aayopaleki"],
    "pagans": ["aapagani"],
    "relatives": ["aapambele"],
    "rulers": ["aapangeli"],
    "nurses": ["aapangi"],
    "judges": ["aapanguli", "aatokoli", "aatokoliveta", "aatokolihapu"],
    "tourists": ["aapashioni", "aapashiyoni"],
    "new": ["aape"],
    "brand new": ["aapeepeka"],
    "deputies": ["aapeha", "aapevi"],
    "researchers": ["aapekaapeki", "aapekapeki"],
    "Persians": ["Aapersia", "Aaperesi"],
    "deputy ministers": ["aapeviminista"],
    "slaves": ["aapika", "aapikwa"],
    "priests": ["aasita", "aapilisteli"],
    "servants": ["aapiya"],
    "disturbers": ["aapiyaganeki"],
    "rioters": ["aapiyaganeki"],
    "middlemen": ["aapokati"],
    "exiled people": ["aapongekwa"],
    "attackers": ["aaponokeli"],
    "close associates": ["aapopepi"],
    "speakers": ["aapopi"],
    "legal representatives": ["aapopilikoveta"],
    "chit-chatters": ["aapopyagani"],
    "talkative": ["aapopyagani"],
    "talkative people": ["aapopyagani"],
    "the blind": ["aaposi"],
    "the visually impared": ["aaposi"],
    "blind people": ["aaposi"],
    "people with blindness": ["aaposi"],
    "listeners": ["aapulakeni"],
    "audience": ["aapulakeni", "aatali"],
    "midwives": ["aavalithi", "aapulumuthi"],
    "investors": ["aapunguli"],
    "Portuguese": ["Aaputu"],
    "mad people": ["aapwidhi", "aapwidhuki"],
    "crazy people": ["aapwidhi", "aapwidhuki"],
    "insane people": ["aapwidhi", "aapwidhuki"],
    "Romans": ["Aaroma"],
    "Romanians": ["Aaromania"],
    "stupid": ["aasama"],
    "Samaritans": ["Aasamalia", "aasamaria", "aasinamutimahenda"],
    "widows": ["aaselekadhi"],
    "real widows": ["aaselekadhilela"],
    "Senegalese": ["Aasenegal"],
    "signatories": ["aashaini"],
    "residents of Oshakati": ["Aashakati"],
    "authors": ["aashangi"],
    "mockers": ["aasheki"],
    "scoffers": ["aasheki"],
    "neighbours": ["aashiinda"],
    "neighbors": ["aashiinda", "aashinda"],
    "neighbouring countries": ["aashindalongo"],
    "neighboring countries": ["aashindalongo"],
    "creators": ["aashiti", "aayetipo"],
    "human beings": ["aashitwa"],
    "creatures": ["aashitwa"],
    "few": ["aashona"],
    "very few": ["aashonashona", "aashuushuka"],
    "goal setters": ["aashoneki"],
    "deceased": ["aasi"],
    "dead people": ["aasi"],
    "caretakers": ["aasilishimpwiyu", "aatakamithi", "aatekuli", "aatonateli"],
    "care-takers": ["aasilishimpwiyu", "aatakamithi", "aatekuli", "aatonateli"],
    "care takers": ["aasilishimpwiyu", "aatakamithi", "aatekuli", "aatonateli"],
    "the forgiven": ["aasilwahenda"],
    "fanatics": ["aasimaneki"],
    "honourables": ["aasimanekwa"],
    "honorables": ["aasimanekwa", "aasimani"],
    "pregnant women": ["aasimba"],
    "winners": ["aasindani"],
    "achievers": ["aasindani", "aasindi"],
    "the hungry": ["aasindjala"],
    "starving people": ["aasindjala"],
    "losers": ["aasindwa"],
    "Syrians": ["Aasiria"],
    "cattle-herders": ["aasitangombe"],
    "cattle herders": ["aasitangombe"],
    "Finnish": ["Aasoomi"],
    "supporters": ["aasopoti", "aayambidhidhi"],
    "South Africans": ["Aasouth Africa"],
    "guards": ["aatakamithi", "aatonateli"],
    "security guards": ["aatakamithi yomaliko", "aatonateli yomaliko"],
    "visitors": ["aatalelipo", "aayenda"],
    "inspectors": ["aataleli"],
    "auditors": ["aataleli"],
    "spectators": ["aatali"],
    "observers": ["aatalinawa"],
    "remarkers": ["aatalululi"],
    "re-markers": ["aatalululi"],
    "prosecutors": ["aatamaneki", "aayeti yiihokolola"],
    "plaintiffs": ["aatamaneki", "aayeti yiihokolola"],
    "complainants": ["aatamaneki", "aayeti yiihokolola"],
    "beginners": ["aatameki"],
    "starters": ["aatameki"],
    "pioneers": ["aatameki", "aatoti", "aatotipo"],
    "surgeons": ["aatandi"],
    "rebels": ["aatangalali", "aatsindumbo"],
    "waiters": ["aategi"],
    "fosters": ["aatekuli"],
    "foster parents": ["aatekuli"],
    "guardians": ["aatekuli"],
    "grandchildren": ["aatekulu"],
    "great-grandchildren": ["aatekulululwa"],
    "cooks": ["aateleki"],
    "migrants": ["aatembuki"],
    "immigrants": ["aatembuki"],
    "emigrants": ["aatembukili"],
    "predecessors": ["aatetekeli"],
    "precursors": ["aatetekeli"],
    "forerunners": ["aatetekeli"],
    "harvesters": ["aateyi"],
    "breakers": ["aateyi"],
    "photographers": ["aathaneki"],
    "cameramen": ["aathaneki"],
    "competitors": ["aathigathani"],
    "the poor": ["aathigona"],
    "poor people": ["aathigona"],
    "heirs": ["aathigululi"],
    "heiresses": ["aathigululi"],
    "inheritors": ["aathigululi"],
    "forcers": ["aathiminiki"],
    "escorts": ["aathindikili"],
    "the deaf": ["aathitawi"],
    "deaf people": ["aathitawi"],
    "whites": ["aatiligane", "aatokele"],
    "second": ["aatiyali"],
    "journalists": ["aatolinkundana", "aatoolinkundana"],
    "enemies": ["aatondi"],
    "establishers": ["aatoti", "aatotipo"],
    "lawmakers": ["aatotiveta"],
    "senders": ["aatumi"],
    "messengers": ["aatumwa"],
    "missionaries": ["aatumwa"],
    "builders": ["aatungi"],
    "bricklayers": ["aatungi"],
    "peacemakers": ["aatungimbili"],
    "vaccinated people": ["aatuntilwa"],
    "immunised people": ["aatuntilwa"],
    "immunized people": ["aatuntilwa"],
    "Ugandans": ["Aauganda"],
    "Northerners": ["Aaumbangalantu"],
    "natives": ["aavalelwamo"],
    "parents": ["aavali"],
    "obedient": ["aavuliki"],
    "Aawambo people": ["aawambo"],
    "they are nice": ["aawanawa"],
    "they are very nice": ["aawawawawa"],
    "church leaders": ["aawilikingerki"],
    "they are bad": ["aawinayi"],
    "no": ["aawoo"],
    "dreamers": ["aayagumi"],
    "stealers": ["aayakipo"],
    "grabbers": ["aayakuli"],
    "counters": ["aayaluli"],
    "enumerators": ["aayaluli"],
    "the rich": ["aayamba", "aazeko"],
    "fans": ["aayambidhidhi"],
    "responders": ["aayamukuli"],
    "apostles": ["aayapostoli"],
    "saints": ["aayapuki", "aayapukilela"],
    "no": ["aayee"],
    "the San": ["Aayelele"],
    "San people": ["Aayelele"],
    "travellers": ["aayendanandjila", "aayendi"],
    "travelers": ["aayendanandjila", "aayendinandjila", "aayendi"],
    "pedestrians": ["aayendilupadhi"],
    "angels": ["aayengeli"],
    "conductors": ["aayimbithi"],
    "fishermen": ["aayuli"],
    "preachers": ["aayuvithi"],
    "Zambians": ["Aazambia"],
    "Zimbabweans": ["Aazimbabwe"],
    "play": ["hiki", "dhana", "dhane", "dhaneni"],
    "plays": ["hiki"],
    "played": ["hiki", "dhana", "dhanwa", "dhanwe", "dhanenwa", "dhanenwe"],
    "celebrated": ["dhana", "dhanenwa", "dhanenwe", "dhanwa", "dhanwe"],
    "celebrate": ["dhana", "dhaneni"],
    "played for": ["dhanene"],
    "plays for": ["dhanene"],
    "find": ["adhe", "adheni"],
    "reach": ["adhe", "adheni", "gwanitha"],
    "reached": ["adhike", "adhike", "gwanitha"],
    "caught": ["adhelela", "adhikililwa", "hakela", "akelwa", "akukilwa"],
    "catch": ["adhelele", "hakela", "akele", "akukilwa"],
    "catches": ["adhelele"],
    "call": ["dhenge", "dhengele", "dhengela", "ithana", "dhengeni"],
    "calls": ["dhenge", "dhengele", "ithana"],
    "beat": ["dhenge", "dhengeni", "dhepagula"],
    "beaten": ["dhenge", "dhengwa", "dhengwe", "dhengagulwa"],
    "called": ["dhengelwa", "ithana", "ithanwa"],
    "beaten for": ["dhengelwa"],
    "defeated": ["dhengwa"],
    "trained for": ["dheulilwa"],
    "trained in": ["dheulilwa"],
    "noted": ["dhidhilika", "dhidhilike"],
    "to have noted": ["adhidhilikithe"],
    "all": [
        "adhihe",
        "adhishe",
        "adhihedhihe",
        "aihe",
        "ayihe",
        "ayiheyihe",
        "agehe",
        "agehegehe",
        "aguhe",
        "awuhe",
        "auhe",
        "ayehe",
    ],
    "every": ["adhihe", "adhishe", "adhihedhihe"],
    "only": [
        "adhike",
        "ageke",
        "aguke",
        "akeke",
        "akuke",
        "alike",
        "awike",
        "aluke",
        "amuke",
        "ashike",
        "atuke",
        "auke",
        "awuke",
        "ayeke",
        "ayike",
    ],
    "alone": ["adhike", "ageke", "aguke", "akeke", "amuke", "andike", "auke", "awuke"],
    "refused": ["dhiki oonyala mevi", "dhiki oonyala mevi", "dhika oonyala mevi"],
    "refuse": ["dhiki oonyala mevi", "dhiki oonyala mevi"],
    "refuses": ["dhiki oonyala mevi", "dhiki oonyala mevi"],
    "caught red-handed": ["adhikilila", "adhikililwa"],
    "caught _ red-handed": ["adhikilile", "adhikilila"],
    "thought": [
        "dhiladhila",
        "dhilaadhila",
        "dhilaadhile",
        "dhilaadhilwa",
        "dhiladhilwa",
    ],
    "realise": ["dhimbulula", "dhimbulule"],
    "recognise": ["dhimbulula", "dhimbululwa", "dhimbulule"],
    "realised": ["dhimbulula"],
    "recognised": ["dhimbulula", "dhimbululwa", "dhimbulule", "dhimbululwe"],
    "forgot": ["dhimbwa"],
    "shone for": ["adhimine"],
    "shined for": ["adhimine"],
    "forgiven": ["dhiminwe po", "dhiminwa po"],
    "made to shine": ["adhimitha"],
    "to make shine": ["adhimithe"],
    "to be made to shine": ["adhimithwa"],
    "killed": ["dhipaga", "dhipagwa", "adhipagwa"],
    "murdered": ["dhipaga", "dhipagwa", "adhipagwa"],
    "arrested": ["adhitikilwe", "adhitikwa", "dhitike", "dhitikwa", "dhitikwe"],
    "apprehended": ["adhitikilwe", "adhitikwa", "dhitike", "dhitikwa", "dhitikwe"],
    "brewers": ["aadhungi"],
    "harbour": ["edhilile"],
    "house": ["edhilile"],
    "walked": ["ende"],
    "like": ["fa"],
    "took _ to": ["faalela"],
    "take _ to": ["faalela"],
    "took _ along": ["faalela"],
    "take _ along": ["faalela"],
    "to take": ["fale"],
    "was taken": ["falwa"],
    "interpret": ["fatulula"],
    "interpreted": ["fatulula"],
    "explain": ["fatulula"],
    "explained": ["fatulula"],
    "suspected": ["fekelwa"],
    "Afghanistan": ["Afghanistan"],
    "Africa": ["Africa", "Afrika"],
    "lied": ["fundju"],
    "impressed": ["fuula"],
    "amazed": ["fuula"],
    "returned": ["galuka", "galukile"],
    "came back": ["agaluka", "agalukile"],
    "return": ["galukile"],
    "gave": ["gandja"],
    "give": ["gandje"],
    "get angry": ["geye"],
    "got angry": ["geye"],
    "rest": ["gondja"],
    "rested": ["gondja"],
    "save": ["gongela", "gongele"],
    "saved": ["gongela", "gongele"],
    "gather": ["gongela", "gongele"],
    "gathered": ["gongela", "gongele"],
    "paunafaalama": ["agricultural"],
    "paunamapya nuuniimuna": ["agricultural"],
    "uunamapya nuuniimuna": ["agriculture"],
    "uunafaalama": ["agriculture"],
    "August": ["Aguste"],
    "turn": ["gwanitha"],
    "turns": ["gwanitha"],
    "turned": ["gwanitha"],
    "cut": ["hahala"],
    "cuts": ["hahala"],
    "chop": ["hahala"],
    "chops": ["hahala"],
    "hack": ["hahala"],
    "hacks": ["hahala"],
    "hacked": ["hahala", "hahalwa"],
    "chopped": ["hahala", "hahalwa"],
    "claps": ["hakela"],
    "clap": ["hakela"],
    "clapped": ["hakela"],
    "want": ["hala"],
    "wants": ["hala"],
    "wanted": ["hala", "ale"],
    "surprised": ["haluthwa"],
    "frightened": ["haluthwa"],
    "startled": ["haluthwa"],
    "spit": ["hiile"],
    "spits": ["hiile"],
    "spat": ["hiile"],
    "whistle": ["hiki"],
    "whistles": ["hiki"],
    "whistled": ["hiki"],
    "sing": ["hiki"],
    "sings": ["hiki"],
    "sang": ["hiki"],
    "sung": ["hiki"],
    "elect": ["hogolola", "hogolole"],
    "elects": ["hogolola"],
    "elected": ["hogolola", "ahogololwa"],
    "choose": ["hogolola", "hogolole"],
    "chooses": ["hogolola"],
    "chose": ["hogolola", "ahogololwa"],
    "chosen": ["hogolola", "ahogololwa"],
    "select": ["hogolola", "hogolole"],
    "selects": ["hogolola"],
    "selected": ["hogolola", "ahogololwa"],
    "reelected": ["hogolululwe"],
    "re-elected": ["hogolululwe"],
    "married": ["hokanwa"],
    "state": ["hokolola"],
    "states": ["hokolola"],
    "stated": ["hokolola"],
    "narrate": ["hokolola"],
    "narrates": ["hokolola"],
    "narrated": ["hokolola"],
    "hide": ["holeka"],
    "hides": ["holeka"],
    "hid": ["holeka"],
    "hidden": ["holeka"],
    "conceal": ["holeka"],
    "conceals": ["holeka"],
    "concealed": ["holeka"],
    "appear": ["holoka", "holoke"],
    "appears": ["holoka"],
    "appeared": ["holoka"],
    "reveal": ["hololela"],
    "reveals": ["hololela"],
    "revealed": ["hololela", "hololwa"],
    "show": ["hololela"],
    "shows": ["hololela"],
    "showed": ["hololela", "hololwa"],
    "shown": ["hololela", "hololwa"],
    "end": ["hulepo", "hulile", "hulitha"],
    "ends": ["hulepo", "hulile", "hulitha"],
    "ended": ["hulile", "hulitha", "hulithila", "hulithila", "hulithile"],
    "stop": ["hulitha", "hulithila"],
    "stops": ["hulitha"],
    "stopped": ["hulitha"],
    "die": ["hulitha", "hulitha oondjenda"],
    "dies": ["hulitha", "hulitha oondjenda"],
    "died": ["hulitha", "hulitha oondjenda", "hulithila", "hulithile"],
    "dead": ["hulitha", "hulitha oondjenda"],
    "saved": ["hupithwa"],
    "rescued": ["hupithwa"],
    "whole": ["aihe", "ayiheyihe", "ayihe", "akehe", "alihe", "auhe", "awuhe"],
    "everything": ["aihe", "ayiheyihe", "ayihe", "ashiheshihe"],
    "will": ["aka"],
    "eventually": ["ka"],
    "to": ["ka"],
    "to": ["ka"],
    "suffer": ["ala"],
    "suffered": ["ala"],
    "crucify": ["alele"],
    "crucifies": ["alele"],
    "crucified": ["alele", "alela", "alelwa", "alelwe"],
    "have _ crucified": ["alelitha"],
    "heal": ["aludhe", "aludheni"],
    "healed": ["aludhwa", "aludhwe"],
    "always": ["aluhe", "aluheluhe"],
    "very sick": ["alukililwa"],
    "very ill": ["alukililwa"],
    "alcohol": ["alukoholi"],
    "ill": ["alukwa"],
    "sick": ["alukwa"],
    "hurt": ["alula", "alule"],
    "hurts": ["alula"],
    "shock": ["alula"],
    "shocks": ["alula"],
    "shocked": ["alula"],
    "almost": ["ambala"],
    "almost": ["ambala"],
    "ambassador": ["ambasada", "ambasanda"],
    "support": ["ambidhidheni"],
    "help": ["ambidhidheni"],
    "assist": ["ambidhidheni"],
    "ambulance": ["ambulansa"],
    "all of you": ["amuhe"],
    "secretary general": ["amushangandjayi"],
    "mend": ["andeke"],
    "mends": ["andeke"],
    "mended": ["andekwa"],
    "I": ["andi"],
    "shared": ["andjagakanekwa", "andjagakanithwa"],
    "spread": [
        "andjagakanekwa",
        "andjagakanithwa",
        "andjagakeneka",
        "andjaganeka",
        "andjaganeke",
        "andjagana",
        "andjalala",
    ],
    "share": ["andjagakeneka", "andjaganeka", "andjaganeke"],
    "wide": ["andjunuka"],
    "open": ["andjunuka"],
    "startle": ["andutha"],
    "startled": ["andutha"],
    "dried": ["aneka", "anekwa"],
    "dry": ["aneka"],
    "drying": ["aneke", "anekwe"],
    "weary of": ["angala", "angale"],
    "almost": ["angala"],
    "nearly": ["angala"],
    "be weary": ["angaleni"],
    "apparently": ["aniwa", "anuwa"],
    "allegedly": ["aniwa", "anuwa"],
    "therefore": ["ano"],
    "everywhere": ["apehe", "apehepehe"],
    "all over": ["apehepehe"],
    "April": ["Apiilili"],
    "pharmacy": ["aputeka", "aputiyeka"],
    "article": ["artikela"],
    "entire": ["ashihe", "ashiheshihe"],
    "but": ["ashike"],
    "elite": ["ashikeshalye"],
    "VIP": ["ashikeshalye"],
    "demean": ["shindula", "shundula"],
    "demeaned": ["shindula", "shundula"],
    "demeans": ["shindula", "shundula"],
    "athletic": ["ateletika"],
    "we are": ["atu"],
    "all of us": ["atuhe", "atuheni", "atuhetuhe", "atushe", "atusheni"],
    "both": ["adhihe", "adhishe", "ayehe"],
    "everyone": ["ayeheyehe"],
    "were": ["dha", "dhali"],
    "of": ["dha"],
    "not": ["dhaa"],
    "without": ["dhaa na", "dhaana"],
    "don't have": ["dhaa na", "dhaana"],
    "do not have": ["dhaa na", "dhaana"],
    "were found": ["dhaadhika"],
    "its": [
        "dhadho",
        "dhago",
        "dhagwo",
        "dhako",
        "dhalwo",
        "dhalyo",
        "dhasho",
        "dhayo",
    ],
    "snatch": ["dhakula"],
    "snatched": ["dhakula", "dhakulwa"],
    "whose": ["dhalye"],
    "stick": ["dhama", "dhame", "dhameni"],
    "stuck": ["dhama"],
    "make stuck": ["dhamithitha", "dhamithwa"],
    "made stuck": ["dhamithitha", "dhamithwa"],
    "lies": ["dhanakalindi", "dhiifundja"],
    "useless": ["dhanathangwa"],
    "my": ["dhandje"],
    "commemorate": ["dhane", "dhaneni"],
    "commemorates": ["dhane"],
    "commemorated": ["dhana", "dhanwa", "dhanwe", "dhanenwa", "dhanenwe"],
    "ladies": ["oontana dhanelende"],
    "play with": ["dhanena"],
    "played with": ["dhanena"],
    "play for": ["dhanena"],
    "played for": ["dhanena"],
    "plays with": ["dhanene"],
    "played with": ["dhanene", "dhaniwa"],
    "plays for": ["dhanene"],
    "played for": ["dhanene"],
    "replayed": ["dhanununa"],
    "their": ["dhawo"],
    "his": ["dhe"],
    "her": ["dhe"],
    "of glory": ["dheadhimo"],
    "of the name": ["dhedhina"],
    "tremble": ["dhekwete"],
    "shiver": ["dhekwete"],
    "beating one another": ["dhengathana", "dhengagulathana"],
    "assaulted": ["dhengagulwa", "dhengagulwe"],
    "call with": ["dhengitha"],
    "calls with": ["dhengitha"],
    "called with": ["dhengitha"],
    "beat with": ["dhengitha"],
    "beats with": ["dhengitha"],
    "have beaten": ["dhengithe"],
    "call again": ["dhengulula"],
    "called again": ["dhengulula"],
    "beat again": ["dhengulula"],
    "your": ["dheni"],
    "our": ["dhetu", "dhetweni"],
    "skilled": ["dheuka", "dheukika", "dhewukika"],
    "trained": ["dheuka", "dheulwa"],
    "train": ["dheula", "dhewula"],
    "well trained": ["dheulikika"],
    "train for": ["dheulileni"],
    "trained for": ["dheulilwa", "dheulwe", "dhewulilwa", "dhewulilwe"],
    "trained in": ["dheulilwa", "dheulwe", "dhewulilwe", "dhewulilwa"],
    "have come": ["dheya"],
    "note": ["dhidhilika"],
    "noted": ["dhidhilika", "dhidhilikwa", "dhidhilike", "dhindhilike"],
    "notes": ["dhidhilike", "dhindhilike"],
    "mark": ["dhidhilika", "dhidhilike", "dhindhilike"],
    "marked": ["dhidhilika", "dhidhilikwa"],
    "marks": ["dhidhilike", "dhindhilike"],
    "keep": ["dhiginine", "dhiginina", "dhiginineni"],
    "keeps": ["dhiginine", "dhiginina"],
    "kept": ["dhiginine", "dhiginina", "dhigininwe"],
    "make difficult": ["dhigupaleka"],
    "made difficult": ["dhigupaleka"],
    "makes difficult": ["dhigupaleke"],
    "fleece": ["dhiifufu"],
    "fake": ["dhiifundja"],
    "of charges": ["dhiifuta"],
    "of nations": ["dhiigwana"],
    "delay": ["dhikala", "dhikaleka"],
    "delays": ["dhikala"],
    "delayed": ["dhikala"],
    "form": ["dhike", "dhikeni", "dhiki"],
    "forms": ["dhike", "dhiki"],
    "formed": ["dhika", "dhike", "dhiki", "dhikwa"],
    "establish": ["dhike", "dhikeni", "dhiki"],
    "establishes": ["dhike", "dhiki"],
    "established": ["dhike", "dhika", "dhiki", "dhikwa"],
    "think": ["dhilaadhila", "dhiladhile", "dhiladhileni"],
    "thinks": ["dhilaadhila"],
    "think fast": ["dhiladhilila"],
    "thinks fast": ["dhiladhilile"],
    "think for": ["dhiladhilila", "dhiladhilile"],
    "thinks for": ["dhiladhilila", "dhiladhilile"],
    "gone": ["dhilongela"],
    "ago": ["dhilongela"],
    "other": ["dhilwe"],
    "make forget": ["dhimbitha"],
    "makes forget": ["dhimbitha"],
    "forgotten": ["dhimbiwa", "dhimbiwe"],
    "remembered": [
        "dhimbulikiwa",
        "dhimbulula",
        "dhimbulukile",
        "dhimbulukilwa",
        "dhimbulukiwa",
        "dhimbulukiwe",
    ],
    "remember": ["dhimbulule" "dhimbulukwe", "dhimbulukweni"],
    "remind": ["dhimbulukitha", "dhimbulukithe", "dhimbulutha", "dhimbuluthe"],
    "reminds": ["dhimbulukitha", "dhimbulutha"],
    "reminded": ["dhimbulukithwa", "dhimbulutha", "dhimbuluthwa"],
    "forget": ["dhimbwe", "dhimbweni"],
    "turn off": ["dhime", "dhimi"],
    "clear": ["dhime", "dhimi"],
    "delete": ["dhime", "dhimi"],
    "erase": ["dhime", "dhimi"],
    "turns off": ["dhimi"],
    "turned off": ["dhimwa", "dhimwe"],
    "cleared": ["dhimwa", "dhimwe"],
    "deleted": ["dhimwa", "dhimwe"],
    "erased": ["dhimwa", "dhimwe"],
    "clears": ["dhimi"],
    "deletes": ["dhimi"],
    "erases": ["dhimi"],
    "forgive each other": ["dhiminathaneni po"],
    "forgive one another": ["dhiminathaneni po"],
    "forgive one another": ["dhiminathanii po"],
    "forgive": ["dhimine po", "dhiminiipo"],
    "forgives": ["dhimine po"],
    "forgave": ["dhimine po"],
    "forgive me": ["dhiminii ndje po"],
    "some": ["dhimwe", "dhimwepo"],
    "only some": ["dhimwedhimwe"],
    "filter": ["dhinde", "dhindi"],
    "filters": ["dhindi"],
    "filtered": ["dhindi", "dhindwa", "dhindwe"],
    "well-filtered": ["dhindolekeka"],
    "well-distilled": ["dhindolekeka"],
    "despise": ["dhine", "dhini"],
    "despised": ["dhini", "dhinika", "dhinike", "dhiniwa"],
    "disrespected": ["dhini", "dhinika", "dhinike", "dhiniwa"],
    "disrespect": ["dhine", "dhini"],
    "roll": ["dhingile"],
    "rolls": ["dhingile"],
    "rolled": ["dhingile", "dhingilwa", "dhingilwe"],
    "wrap": ["dhingile"],
    "wraps": ["dhingile"],
    "wrapped": ["dhingile", "dhingilwa", "dhingilwe"],
    "surround": ["dhingilila", "dhingilile"],
    "surrounds": ["dhingilila", "dhingilile"],
    "surrounded": ["dhingilila", "dhingolokwa"],
    "go around": ["dhingoloke"],
    "make go around": ["dhingolokitha"],
    "unwrap": ["dhingulula"],
    "unwrapped": ["dhingulula"],
    "which": ["dhinipo"],
    "these": ["dhino"],
    "kill each other": ["dhipagathana"],
    "kill one another": ["dhipagathana"],
    "kill": ["dhipage"],
    "kill at": ["dhipagela", "dhipagele"],
    "murder at": ["dhipagela", "dhipagele"],
    "kill for": ["dhipagela", "dhipagele"],
    "murder at": ["dhipagela", "dhipagele"],
    "killed at": ["dhipagelwa", "dhipagelwe"],
    "killed for": ["dhipagelwa", "dhipagelwe"],
    "murdered at": ["dhipagelwa", "dhipagelwe"],
    "murdered for": ["dhipagelwa", "dhipagelwe"],
    "kill": ["dhipageni"],
    "murder": ["dhipageni"],
    "killed": ["dhipagwe"],
    "arrested at": ["dhitikilwa"],
    "released": ["dhitikululwa"],
    "untie": ["dhitula", "dhitule", "dhitululeni"],
    "untied": ["dhituluka"],
}
