difficult_words = {
    # "aadhiginini"],
    # "aadibon"],
    # "aadikla"],
    # "aaebal"],
    # "aaedom"],
    # "aaedomi"],
    # "aaefeso"],
    # "aaefraim"],
    # "aaelam"],
    # "aaelisha"],
    # "aaemim"],
    # "aaemimi"],
    # "aafarisayi"],
    # "aafilisti"],
    # "aafoinikia"],
    # "aafukalekwa"],
    # "aafukedhi"],
    # "aafutili"],
    # "aafutwa"],
    # "aagad"],
    # "aagalati"],
    # "aagalilea"],
    # "aagallim"],
    # "aagaza"],
    # "aageshuri"],
    # "aagibea"],
    # "aagibeon"],
    # "aagilead"],
    # "aagirgashi"],
    # "aagirzi"],
    # "aagoyoki"],
    # "aagoyokithi"],
    # "aagreka"],
    # "aahadoram"],
    # "aahagari"],
    # "aahavila"],
    # "aahazarmavet"],
    # "aahebeli"],
    # "aaheshboni"],
    # "aahetatu"],
    # "aahethi"],
    # "aaheti"],
    # "aahevi"],
    # "aahiki"],
    # "D" :["aaholland"],
    # "" :["aaholokepo"],
    # "" :["aahomoni"],
    # "" :["aahori"],
    # "" :["aahugunina"],
    # "" :["aahuni"],
    # "" :["aahupipo"],
    # "" :["aahutu"],
    # "" :["aahwepo"],
    # "" :["aaikuthimo"],
    # "" :["aaismaeli"],
    # "" :["aajabesh"],
    # "" :["aajaser"],
    # "" :["aajerak"],
    # "" :["aajeriko"],
    # "" :["aajerusalem"],
    # "" :["aajeter"],
    # "" :["aajuda"],
    # "" :["aakaanana"],
    # "" :["aakadhi"],
    # "" :["aakadhonalela"],
    # "" :["aakalalimo"],
    # "" :["aakalele"],
    # "" :["aakaleli"],
    # "" :["aakalekipo"],
    # "" :["aakaliko"],
    # "" :["aakanaan"],
    # "" :["aakandi"],
    # "" :["aakaslu"],
    # "" :["aakeni"],
    # "" :["aakenki"],
    # "" :["aakerubi"],
    # "" :["aakipro"],
    # "" :["aakolokohi"],
    # "": ["aakolokoshi"],
    # "" :["aakomangeli"],
    # "" :["aakondeki"],
    # "" :["aakoneki"],
    # "" :["aakothi"],
    # "" :["aakukutu"],
    # "" :["aakuli"],
    # "old" :["aakulu"],
    # "" :["aakulukulu"],
    # "" :["aakumiki"],
    # "" :["aakwaajani"],
    # # "" :["aakwaamagulu"],
    # "" :["aakwagerson"],
    # "" :["aakwagulu"],
    # "" :["aakwaham"],
    # "" :["aakwakehat"],
    # "" :["Aakwamanya"],
    # "" :["aakwamerari"],
    # "" :["aakwamuhoko"],
    # "" :["aakwanayuma"],
    # "" :["aakwanelumbi"],
    # "" :["aakwanepangelo"],
    # "" :["aakwanezi"],
    # "" :["aakwanezima"],
    # "" :["aakwankwa"],
    # "" :["aakwati"],
    # "" :["aakwaveta"],
    # "" :["aakweyi"],
    # "" :["aalaadhi"],
    # "" :["aalajesha"],
    # "" :["aalalekwa"],
    # "" :["aalali"],
    # "" :["aalangeli"],
    # "" :["aalefule"],
    # "" :["aalehab"],
    # "" :["aaletushi"],
    # "" :["aalevi"],
    # "" :["aalidia"],
    # "" :["aaloloki"],
    # "" :["aamadmena"],
    # "" :["aamakedonia"],
    # "" :["aamanako"],
    # "" :["aamanasse"],
    # "" :["aamar"],
    # "" :["aamasubia"],
    # "" :["aambanda"],
    # "" :["aamedia"],
    # "" :["aamidiana"],
    # "" :["aamix"],
    # "" :["aamoabi"],
    # "" :["aamutimahenda"],
    # "" :["aanaftali"],
    # "" :["aanaftu"],
    # "" :["aanaluhepo"],
    # "" :["aanalwiho"],
    # "" :["aanalwiimbo"],
    # "" :["aanamagongamwele"],
    # "" :["aanamakoto"],
    # "" :["aanamalaka"],
    # "" :["aanamaliko"],
    # "" :["aanamapangelo"],
    # "" :["aanamatati"],
    # "" :["aanamatatilela"],
    # "" :["aanamatembakwiita"],
    # "" :["aanamawudhano"],
    # "" :["aanampwidhuli"],
    # "" :["aanamutimahenda"],
    # "" :["aanankayi"],
    # "" :["aananyanya"],
    # "" :["aanapangelo"],
    # "" :["aanashihako"],
    # "" :["aanashihongelo"],
    # "" :["aanashikandjo"],
    # "" :["aanasikepa"],
    # "" :["aanasiri"],
    # "" :["aanatempeli"],
    # "" :["aanaveta"],
    # "" :["aanchen"],
    # "" :["aanezimo"],
    # "" :["aangandjawo"],
    # "" :["aangandjeni"],
    # "" :["aangandjetu"],
    # "" :["aangandjoye"],
    # "" :["aangoka"],
    # "" :["aaniihako"],
    # "" :["aaniikaha"],
    # "" :["aaniikandjo"],
    # "" :["aaniita"],
    # "": ["aaniimaliwa"],
    # "" :["aaninive"],
    # "" :["aanotelwa"],
    # "" :["aanuuntsa"],
    # "" :["aanuushimba"],
    # "" :["aanye"],
    # "" :["aanyu"],
    # "" :["aaofir"],
    # "" :["aapindi"],
    # "" :["aapitithi"],
    # "" :["aaponto"],
    # "" :["aapukithi"],
    # "" :["aaput"],
    # "" :["aapyokoki"],
    # "" :["aarafa"],
    # "" :["aaragma"],
    # "" :["aarekab"],
    # "" :["aareuben"],
    # "" :["aarifat"],
    # "" :["aarodos"],
    # "" :["aarohingya"],
    # "" :["aasaageli"],
    # "" :["aasaba"],
    # "" :["aasabta"],
    # "" :["aasadukayi"],
    # "" :["aasamsumi"],
    # "" :["aasapoti"],
    # "" :["aasarde"],
    # "" :["aaseba"],
    # "" :["aasebulon"],
    # "" :["aaserafi"],
    # "" :["aasheba"],
    # "" :["aashekedhi"],
    # "" :["aashekem"],
    # "" :["aashelef"],
    # "" :["aashimati"],
    # "" :["aashinga"],
    # "" :["aashumati"],
    # "" :["aashungu"],
    # "" :["aasibma"],
    # "" :["aasidoni"],
    # "" :["aasikem"],
    # "" :["aasima"],
    # "" :["aasithahoni"],
    # "" :["aasodomu"],
    # "" :["aasona"],
    # "Sudanese" :["Aasudani"],
    # "" :["aasuki"],
    # "" :["aasukkot"],
    # "" :["aasusi"],
    # "" :["aatalanteni"],
    # "" :["aatango"],
    # "" :["aawuliki"],
    # "" :["aateki"],
    # "" :["aatessalonika"],
    # "" :["aathayili"],
    # "" :["aathigwa"],
    # "" :["aathiminikwa"],
    # "" :["aathingo"],
    # "" :["aathingwa"],
    # "" :["aathiopia"],
    # "" :["aathonwantu"],
    # "" :["aati"],
    # "" :["aatidhagani"],
    # "" :["aatirati"],
    # "" :["aatiro"],
    # "" :["aatjimba"],
    # "" :["aatononi"],
    # "" :["aatsaangidhi"],
    # "" :["aatsi"],
    # "" :["aatulimo"],
    # "" :["aatutsi"],
    # "" :["aatyayi"],
    # "" :["aauliki yiipindi"],
    # "" :["aaunduli"],
    # "" :["aausal"],
    # "" :["aavale"],
    # "" :["aawagona"],
    # "" :["aayai"],
    # "" :["aayakulwa"],
    # "" :["aayalmodad"],
    # "" :["aayamaleki"],
    # "" :["aayambi"],
    # "" :["aayameleki"],
    # "" :["aayammoni"],
    # "" :["aayamori"],
    # "" :["aayanaki"],
    # "" :["aayanakim"],
    # "" :["aayanam"],
    # "" :["aayanatot"],
    # "" :["aayanekeli"],
    # "" :["aayarabi"],
    # "" :["aayarki"],
    # "" :["aayaser"],
    # "" :["aayashuri"],
    # "" :["aayassur"],
    # "" :["aayatena"],
    # "" :["aayavvim"],
    # "" :["aayebusi"],
    # "" :["aayeni"],
    # "" :["aayeti"],
    # "" :["aayindi"],
    # "" :["aayitedhululi"],
    # "" :["aayithanwa"],
    # "" :["aayogohi"],
    # "" :["aayogoki"],
    # "" :["aayonaguli"],
    # "" :["aayoni"],
    # "" :["aayugani"],
    # "" :["aayuzilo"],
    # "" :["adhiminwa"],
    # "" :["adhitha"],
    # "" :["afek"],
    # "" :["ahangununwa"],
    # "" :["akwetu"],
    # "" :["alaala"],
    # "" :["alaalithwa"],
    # "" :["alulitha"],
    # "" :["alusaati"],
    # "" :["aluusati"],
    # "" :["ambekwa"],
    # "" :["amushangampangu"],
    # "" :["anda"],
    # "" :["andalalithwa"],
    # "" :["andanithwa"],
    # "" :["andjaganekelwa"],
    # "" :["andjaganekelwe"],
    # "" :["andjaganekwa"],
    # "" :["andjaganekwe"],
    # "" :["andjaganitha"],
    # "" :["andjakana"],
    # "" :["andjakane"],
    # "" :["andjakaneka"],
    # "" :["andjakaneke"],
    # "" :["andjakanekwe"],
    # "" :["andjakanitha"],
    # "" :["andjaneka"],
    # "" :["andjaneke"],
    # "" :["andjanekwa"],
    # "" :["andjeneke"],
    # "" :["andjenekele"],
    # "" :["andyakaneka"],
    # "" :["anekela"],
    # "" :["anekele"],
    # "" :["anekelitha"],
    # "" :["angukununa"],
    # "" :["apeke"],
    # "" :["ashi"],
    # "" :["ayandjaganekwa"],
    # "" :["dhaadhigile"],
    # "" :["dhaahoka"],
    # "" : dhahe, dhahekulu
    # "" :["dhamo"],
    # "" :["dhamuka"],
    # "" :["dhanakapipi"],
    # "" :["dhandhenga"], dhenga mbanda
    # construction for dhaNOUN and dheNOUN
    # "" :["dhene"],
    # "" :["dhenedhene"],
    # "" :["dhi"],
    # "" :["dhigininitha"],
    # "" :["dhigininwa"],
    # "" :["dhiidhila"],
    # "" :["dhiifudhitho"],
    # "" :["dhiifudho"],
    # "" :["dhiihape"],
    # "of " :["dhiihauto"],
    # "" :["dhiihokolola"],
    # "" :["dhiihumbatitho"],
    # "" :["dhiihupe"],
    # "" :["dhiihwa"],
    # "" :["dhiihwapo"],
    # "" :["dhiikalunga"],
    # "" :["dhiikandjohogololo"],
    # "" :["dhiikolitha"],
    # "" :["dhiikolokosha"],
    # "" :["dhiikombo"],
    # "" :["dhiikondo"],
    # "" :["dhiikuilya"],
    # "" :["dhiikulya"],
    # "" :["dhiikundaneki"],
    # "" :["dhiikunino"],
    # "" :["dhiikunuwa"],
    # "" :["dhiikushu"],
    # "" :["dhiikutu"],
    # "" :["dhiikwamahina"],
    # "" :["dhiikwamahini"],
    # "" :["dhiikwamahooli"],
    # "" :["dhiikwamalusheno"],
    # "" :["dhiikwamboga"],
    # "" :["dhiikwameni"],
    # "" :["dhiikwaniipangitho"],
    # "" :["dhiikwatelela"],
    # "" :["dhiikwatenda"],
    # "" :["dhiikwiila"],
    # "" :["dhiilalo"],
    # "" :["dhiilando"],
    # "" :["dhiili"],
    # "" :["dhiilonga"],
    # "" :["dhiilongashikongo"],
    # "" :["dhiilongela"],
    # "" :["dhiilongo"],
    # "" :["dhiilongomwa"],
    # "" :["dhiilongwa"],
    # "" :["dhiilya"],
    # "" :["dhiimaliwa"],
    # "" :["dhiimbuluma"],
    # "" :["dhiimenka"],
    # "" :["dhiimeno"],
    # "" :["dhiimuna"],
    # "" :["dhiinamwenyo"],
    # "" :["dhiingangamithi"],
    # "" :["dhiingoli"],
    # "" :["dhiinima"],
    # "" :["dhiiningwanima"],
    # "" :["dhiinonoma"],
    # "" :["dhiinyanyu"],
    # "" :["dhiipa"],
    # "" :["dhiipakete"],
    # "" :["dhiipangelo"],
    # "" :["dhiipeleki"],
    # "" :["dhiipilangi"],
    # "" :["dhiipolopolo"],
    # "" :["dhiiponga"],
    # "" :["dhiipundi"],
    # "" :["dhiipundiiheyali"],
    # "" :["dhiiputudhilo"],
    # "" :["dhiishangitha"],
    # "" :["dhiishokelya"],
    # "" :["dhiita"],
    # "" :["dhiitenda"],
    # "" :["dhiithikamena"],
    # "" :["dhiitopolwa"],
    # "" :["dhiitula"],
    # "" :["dhiitungitho"],
    # "" :["dhiiyagaya"],
    # "" :["dhiiyala"],
    # "" :["dhiiyamakuti"],
    # "" :["dhiiyambelo"],
    # "" :["dhiiyata"],
    # "" :["dhiiyela"],
    # "" :["dhiiyelekela"],
    # "" :["dhiiyelo"],
    # "" :["dhiiyemo"],
    # "" :["dhiiyimati"],
    # "" :["dhiizalomwa"],
    # "" :["dhiizemo"],
    # "" :["dhiizimba"],
    # "" :["dhikila"],
    # "" :["dhikile"],
    # "" :["dhikilwa"],
    # "" :["dhikilwe"],
    # "" :["dhikitha"],
    # "" :["dhikithile"],
    # "" :["dhikule"],
    # "" :["dhikulula"],
    # "" :["dhikulwa"],
    # "" :["dhikulwe"],
    # "" :["dhiladhililathana"],
    # "" :["dhiladhililwa"],
    # "" :["dhiladhilitha"],
    # "" :["dhilagula"],
    # "" :["dhili"],
    # "" :["dhilikilwa"],
    # "" :["dhilukitha"],
    # "" :["dhilukitheni"],
    # "" :["dhilukithilwa"],
    # "" :["dhimitha"],
    # "" :["dhimuka"],
    # "" :["dhimuna"],
    # "" :["dhingwa"],
    # "" :["dhinitha"],
    # "" :["dhipagelele"],
    # "" :["dhipagii"],
    # "" :["dhipagitha"],
    # "" :["dhipagithe"],
    # "" :["dhipagithila"],
    # "" :["dhipagithile"],
    # "" :["dhipagithwa"],
    # "" :["dhitikithe"],
    # "" :["dhituka"],
    # "" :["dhiya"],
    # "" :["dhiye"],
    "": ["dhuugoyoki"],
    "": ["dhuukonakoni"],
    "": ["dhuukumwe"],
    "": ["dhuulenga"],
    "": ["dhuumpulile"],
    "": ["dhuundhulumutu"],
    "": ["dhuundjendi"],
    "": ["dhuuntsa"],
    "": ["dhuunyekadhi"],
    "": ["dhuusita"],
    "": ["edhilileni"],
    "": ["edhililitha"],
    "": ["edhililwe"],
    "": ["edhilitha"],
    "": ["edhilwa"],
    "": ["edhilwe"],
    "": ["eendunge"],
    "": ["efundjaleko"],
    "": ["egombe"],
    "": ["egwanitho"],
    "": ["ehalakano"],
    "": ["ehambulo"],
    "": ["ehanganokwatheli"],
}
