difficult_words = {
    # "aadhiginini"],
    # "aadibon"],
    # "aadikla"],
    # "aaebal"],
    # "aaedom"],
    # "aaedomi"],
    # "aaefeso"],
    # "aaefraim"],
    # "aaelam"],
    # "aaelisha"],
    # "aaemim"],
    # "aaemimi"],
    # "aafarisayi"],
    # "aafilisti"],
    # "aafoinikia"],
    # "aafukalekwa"],
    # "aafukedhi"],
    # "aafutili"],
    # "aafutwa"],
    # "aagad"],
    # "aagalati"],
    # "aagalilea"],
    # "aagallim"],
    # "aagaza"],
    # "aageshuri"],
    # "aagibea"],
    # "aagibeon"],
    # "aagilead"],
    # "aagirgashi"],
    # "aagirzi"],
    # "aagoyoki"],
    # "aagoyokithi"],
    # "aagreka"],
    # "aahadoram"],
    # "aahagari"],
    # "aahavila"],
    # "aahazarmavet"],
    # "aahebeli"],
    # "aaheshboni"],
    # "aahetatu"],
    # "aahethi"],
    # "aaheti"],
    # "aahevi"],
    # "aahiki"],
    # "D" :["aaholland"],
    # "" :["aaholokepo"],
    # "" :["aahomoni"],
    # "" :["aahori"],
    # "" :["aahugunina"],
    # "" :["aahuni"],
    # "" :["aahupipo"],
    # "" :["aahutu"],
    # "" :["aahwepo"],
    # "" :["aaikuthimo"],
    # "" :["aaismaeli"],
    # "" :["aajabesh"],
    # "" :["aajaser"],
    # "" :["aajerak"],
    # "" :["aajeriko"],
    # "" :["aajerusalem"],
    # "" :["aajeter"],
    # "" :["aajuda"],
    # "" :["aakaanana"],
    # "" :["aakadhi"],
    # "" :["aakadhonalela"],
    # "" :["aakalalimo"],
    # "" :["aakalele"],
    # "" :["aakaleli"],
    # "" :["aakalekipo"],
    # "" :["aakaliko"],
    # "" :["aakanaan"],
    # "" :["aakandi"],
    # "" :["aakaslu"],
    # "" :["aakeni"],
    # "" :["aakenki"],
    # "" :["aakerubi"],
    # "" :["aakipro"],
    # "" :["aakolokohi"],
    # "": ["aakolokoshi"],
    # "" :["aakomangeli"],
    # "" :["aakondeki"],
    # "" :["aakoneki"],
    # "" :["aakothi"],
    # "" :["aakukutu"],
    # "" :["aakuli"],
    # "old" :["aakulu"],
    # "" :["aakulukulu"],
    # "" :["aakumiki"],
    # "" :["aakwaajani"],
    # # "" :["aakwaamagulu"],
    # "" :["aakwagerson"],
    # "" :["aakwagulu"],
    # "" :["aakwaham"],
    # "" :["aakwakehat"],
    # "" :["Aakwamanya"],
    # "" :["aakwamerari"],
    # "" :["aakwamuhoko"],
    # "" :["aakwanayuma"],
    # "" :["aakwanelumbi"],
    # "" :["aakwanepangelo"],
    # "" :["aakwanezi"],
    # "" :["aakwanezima"],
    # "" :["aakwankwa"],
    # "" :["aakwati"],
    # "" :["aakwaveta"],
    # "" :["aakweyi"],
    # "" :["aalaadhi"],
    # "" :["aalajesha"],
    # "" :["aalalekwa"],
    # "" :["aalali"],
    # "" :["aalangeli"],
    # "" :["aalefule"],
    # "" :["aalehab"],
    # "" :["aaletushi"],
    # "" :["aalevi"],
    # "" :["aalidia"],
    # "" :["aaloloki"],
    # "" :["aamadmena"],
    # "" :["aamakedonia"],
    # "" :["aamanako"],
    # "" :["aamanasse"],
    # "" :["aamar"],
    # "" :["aamasubia"],
    # "" :["aambanda"],
    # "" :["aamedia"],
    # "" :["aamidiana"],
    # "" :["aamix"],
    # "" :["aamoabi"],
    # "" :["aamutimahenda"],
    # "" :["aanaftali"],
    # "" :["aanaftu"],
    # "" :["aanaluhepo"],
    # "" :["aanalwiho"],
    # "" :["aanalwiimbo"],
    # "" :["aanamagongamwele"],
    # "" :["aanamakoto"],
    # "" :["aanamalaka"],
    # "" :["aanamaliko"],
    # "" :["aanamapangelo"],
    # "" :["aanamatati"],
    # "" :["aanamatatilela"],
    # "" :["aanamatembakwiita"],
    # "" :["aanamawudhano"],
    # "" :["aanampwidhuli"],
    # "" :["aanamutimahenda"],
    # "" :["aanankayi"],
    # "" :["aananyanya"],
    # "" :["aanapangelo"],
    # "" :["aanashihako"],
    # "" :["aanashihongelo"],
    # "" :["aanashikandjo"],
    # "" :["aanasikepa"],
    # "" :["aanasiri"],
    # "" :["aanatempeli"],
    # "" :["aanaveta"],
    # "" :["aanchen"],
    # "" :["aanezimo"],
    # "" :["aangandjawo"],
    # "" :["aangandjeni"],
    # "" :["aangandjetu"],
    # "" :["aangandjoye"],
    # "" :["aangoka"],
    # "" :["aaniihako"],
    # "" :["aaniikaha"],
    # "" :["aaniikandjo"],
    # "" :["aaniita"],
    # "": ["aaniimaliwa"],
    # "" :["aaninive"],
    # "" :["aanotelwa"],
    # "" :["aanuuntsa"],
    # "" :["aanuushimba"],
    # "" :["aanye"],
    # "" :["aanyu"],
    # "" :["aaofir"],
    # "" :["aapindi"],
    # "" :["aapitithi"],
    # "" :["aaponto"],
    # "" :["aapukithi"],
    # "" :["aaput"],
    # "" :["aapyokoki"],
    # "" :["aarafa"],
    # "" :["aaragma"],
    # "" :["aarekab"],
    # "" :["aareuben"],
    # "" :["aarifat"],
    # "" :["aarodos"],
    # "" :["aarohingya"],
    # "" :["aasaageli"],
    # "" :["aasaba"],
    # "" :["aasabta"],
    # "" :["aasadukayi"],
    # "" :["aasamsumi"],
    # "" :["aasapoti"],
    # "" :["aasarde"],
    # "" :["aaseba"],
    # "" :["aasebulon"],
    # "" :["aaserafi"],
    # "" :["aasheba"],
    # "" :["aashekedhi"],
    # "" :["aashekem"],
    # "" :["aashelef"],
    # "" :["aashimati"],
    # "" :["aashinga"],
    # "" :["aashumati"],
    # "" :["aashungu"],
    # "" :["aasibma"],
    # "" :["aasidoni"],
    # "" :["aasikem"],
    # "" :["aasima"],
    # "" :["aasithahoni"],
    # "" :["aasodomu"],
    # "" :["aasona"],
    # "Sudanese" :["Aasudani"],
    # "" :["aasuki"],
    # "" :["aasukkot"],
    # "" :["aasusi"],
    # "" :["aatalanteni"],
    # "" :["aatango"],
    # "" :["aawuliki"],
    # "" :["aateki"],
    # "" :["aatessalonika"],
    # "" :["aathayili"],
    # "" :["aathigwa"],
    # "" :["aathiminikwa"],
    # "" :["aathingo"],
    # "" :["aathingwa"],
    # "" :["aathiopia"],
    # "" :["aathonwantu"],
    # "" :["aati"],
    # "" :["aatidhagani"],
    # "" :["aatirati"],
    # "" :["aatiro"],
    # "" :["aatjimba"],
    # "" :["aatononi"],
    # "" :["aatsaangidhi"],
    # "" :["aatsi"],
    # "" :["aatulimo"],
    # "" :["aatutsi"],
    # "" :["aatyayi"],
    # "" :["aauliki yiipindi"],
    # "" :["aaunduli"],
    # "" :["aausal"],
    # "" :["aavale"],
    # "" :["aawagona"],
    # "" :["aayai"],
    # "" :["aayakulwa"],
    # "" :["aayalmodad"],
    # "" :["aayamaleki"],
    # "" :["aayambi"],
    # "" :["aayameleki"],
    # "" :["aayammoni"],
    # "" :["aayamori"],
    # "" :["aayanaki"],
    # "" :["aayanakim"],
    # "" :["aayanam"],
    # "" :["aayanatot"],
    # "" :["aayanekeli"],
    # "" :["aayarabi"],
    # "" :["aayarki"],
    # "" :["aayaser"],
    # "" :["aayashuri"],
    # "" :["aayassur"],
    # "" :["aayatena"],
    # "" :["aayavvim"],
    # "" :["aayebusi"],
    # "" :["aayeni"],
    # "" :["aayeti"],
    # "" :["aayindi"],
    # "" :["aayitedhululi"],
    # "" :["aayithanwa"],
    # "" :["aayogohi"],
    # "" :["aayogoki"],
    # "" :["aayonaguli"],
    # "" :["aayoni"],
    # "" :["aayugani"],
    # "" :["aayuzilo"],
    # "" :["adhiminwa"],
    # "" :["adhitha"],
    # "" :["afek"],
    # "" :["ahangununwa"],
    # "" :["akwetu"],
    # "" :["alaala"],
    # "" :["alaalithwa"],
    # "" :["alulitha"],
    # "" :["alusaati"],
    # "" :["aluusati"],
    # "" :["ambekwa"],
    # "" :["amushangampangu"],
    # "" :["anda"],
    # "" :["andalalithwa"],
    # "" :["andanithwa"],
    # "" :["andjaganekelwa"],
    # "" :["andjaganekelwe"],
    # "" :["andjaganekwa"],
    # "" :["andjaganekwe"],
    # "" :["andjaganitha"],
    # "" :["andjakana"],
    # "" :["andjakane"],
    # "" :["andjakaneka"],
    # "" :["andjakaneke"],
    # "" :["andjakanekwe"],
    # "" :["andjakanitha"],
    # "" :["andjaneka"],
    # "" :["andjaneke"],
    # "" :["andjanekwa"],
    # "" :["andjeneke"],
    # "" :["andjenekele"],
    # "" :["andyakaneka"],
    # "" :["anekela"],
    # "" :["anekele"],
    # "" :["anekelitha"],
    # "" :["angukununa"],
    # "" :["apeke"],
    # "" :["ashi"],
    # "" :["ayandjaganekwa"],
    # "" :["dhaadhigile"],
    # "" :["dhaahoka"],
    # "" : dhahe, dhahekulu
    # "" :["dhamo"],
    # "" :["dhamuka"],
    # "" :["dhanakapipi"],
    # "" :["dhandhenga"], dhenga mbanda
    # construction for dhaNOUN and dheNOUN
    # "" :["dhene"],
    # "" :["dhenedhene"],
    # "" :["dhi"],
    # "" :["dhigininitha"],
    # "" :["dhigininwa"],
    # "" :["dhiidhila"],
    # "" :["dhiifudhitho"],
    # "" :["dhiifudho"],
    # "" :["dhiihape"],
    # "of " :["dhiihauto"],
    # "" :["dhiihokolola"],
    # "" :["dhiihumbatitho"],
    # "" :["dhiihupe"],
    # "" :["dhiihwa"],
    # "" :["dhiihwapo"],
    # "" :["dhiikalunga"],
    # "" :["dhiikandjohogololo"],
    # "" :["dhiikolitha"],
    # "" :["dhiikolokosha"],
    # "" :["dhiikombo"],
    # "" :["dhiikondo"],
    # "" :["dhiikuilya"],
    # "" :["dhiikulya"],
    # "" :["dhiikundaneki"],
    # "" :["dhiikunino"],
    # "" :["dhiikunuwa"],
    # "" :["dhiikushu"],
    # "" :["dhiikutu"],
    # "" :["dhiikwamahina"],
    # "" :["dhiikwamahini"],
    # "" :["dhiikwamahooli"],
    # "" :["dhiikwamalusheno"],
    # "" :["dhiikwamboga"],
    # "" :["dhiikwameni"],
    # "" :["dhiikwaniipangitho"],
    # "" :["dhiikwatelela"],
    # "" :["dhiikwatenda"],
    # "" :["dhiikwiila"],
    # "" :["dhiilalo"],
    # "" :["dhiilando"],
    # "" :["dhiili"],
    # "" :["dhiilonga"],
    # "" :["dhiilongashikongo"],
    # "" :["dhiilongela"],
    # "" :["dhiilongo"],
    # "" :["dhiilongomwa"],
    # "" :["dhiilongwa"],
    # "" :["dhiilya"],
    # "" :["dhiimaliwa"],
    # "" :["dhiimbuluma"],
    # "" :["dhiimenka"],
    # "" :["dhiimeno"],
    # "" :["dhiimuna"],
    # "" :["dhiinamwenyo"],
    # "" :["dhiingangamithi"],
    # "" :["dhiingoli"],
    # "" :["dhiinima"],
    # "" :["dhiiningwanima"],
    # "" :["dhiinonoma"],
    # "" :["dhiinyanyu"],
    # "" :["dhiipa"],
    # "" :["dhiipakete"],
    # "" :["dhiipangelo"],
    # "" :["dhiipeleki"],
    # "" :["dhiipilangi"],
    # "" :["dhiipolopolo"],
    # "" :["dhiiponga"],
    # "" :["dhiipundi"],
    # "" :["dhiipundiiheyali"],
    # "" :["dhiiputudhilo"],
    # "" :["dhiishangitha"],
    # "" :["dhiishokelya"],
    # "" :["dhiita"],
    # "" :["dhiitenda"],
    # "" :["dhiithikamena"],
    # "" :["dhiitopolwa"],
    # "" :["dhiitula"],
    # "" :["dhiitungitho"],
    # "" :["dhiiyagaya"],
    # "" :["dhiiyala"],
    # "" :["dhiiyamakuti"],
    # "" :["dhiiyambelo"],
    # "" :["dhiiyata"],
    # "" :["dhiiyela"],
    # "" :["dhiiyelekela"],
    # "" :["dhiiyelo"],
    # "" :["dhiiyemo"],
    # "" :["dhiiyimati"],
    # "" :["dhiizalomwa"],
    # "" :["dhiizemo"],
    # "" :["dhiizimba"],
    # "" :["dhikila"],
    # "" :["dhikile"],
    # "" :["dhikilwa"],
    # "" :["dhikilwe"],
    # "" :["dhikitha"],
    # "" :["dhikithile"],
    # "" :["dhikule"],
    # "" :["dhikulula"],
    # "" :["dhikulwa"],
    # "" :["dhikulwe"],
    # "" :["dhiladhililathana"],
    # "" :["dhiladhililwa"],
    # "" :["dhiladhilitha"],
    # "" :["dhilagula"],
    # "" :["dhili"],
    # "" :["dhilikilwa"],
    # "" :["dhilukitha"],
    # "" :["dhilukitheni"],
    # "" :["dhilukithilwa"],
    # "" :["dhimitha"],
    # "" :["dhimuka"],
    # "" :["dhimuna"],
    # "" :["dhingwa"],
    # "" :["dhinitha"],
    # "" :["dhipagelele"],
    # "" :["dhipagii"],
    # "" :["dhipagitha"],
    # "" :["dhipagithe"],
    # "" :["dhipagithila"],
    # "" :["dhipagithile"],
    # "" :["dhipagithwa"],
    # "" :["dhitikithe"],
    # "" :["dhituka"],
    # "" :["dhiya"],
    # "" :["dhiye"],
    "": ["dhuugoyoki"],
    "": ["dhuukonakoni"],
    "": ["dhuukumwe"],
    "": ["dhuulenga"],
    "": ["dhuumpulile"],
    "": ["dhuundhulumutu"],
    "": ["dhuundjendi"],
    "": ["dhuuntsa"],
    "": ["dhuunyekadhi"],
    "": ["dhuusita"],
    "": ["edhilileni"],
    "": ["edhililitha"],
    "": ["edhililwe"],
    "": ["edhilitha"],
    "": ["edhilwa"],
    "": ["edhilwe"],
    "": ["eendunge"],
    "": ["efundjaleko"],
    "": ["egombe"],
    "": ["egwanitho"],
    "": ["ehalakano"],
    "": ["ehambulo"],
    "": ["ehanganokwatheli"],
    "": ["ehukulalakano"],
    "": ["ehungaelo"],
    "": ["ehunga"],
    "": ["ehungo"],
    "": ["ehwahwamekohungi"],
    "": ["ehwamo"],
    "": ["eigandjo"],
    "": ["eihepeko"],
    "": ["eiholeko"],
    "": ["eihupulo"],
    "": ["eikakankamekelo"],
    "": ["eikalekelwo"],
    "": ["eikankamekelo"],
    "": ["eikutho"],
    "": ["eikwato"],
    "": ["eikwatonawa"],
    "": ["eikwatopomutima"],
    "": ["einekelomwene"],
    "": ["eipyakidhilo"],
    "": ["eisiikilo"],
    "": ["eiteko"],
    "": ["eitheto"],
    "": ["eitumbo"],
    "": ["eiuvito"],
    "": ["eiyapulo"],
    "": ["eiyopaleko"],
    "": ["ekaka"],
    "": ["ekandanga"],
    "": ["ekehuko"],
    "": ["ekelela"],
    "": ["ekolo"],
    "": ["ekolokoto"],
    "": ["ekwatakanithi"],
    "": ["elundalalo"],
    "": ["elunduko"],
    "": ["elyalyakaneko"],
    "": ["elyambala"],
    "": ["embompango"],
    "": ["embulukuto"],
    "": ["embweengo"],
    "": ["embwinda"],
    "": ["eminikilo"],
    "": ["emonitho"],
    "": ["emono"],
    "": ["enawapalo"],
    "": ["enayipalo"],
    "": ["endekela"],
    "": ["endekele"],
    "": ["endela"],
    "": ["endele"],
    "": ["endikinongeki"],
    "": ["enkono"],
    "": ["enkulutumba"],
    "": ["entamena"],
    "": ["entamene"],
    "": ["eopalo"],
    "": ["epona"],
    "": ["epwanga"],
    "": ["eshigo"],
    "": ["eshigolapi"],
    "": ["eshundulo"],
    "": ["etangakwiita"],
    "": ["etangalalo"],
    "": ["etetoko"],
    "": ["etetopo"],
    "": ["etetulo"],
    "": ["ethathana"],
    "": ["etidhaatiho"],
    "": ["etidhagano"],
    "": ["etidhomo"],
    "": ["etopagulo"],
    "": ["etopoluuthiga"],
    "": ["etsali"],
    "": ["etukauko"],
    "": ["etuwalalo"],
    "": ["eukililo"],
    "": ["euma"],
    "": ["euvithoko"],
    "": ["euvithonayi"],
    "": ["ewalanda"],
    "": ["eyakeloko"],
    "": ["eyeleko"],
    "": ["eyelo"],
    "": ["eyikwatopomitima"],
    "": ["eyikwatopomutima"],
    "": ["eyopamwe"],
    "": ["ezalo"],
    "": ["ezepo"],
    "": ["fatulile"],
    "": ["fatulilwa"],
    "": ["fatulule"],
    "": ["fatululile"],
    "": ["fatululilwa"],
    "": ["fatululilwe"],
    "": ["fatululwe"],
    "": ["fegulwa"],
    "": ["fendelitha"],
    "": ["fendelithwa"],
    "": ["fendelwa"],
    "": ["filala"],
    "": ["file"],
    "": ["filepo"],
    "": ["filila"],
    "": ["filile"],
    "": ["filwa"],
    "": ["fufila"],
    "": ["fukala"],
    "": ["fukaleka"],
    "": ["fukaleke"],
    "": ["fukalekitha"],
    "": ["fukalekithe"],
    "": ["fukalekitheni"],
    "": ["fukalekwa"],
    "": ["fukalekwe"],
    "": ["fulika"],
    "": ["fulikwa"],
    "": ["fulila"],
    "": ["fulile"],
    "": ["fulukile"],
    "": ["fulula"],
    "": ["fululukile"],
    "": ["fumbuka"],
    "": ["fumbululwe"],
    "": ["fumbulwe"],
    "": ["fumikwa"],
    "": ["fundula"],
    "": ["fundule"],
    "": ["fundulwa"],
    "": ["fungafunga"],
    "": ["galukilwa"],
    "": ["galukilwe"],
    "": ["galulako"],
    "": ["galule"],
    "": ["gameka"],
    "": ["gameke"],
    "": ["gameni"],
    "": ["gandjeleni"],
    "": ["gandjelwe"],
    "": ["gandjulula"],
    "": ["ganekele"],
    "": ["ganekwa"],
    "": ["ganenathana"],
    "": ["ganenwa"],
    "": ["gealuko"],
    "": ["geelela"],
    "": ["geelele"],
    "": ["geelelwa"],
    "": ["geelitha"],
    "": ["hadhela"],
    "": ["hadhele"],
    "": ["hadhiyi"],
    "": ["hadhwa"],
    "": ["hadhwe"],
    "": ["halakanena"],
    "": ["halakanene"],
    "": ["halakanitha"],
    "": ["halakanithapo"],
    "": ["halakanithe"],
    "": ["halakanitheni"],
    "": ["halakanithila"],
    "": ["halakanithile"],
    "": ["halakanithilwa"],
    "": ["halakanithwa"],
    "": ["halukitha"],
    "": ["halukwa"],
    "": ["halulwa"],
    "": ["halumwe"],
    "": ["halundji"],
    "": ["haluthe"],
    "": ["haluthile"],
    "": ["haluthitha"],
    "": ["haluthwa"],
    "": ["haluthwe"],
    "": ["halwo"],
    "": ["hambelele"],
    "": ["hambeleleni"],
    "": ["hambelelitha"],
    "": ["hambelelwa"],
    "": ["hambelelwe"],
    "": ["hambuleni"],
    "": ["hambulikika"],
    "": ["hambulila"],
    "": ["hambulile"],
    "": ["hambulilwa"],
    "": ["hambulilwe"],
    "": ["hambulitha"],
    "": ["hambulithila"],
    "": ["hambulithile"],
    "": ["hambulithilwa"],
    "": ["hambulithilwe"],
    "": ["hambulithitha"],
    "": ["hambulwa"],
    "": ["hali"],
    "": ["halika"],
    "": ["hamu"],
    "": ["hapa"],
    "": ["hapo"],
    "": ["hapu"],
    "": ["hapuka"],
    "": ["hawo"],
    "": ["hawu"],
    "": ["hawunene"],
    "": ["hedheni"],
    "": ["hedhi"],
    "": ["hedhitha"],
    "": ["hehelwa"],
    "": ["heke"],
    "": ["hekele"],
    "": ["hekelemo"],
    "": ["hekelwa"],
    "": ["hekuka"],
    "": ["hepekitha"],
    "": ["hepuluka"],
    "": ["hepulutha"],
    "": ["hepuluthila"],
    "": ["hewu"],
    "": ["heya"],
    "": ["heyi"],
    "": ["hilathana"],
    "": ["hindi"],
    "": ["hindwa"],
    "": ["hingila"],
    "": ["hingilathana"],
    "": ["hingile"],
    "": ["hiti"],
    "": ["hogololitha"],
    "": ["hogololithe"],
    "": ["hogolulule"],
    "": ["hogolululwa"],
    "": ["hogolululwe"],
    "": ["hokanenwe"],
    "": ["hokanitheni"],
    "": ["hokololelathana"],
    "": ["hokololelathaneni"],
    "": ["hololela"],
    "": ["hololele"],
    "": ["hololelwa"],
    "": ["homatekeka"],
    "": ["homone"],
    "": ["homoneni"],
    "": ["homonoka"],
    "": ["homonona"],
    "": ["hondelitha"],
    "": ["hondelwa"],
    "": ["hondjela"],
    "": ["hondjele"],
    "": ["hondjelwa"],
    "": ["hondjitha"],
    "": ["hongwa"],
    "": ["hotekwa"],
    "": ["hugila"],
    "": ["hugile"],
    "": ["hugileni"],
    "": ["hugilwa"],
    "": ["hugunine"],
    "": ["hugununi"],
    "": ["huhulukwa"],
    "": ["huhulukwe"],
    "": ["huhuwala"],
    "": ["hulu"],
    "": ["humbatelwa"],
    "": ["humbatitha"],
    "": ["humbatithwa"],
    "": ["humitha"],
    "": ["hunganekela"],
    "": ["hunganekele"],
    "": ["hunganekitha"],
    "": ["hupula"],
    "": ["hupulile"],
    "": ["hupulitha"],
    "": ["hupulula"],
    "": ["hupulutha"],
    "": ["hupuluthe"],
    "": ["hupuluthwa"],
    "": ["hwameni"],
}
