difficult_words = {
    # "aadhiginini"],
    # "aadibon"],
    # "aadikla"],
    # "aaebal"],
    # "aaedom"],
    # "aaedomi"],
    # "aaefeso"],
    # "aaefraim"],
    # "aaelam"],
    # "aaelisha"],
    # "aaemim"],
    # "aaemimi"],
    # "aafarisayi"],
    # "aafilisti"],
    # "aafoinikia"],
    # "aafukalekwa"],
    # "aafukedhi"],
    # "aafutili"],
    # "aafutwa"],
    # "aagad"],
    # "aagalati"],
    # "aagalilea"],
    # "aagallim"],
    # "aagaza"],
    # "aageshuri"],
    # "aagibea"],
    # "aagibeon"],
    # "aagilead"],
    # "aagirgashi"],
    # "aagirzi"],
    # "aagoyoki"],
    # "aagoyokithi"],
    # "aagreka"],
    # "aahadoram"],
    # "aahagari"],
    # "aahavila"],
    # "aahazarmavet"],
    # "aahebeli"],
    # "aaheshboni"],
    # "aahetatu"],
    # "aahethi"],
    # "aaheti"],
    # "aahevi"],
    # "aahiki"],
    # "D" :["aaholland"],
    # "" :["aaholokepo"],
    # "" :["aahomoni"],
    # "" :["aahori"],
    # "" :["aahugunina"],
    # "" :["aahuni"],
    # "" :["aahupipo"],
    # "" :["aahutu"],
    # "" :["aahwepo"],
    # "" :["aaikuthimo"],
    # "" :["aaismaeli"],
    # "" :["aajabesh"],
    # "" :["aajaser"],
    # "" :["aajerak"],
    # "" :["aajeriko"],
    # "" :["aajerusalem"],
    # "" :["aajeter"],
    # "" :["aajuda"],
    # "" :["aakaanana"],
    # "" :["aakadhi"],
    # "" :["aakadhonalela"],
    # "" :["aakalalimo"],
    # "" :["aakalele"],
    # "" :["aakaleli"],
    # "" :["aakalekipo"],
    # "" :["aakaliko"],
    # "" :["aakanaan"],
    # "" :["aakandi"],
    # "" :["aakaslu"],
    # "" :["aakeni"],
    # "" :["aakenki"],
    # "" :["aakerubi"],
    # "" :["aakipro"],
    # "" :["aakolokohi"],
    # "": ["aakolokoshi"],
    # "" :["aakomangeli"],
    # "" :["aakondeki"],
    # "" :["aakoneki"],
    # "" :["aakothi"],
    # "" :["aakukutu"],
    # "" :["aakuli"],
    # "old" :["aakulu"],
    # "" :["aakulukulu"],
    # "" :["aakumiki"],
    # "" :["aakwaajani"],
    # # "" :["aakwaamagulu"],
    # "" :["aakwagerson"],
    # "" :["aakwagulu"],
    # "" :["aakwaham"],
    # "" :["aakwakehat"],
    # "" :["Aakwamanya"],
    # "" :["aakwamerari"],
    # "" :["aakwamuhoko"],
    # "" :["aakwanayuma"],
    # "" :["aakwanelumbi"],
    # "" :["aakwanepangelo"],
    # "" :["aakwanezi"],
    # "" :["aakwanezima"],
    # "" :["aakwankwa"],
    # "" :["aakwati"],
    # "" :["aakwaveta"],
    # "" :["aakweyi"],
    # "" :["aalaadhi"],
    # "" :["aalajesha"],
    # "" :["aalalekwa"],
    # "" :["aalali"],
    # "" :["aalangeli"],
    # "" :["aalefule"],
    # "" :["aalehab"],
    # "" :["aaletushi"],
    # "" :["aalevi"],
    # "" :["aalidia"],
    # "" :["aaloloki"],
    # "" :["aamadmena"],
    # "" :["aamakedonia"],
    # "" :["aamanako"],
    # "" :["aamanasse"],
    # "" :["aamar"],
    # "" :["aamasubia"],
    # "" :["aambanda"],
    # "" :["aamedia"],
    # "" :["aamidiana"],
    # "" :["aamix"],
    # "" :["aamoabi"],
    # "" :["aamutimahenda"],
    # "" :["aanaftali"],
    # "" :["aanaftu"],
    # "" :["aanaluhepo"],
    # "" :["aanalwiho"],
    # "" :["aanalwiimbo"],
    # "" :["aanamagongamwele"],
    # "" :["aanamakoto"],
    # "" :["aanamalaka"],
    # "" :["aanamaliko"],
    # "" :["aanamapangelo"],
    # "" :["aanamatati"],
    # "" :["aanamatatilela"],
    # "" :["aanamatembakwiita"],
    # "" :["aanamawudhano"],
    # "" :["aanampwidhuli"],
    # "" :["aanamutimahenda"],
    # "" :["aanankayi"],
    # "" :["aananyanya"],
    # "" :["aanapangelo"],
    # "" :["aanashihako"],
    # "" :["aanashihongelo"],
    # "" :["aanashikandjo"],
    # "" :["aanasikepa"],
    # "" :["aanasiri"],
    # "" :["aanatempeli"],
    # "" :["aanaveta"],
    # "" :["aanchen"],
    # "" :["aanezimo"],
    # "" :["aangandjawo"],
    # "" :["aangandjeni"],
    # "" :["aangandjetu"],
    # "" :["aangandjoye"],
    # "" :["aangoka"],
    # "" :["aaniihako"],
    # "" :["aaniikaha"],
    # "" :["aaniikandjo"],
    # "" :["aaniita"],
    # "": ["aaniimaliwa"],
    # "" :["aaninive"],
    # "" :["aanotelwa"],
    # "" :["aanuuntsa"],
    # "" :["aanuushimba"],
    # "" :["aanye"],
    # "" :["aanyu"],
    # "" :["aaofir"],
    # "" :["aapindi"],
    # "" :["aapitithi"],
    # "" :["aaponto"],
    # "" :["aapukithi"],
    # "" :["aaput"],
    # "" :["aapyokoki"],
    # "" :["aarafa"],
    # "" :["aaragma"],
    # "" :["aarekab"],
    # "" :["aareuben"],
    # "" :["aarifat"],
    # "" :["aarodos"],
    # "" :["aarohingya"],
    # "" :["aasaageli"],
    # "" :["aasaba"],
    # "" :["aasabta"],
    # "" :["aasadukayi"],
    # "" :["aasamsumi"],
    # "" :["aasapoti"],
    # "" :["aasarde"],
    # "" :["aaseba"],
    # "" :["aasebulon"],
    # "" :["aaserafi"],
    # "" :["aasheba"],
    # "" :["aashekedhi"],
    # "" :["aashekem"],
    # "" :["aashelef"],
    # "" :["aashimati"],
    # "" :["aashinga"],
    # "" :["aashumati"],
    # "" :["aashungu"],
    # "" :["aasibma"],
    # "" :["aasidoni"],
    # "" :["aasikem"],
    # "" :["aasima"],
    # "" :["aasithahoni"],
    # "" :["aasodomu"],
    # "" :["aasona"],
    # "Sudanese" :["Aasudani"],
    # "" :["aasuki"],
    # "" :["aasukkot"],
    # "" :["aasusi"],
    # "" :["aatalanteni"],
    # "" :["aatango"],
    # "" :["aawuliki"],
    # "" :["aateki"],
    # "" :["aatessalonika"],
    # "" :["aathayili"],
    # "" :["aathigwa"],
    # "" :["aathiminikwa"],
    # "" :["aathingo"],
    # "" :["aathingwa"],
    # "" :["aathiopia"],
    # "" :["aathonwantu"],
    # "" :["aati"],
    # "" :["aatidhagani"],
    # "" :["aatirati"],
    # "" :["aatiro"],
    # "" :["aatjimba"],
    # "" :["aatononi"],
    # "" :["aatsaangidhi"],
    # "" :["aatsi"],
    # "" :["aatulimo"],
    # "" :["aatutsi"],
    # "" :["aatyayi"],
    # "" :["aauliki yiipindi"],
    # "" :["aaunduli"],
    # "" :["aausal"],
    # "" :["aavale"],
    # "" :["aawagona"],
    # "" :["aayai"],
    # "" :["aayakulwa"],
    # "" :["aayalmodad"],
    # "" :["aayamaleki"],
    # "" :["aayambi"],
    # "" :["aayameleki"],
    # "" :["aayammoni"],
    # "" :["aayamori"],
    # "" :["aayanaki"],
    # "" :["aayanakim"],
    # "" :["aayanam"],
    # "" :["aayanatot"],
    # "" :["aayanekeli"],
    # "" :["aayarabi"],
    # "" :["aayarki"],
    # "" :["aayaser"],
    # "" :["aayashuri"],
    # "" :["aayassur"],
    # "" :["aayatena"],
    # "" :["aayavvim"],
    # "" :["aayebusi"],
    # "" :["aayeni"],
    # "" :["aayeti"],
    # "" :["aayindi"],
    # "" :["aayitedhululi"],
    # "" :["aayithanwa"],
    # "" :["aayogohi"],
    # "" :["aayogoki"],
    # "" :["aayonaguli"],
    # "" :["aayoni"],
    # "" :["aayugani"],
    # "" :["aayuzilo"],
    # "" :["adhiminwa"],
    # "" :["adhitha"],
    # "" :["afek"],
    # "" :["ahangununwa"],
    # "" :["akwetu"],
    # "" :["alaala"],
    # "" :["alaalithwa"],
    # "" :["alulitha"],
    # "" :["alusaati"],
    # "" :["aluusati"],
    # "" :["ambekwa"],
    # "" :["amushangampangu"],
    # "" :["anda"],
    # "" :["andalalithwa"],
    # "" :["andanithwa"],
    # "" :["andjaganekelwa"],
    # "" :["andjaganekelwe"],
    # "" :["andjaganekwa"],
    # "" :["andjaganekwe"],
    # "" :["andjaganitha"],
    # "" :["andjakana"],
    # "" :["andjakane"],
    # "" :["andjakaneka"],
    # "" :["andjakaneke"],
    # "" :["andjakanekwe"],
    # "" :["andjakanitha"],
    # "" :["andjaneka"],
    # "" :["andjaneke"],
    # "" :["andjanekwa"],
    # "" :["andjeneke"],
    # "" :["andjenekele"],
    # "" :["andyakaneka"],
    # "" :["anekela"],
    # "" :["anekele"],
    # "" :["anekelitha"],
    # "" :["angukununa"],
    # "" :["apeke"],
    # "" :["ashi"],
    # "" :["ayandjaganekwa"],
    # "" :["dhaadhigile"],
    # "" :["dhaahoka"],
    # "" : dhahe, dhahekulu
    # "" :["dhamo"],
    # "" :["dhamuka"],
    # "" :["dhanakapipi"],
    # "" :["dhandhenga"], dhenga mbanda
    # construction for dhaNOUN and dheNOUN
    # "" :["dhene"],
    # "" :["dhenedhene"],
    # "" :["dhi"],
    # "" :["dhigininitha"],
    # "" :["dhigininwa"],
    # "" :["dhiidhila"],
    # "" :["dhiifudhitho"],
    # "" :["dhiifudho"],
    # "" :["dhiihape"],
    # "of " :["dhiihauto"],
    # "" :["dhiihokolola"],
    # "" :["dhiihumbatitho"],
    # "" :["dhiihupe"],
    # "" :["dhiihwa"],
    # "" :["dhiihwapo"],
    # "" :["dhiikalunga"],
    # "" :["dhiikandjohogololo"],
    # "" :["dhiikolitha"],
    # "" :["dhiikolokosha"],
    # "" :["dhiikombo"],
    # "" :["dhiikondo"],
    # "" :["dhiikuilya"],
    # "" :["dhiikulya"],
    # "" :["dhiikundaneki"],
    # "" :["dhiikunino"],
    # "" :["dhiikunuwa"],
    # "" :["dhiikushu"],
    # "" :["dhiikutu"],
    # "" :["dhiikwamahina"],
    # "" :["dhiikwamahini"],
    # "" :["dhiikwamahooli"],
    # "" :["dhiikwamalusheno"],
    # "" :["dhiikwamboga"],
    # "" :["dhiikwameni"],
    # "" :["dhiikwaniipangitho"],
    # "" :["dhiikwatelela"],
    # "" :["dhiikwatenda"],
    # "" :["dhiikwiila"],
    # "" :["dhiilalo"],
    # "" :["dhiilando"],
    # "" :["dhiili"],
    # "" :["dhiilonga"],
    # "" :["dhiilongashikongo"],
    # "" :["dhiilongela"],
    # "" :["dhiilongo"],
    # "" :["dhiilongomwa"],
    # "" :["dhiilongwa"],
    # "" :["dhiilya"],
    # "" :["dhiimaliwa"],
    # "" :["dhiimbuluma"],
    # "" :["dhiimenka"],
    # "" :["dhiimeno"],
    # "" :["dhiimuna"],
    # "" :["dhiinamwenyo"],
    # "" :["dhiingangamithi"],
    # "" :["dhiingoli"],
    # "" :["dhiinima"],
    # "" :["dhiiningwanima"],
    # "" :["dhiinonoma"],
    # "" :["dhiinyanyu"],
    # "" :["dhiipa"],
    # "" :["dhiipakete"],
    # "" :["dhiipangelo"],
    # "" :["dhiipeleki"],
    # "" :["dhiipilangi"],
    # "" :["dhiipolopolo"],
    # "" :["dhiiponga"],
    # "" :["dhiipundi"],
    # "" :["dhiipundiiheyali"],
    # "" :["dhiiputudhilo"],
    # "" :["dhiishangitha"],
    # "" :["dhiishokelya"],
    # "" :["dhiita"],
    # "" :["dhiitenda"],
    # "" :["dhiithikamena"],
    # "" :["dhiitopolwa"],
    # "" :["dhiitula"],
    # "" :["dhiitungitho"],
    # "" :["dhiiyagaya"],
    # "" :["dhiiyala"],
    # "" :["dhiiyamakuti"],
    # "" :["dhiiyambelo"],
    # "" :["dhiiyata"],
    # "" :["dhiiyela"],
    # "" :["dhiiyelekela"],
    # "" :["dhiiyelo"],
    # "" :["dhiiyemo"],
    # "" :["dhiiyimati"],
    # "" :["dhiizalomwa"],
    # "" :["dhiizemo"],
    # "" :["dhiizimba"],
    # "" :["dhikila"],
    # "" :["dhikile"],
    # "" :["dhikilwa"],
    # "" :["dhikilwe"],
    # "" :["dhikitha"],
    # "" :["dhikithile"],
    # "" :["dhikule"],
    # "" :["dhikulula"],
    # "" :["dhikulwa"],
    # "" :["dhikulwe"],
    # "" :["dhiladhililathana"],
    # "" :["dhiladhililwa"],
    # "" :["dhiladhilitha"],
    # "" :["dhilagula"],
    # "" :["dhili"],
    # "" :["dhilikilwa"],
    # "" :["dhilukitha"],
    # "" :["dhilukitheni"],
    # "" :["dhilukithilwa"],
    # "" :["dhimitha"],
    # "" :["dhimuka"],
    # "" :["dhimuna"],
    # "" :["dhingwa"],
    # "" :["dhinitha"],
    # "" :["dhipagelele"],
    # "" :["dhipagii"],
    # "" :["dhipagitha"],
    # "" :["dhipagithe"],
    # "" :["dhipagithila"],
    # "" :["dhipagithile"],
    # "" :["dhipagithwa"],
    # "" :["dhitikithe"],
    # "" :["dhituka"],
    # "" :["dhiya"],
    # "" :["dhiye"],
    "": ["dhuugoyoki"],
    "": ["dhuukonakoni"],
    "": ["dhuukumwe"],
    "": ["dhuulenga"],
    "": ["dhuumpulile"],
    "": ["dhuundhulumutu"],
    "": ["dhuundjendi"],
    "": ["dhuuntsa"],
    "": ["dhuunyekadhi"],
    "": ["dhuusita"],
    "": ["edhilileni"],
    "": ["edhililitha"],
    "": ["edhililwe"],
    "": ["edhilitha"],
    "": ["edhilwa"],
    "": ["edhilwe"],
    "": ["eendunge"],
    "": ["efundjaleko"],
    "": ["egombe"],
    "": ["egwanitho"],
    "": ["ehalakano"],
    "": ["ehambulo"],
    "": ["ehanganokwatheli"],
    "": ["ehukulalakano"],
    "": ["ehungaelo"],
    "": ["ehunga"],
    "": ["ehungo"],
    "": ["ehwahwamekohungi"],
    "": ["ehwamo"],
    "": ["eigandjo"],
    "": ["eihepeko"],
    "": ["eiholeko"],
    "": ["eihupulo"],
    "": ["eikakankamekelo"],
    "": ["eikalekelwo"],
    "": ["eikankamekelo"],
    "": ["eikutho"],
    "": ["eikwato"],
    "": ["eikwatonawa"],
    "": ["eikwatopomutima"],
    "": ["einekelomwene"],
    "": ["eipyakidhilo"],
    "": ["eisiikilo"],
    "": ["eiteko"],
    "": ["eitheto"],
    "": ["eitumbo"],
    "": ["eiuvito"],
    "": ["eiyapulo"],
    "": ["eiyopaleko"],
    "": ["ekaka"],
    "": ["ekandanga"],
    "": ["ekehuko"],
    "": ["ekelela"],
    "": ["ekolo"],
    "": ["ekolokoto"],
    "": ["ekwatakanithi"],
    "": ["elundalalo"],
    "": ["elunduko"],
    "": ["elyalyakaneko"],
    "": ["elyambala"],
    "": ["embompango"],
    "": ["embulukuto"],
    "": ["embweengo"],
    "": ["embwinda"],
    "": ["eminikilo"],
    "": ["emonitho"],
    "": ["emono"],
    "": ["enawapalo"],
    "": ["enayipalo"],
    "": ["endekela"],
    "": ["endekele"],
    "": ["endela"],
    "": ["endele"],
    "": ["endikinongeki"],
    "": ["enkono"],
    "": ["enkulutumba"],
    "": ["entamena"],
    "": ["entamene"],
    "": ["eopalo"],
    "": ["epona"],
    "": ["epwanga"],
    "": ["eshigo"],
    "": ["eshigolapi"],
    "": ["eshundulo"],
    "": ["etangakwiita"],
    "": ["etangalalo"],
    "": ["etetoko"],
    "": ["etetopo"],
    "": ["etetulo"],
    "": ["ethathana"],
    "": ["etidhaatiho"],
    "": ["etidhagano"],
    "": ["etidhomo"],
    "": ["etopagulo"],
    "": ["etopoluuthiga"],
    "": ["etsali"],
    "": ["etukauko"],
    "": ["etuwalalo"],
    "": ["eukililo"],
    "": ["euma"],
    "": ["euvithoko"],
    "": ["euvithonayi"],
    "": ["ewalanda"],
    "": ["eyakeloko"],
    "": ["eyeleko"],
    "": ["eyelo"],
    "": ["eyikwatopomitima"],
    "": ["eyikwatopomutima"],
    "": ["eyopamwe"],
    "": ["ezalo"],
    "": ["ezepo"],
    "": ["fatulile"],
    "": ["fatulilwa"],
    "": ["fatulule"],
    "": ["fatululile"],
    "": ["fatululilwa"],
    "": ["fatululilwe"],
    "": ["fatululwe"],
    "": ["fegulwa"],
    "": ["fendelitha"],
    "": ["fendelithwa"],
    "": ["fendelwa"],
    "": ["filala"],
    "": ["file"],
    "": ["filepo"],
    "": ["filila"],
    "": ["filile"],
    "": ["filwa"],
    "": ["fufila"],
    "": ["fukala"],
    "": ["fukaleka"],
    "": ["fukaleke"],
    "": ["fukalekitha"],
    "": ["fukalekithe"],
    "": ["fukalekitheni"],
    "": ["fukalekwa"],
    "": ["fukalekwe"],
    "": ["fulika"],
    "": ["fulikwa"],
    "": ["fulila"],
    "": ["fulile"],
    "": ["fulukile"],
    "": ["fulula"],
    "": ["fululukile"],
    "": ["fumbuka"],
    "": ["fumbululwe"],
    "": ["fumbulwe"],
    "": ["fumikwa"],
    "": ["fundula"],
    "": ["fundule"],
    "": ["fundulwa"],
    "": ["fungafunga"],
    "": ["galukilwa"],
    "": ["galukilwe"],
    "": ["galulako"],
    "": ["galule"],
    "": ["gameka"],
    "": ["gameke"],
    "": ["gameni"],
    "": ["gandjeleni"],
    "": ["gandjelwe"],
    "": ["gandjulula"],
    "": ["ganekele"],
    "": ["ganekwa"],
    "": ["ganenathana"],
    "": ["ganenwa"],
    "": ["gealuko"],
    "": ["geelela"],
    "": ["geelele"],
    "": ["geelelwa"],
    "": ["geelitha"],
    "": ["hadhela"],
    "": ["hadhele"],
    "": ["hadhiyi"],
    "": ["hadhwa"],
    "": ["hadhwe"],
    "": ["halakanena"],
    "": ["halakanene"],
    "": ["halakanitha"],
    "": ["halakanithapo"],
    "": ["halakanithe"],
    "": ["halakanitheni"],
    "": ["halakanithila"],
    "": ["halakanithile"],
    "": ["halakanithilwa"],
    "": ["halakanithwa"],
    "": ["halukitha"],
    "": ["halukwa"],
    "": ["halulwa"],
    "": ["halumwe"],
    "": ["halundji"],
    "": ["haluthe"],
    "": ["haluthile"],
    "": ["haluthitha"],
    "": ["haluthwa"],
    "": ["haluthwe"],
    "": ["halwo"],
    "": ["hambelele"],
    "": ["hambeleleni"],
    "": ["hambelelitha"],
    "": ["hambelelwa"],
    "": ["hambelelwe"],
    "": ["hambuleni"],
    "": ["hambulikika"],
    "": ["hambulila"],
    "": ["hambulile"],
    "": ["hambulilwa"],
    "": ["hambulilwe"],
    "": ["hambulitha"],
    "": ["hambulithila"],
    "": ["hambulithile"],
    "": ["hambulithilwa"],
    "": ["hambulithilwe"],
    "": ["hambulithitha"],
    "": ["hambulwa"],
    "": ["hali"],
    "": ["halika"],
    "": ["hamu"],
    "": ["hapa"],
    "": ["hapo"],
    "": ["hapu"],
    "": ["hapuka"],
    "": ["hawo"],
    "": ["hawu"],
    "": ["hawunene"],
    "": ["hedheni"],
    "": ["hedhi"],
    "": ["hedhitha"],
    "": ["hehelwa"],
    "": ["heke"],
    "": ["hekele"],
    "": ["hekelemo"],
    "": ["hekelwa"],
    "": ["hekuka"],
    "": ["hepekitha"],
    "": ["hepuluka"],
    "": ["hepulutha"],
    "": ["hepuluthila"],
    "": ["hewu"],
    "": ["heya"],
    "": ["heyi"],
    "": ["hilathana"],
    "": ["hindi"],
    "": ["hindwa"],
    "": ["hingila"],
    "": ["hingilathana"],
    "": ["hingile"],
    "": ["hiti"],
    "": ["hogololitha"],
    "": ["hogololithe"],
    "": ["hogolulule"],
    "": ["hogolululwa"],
    "": ["hogolululwe"],
    "": ["hokanenwe"],
    "": ["hokanitheni"],
    "": ["hokololelathana"],
    "": ["hokololelathaneni"],
    "": ["hololela"],
    "": ["hololele"],
    "": ["hololelwa"],
    "": ["homatekeka"],
    "": ["homone"],
    "": ["homoneni"],
    "": ["homonoka"],
    "": ["homonona"],
    "": ["hondelitha"],
    "": ["hondelwa"],
    "": ["hondjela"],
    "": ["hondjele"],
    "": ["hondjelwa"],
    "": ["hondjitha"],
    "": ["hongwa"],
    "": ["hotekwa"],
    "": ["hugila"],
    "": ["hugile"],
    "": ["hugileni"],
    "": ["hugilwa"],
    "": ["hugunine"],
    "": ["hugununi"],
    "": ["huhulukwa"],
    "": ["huhulukwe"],
    "": ["huhuwala"],
    "": ["hulu"],
    "": ["humbatelwa"],
    "": ["humbatitha"],
    "": ["humbatithwa"],
    "": ["humitha"],
    "": ["hunganekela"],
    "": ["hunganekele"],
    "": ["hunganekitha"],
    "": ["hupula"],
    "": ["hupulile"],
    "": ["hupulitha"],
    "": ["hupulula"],
    "": ["hupulutha"],
    "": ["hupuluthe"],
    "": ["hupuluthwa"],
    "": ["hwameni"],
    "": ["idhimbitha"],
    "": ["idhimbithe"],
    "": ["idhimina"],
    "": ["idhingila"],
    "": ["idhingile"],
    "": ["idhunga"],
    "": ["igalala"],
    "": ["igalaleke"],
    "": ["igaluka"],
    "": ["igalula"],
    "": ["igalule"],
    "": ["igaluluka"],
    "": ["igidhathana"],
    "": ["igidhitha"],
    "": ["igidhwa"],
    "": ["igundu"],
    "": ["igwana"],
    "": ["igwedha"],
    "": ["igwedhela"],
    "": ["igwedheleko"],
    "": ["ihakanwa"],
    "": ["ihambulila"],
    "": ["ihambulile"],
    "": ["ihambulithila"],
    "": ["ihambulithile"],
    "": ["ihanganitha"],
    "": ["ihapa"],
    "": ["ihapititha"],
    "": ["ihapu"],
    "": ["ihepekele"],
    "": ["iholele"],
    "": ["iholola"],
    "": ["ihololela"],
    "": ["ihololele"],
    "": ["ihomatekeleni"],
    "": ["ihukata"],
    "": ["ihumba"],
    "": ["ihumbate"],
    "": ["ihumbatela"],
    "": ["ihumbatele"],
    "": ["ihumbatelwa"],
    "": ["ihupithila"],
    "": ["ihupithile"],
    "": ["ihupithileni"],
    "": ["ihupula"],
    "": ["iidhenge"],
    "": ["iidhimakuni"],
    "": ["iidhipagele"],
    "": ["iidhudhu"],
    "": ["iifakufaku"],
    "": ["iifeka"],
    "": ["iifo"],
    "": ["iifudhitho"],
    "": ["iifulomwa"],
    "": ["iifutile"],
    "": ["iifutilemo"],
    "": ["iifutwa"],
    "": ["iigeyi"],
    "": ["iigumbotya"],
    "": ["iihaki"],
    "": ["iihampi"],
    "": ["iihehelela"],
    "": ["iihingitho"],
    "": ["iihogololitho"],
    "": ["iihokithi"],
    "": ["iiholameno"],
    "": ["iihole"],
    "": ["iihomo"],
    "": ["iihondjelo"],
    "": ["iihongomwa"],
    "": ["iihongwamenka"],
    "": ["iihono"],
    "": ["iihukikwanyeka"],
    "": ["iihumbatitho"],
    "": ["iihupithi"],
    "": ["iikalungakombo"],
    "": ["iikandekitho"],
    "": ["iikandjo"],
    "": ["iikandjolonga"],
    "": ["iikango"],
    "": ["iikologo"],
    "": ["iikonaakonithi"],
    "": ["iikonakonitha"],
    "": ["iikonakonwa"],
    "": ["iikonaakonithi"],
    "": ["iikonakonitha"],
    "": ["iikonakonwa"],
    "": ["iikulugumbo"],
    "": ["iikulumanene"],
    "": ["iikuyali"],
    "": ["iikwakegulu"],
    "": ["iikwakuwale"],
    "": ["iikwakuyakwa"],
    "": ["iikwamagadhi"],
    "": ["iikwamagulugane"],
    "": ["iikwamahogololo"],
    "": ["iikwamahooli"],
    "": ["iikwamahupilo"],
    "": ["iikwamaliko"],
    "": ["iikwamantompelo"],
    "": ["iikwamatungo"],
    "": ["iikwamela"],
    "": ["iikwamenye"],
    "": ["iikwamulandu"],
    "": ["iikwandjembo"],
    "": ["iikwangala"],
    "": ["iikwankondo"],
    "": ["iikwankulunkedhi"],
    "": ["iikwanyama"],
    "": ["iikwanzo"],
    "": ["iikwaopaleki"],
    "": ["iikwapuka"],
    "": ["iikwatakanithi"],
    "": ["iikwatakanithitya"],
    "": ["iikwatelwa"],
    "": ["iikwathithi"],
    "": ["iikwathithilongo"],
    "": ["iikwathitho"],
    "": ["iikwathitholongo"],
    "": ["iikwathityalonga"],
    "": ["iikwathokondjithi"],
    "": ["iikwatitho"],
    "": ["iikwatwa"],
    "": ["iikwelengi"],
    "": ["iikwiila"],
    "": ["iilandulithitsa"],
    "": ["iilongayakulo"],
    "": ["iilongithwa"],
    "": ["iilongomwa"],
    "": ["iilyatelelo"],
    "": ["iimbamba"],
    "": ["iimenka"],
    "": ["iimona"],
    "": ["iimpungu"],
    "": ["iimputu"],
    "": ["iinkoti"],
    "": ["iinyakwi"],
    "": ["iinyanga"],
    "": ["iinyolwa"],
    "": ["iinzinzi"],
    "": ["iipakolwa"],
    "": ["iipakosolwa"],
    "": ["iipangelithi"],
    "": ["iipatithi"],
    "": ["iipatitho"],
    "": ["iipatululitya"],
    "": ["iipena"],
    "": ["iipopo"],
    "": ["iipundjamenye"],
    "": ["iipungulwa"],
    "": ["iipwe"],
    "": ["iishini"],
    "": ["iitaandelithi"],
    "": ["iitakamithi"],
    "": ["iitayingeleki"],
    "": ["iitelekela"],
    "": ["iitembukilwa"],
    "": ["iitemitho"],
    "": ["iitenga"],
    "": ["iithingila"],
    "": ["iitholomo"],
    "": ["iitila"],
    "": ["iitogonyona"],
    "": ["iitonditha"],
    "": ["iitondoka"],
    "": ["iitopolelwa"],
    "": ["iitsalomwa"],
    "": ["iitsambe"],
    "": ["iitsankwanu"],
    "": ["iitsezi"],
    "": ["iitsininitho"],
    "": ["iitsinino"],
    "": ["iitsininondjambo"],
    "": ["iitukimbepo"],
    "": ["iityahalalupe"],
    "": ["iityalonga"],
    "": ["iityahalalupe"],
    "": ["iityalupe"],
    "": ["iityani"],
    "": ["iityankumwe"],
    "": ["iityapeha"],
    "": ["iityapehalela"],
    "": ["iiyakele"],
    "": ["iiyakulitho"],
    "": ["iiyata"],
    "": ["iiyela"],
    "": ["iiyelekela"],
    "": ["iiyelekitho"],
    "": ["iiyelele"],
    "": ["iiyelelwa"],
    "": ["iiyenda"],
    "": ["iiyetwa"],
    "": ["iiyetwamo"],
    "": ["iiyetwapo"],
    "": ["iiyoololinkwanu"],
    "": ["iiyopalekithi"],
    "": ["iiyopalekitho"],
    "": ["iiyotitho"],
    "": ["iiyulitho"],
    "": ["iiyuma"],
    "": ["iiyumbitho"],
    "": ["iiyutha"],
    "": ["iiyuvikitya"],
    "": ["iizatya"],
    "": ["iizigitho"],
    "": ["ikalathana"],
    "": ["ikalekeni"],
    "": ["ikanithitha"],
    "": ["ikanyatela"],
    "": ["ikanyutulule"],
    "": ["ikesha"],
    "": ["ikile"],
    "": ["ikokela"],
    "": ["ikokele"],
    "": ["ikongeleni"],
    "": ["ikotokele"],
    "": ["ikotokeleni"],
    "": ["ikukutika"],
    "": ["ikukutike"],
    "": ["ikukutile"],
    "": ["ikululitha"],
    "": ["ikululithe"],
    "": ["ikulupike"],
    "": ["ikumbu"],
    "": ["ikumike"],
    "": ["ikumikeni"],
    "": ["ikumithi"],
    "": ["ikuthe"],
    "": ["ikuthila"],
    "": ["ikuthile"],
    "": ["ikuthitha"],
    "": ["ilandela"],
    "": ["ilandele"],
    "": ["ilandeleni"],
    "": ["ilanditha"],
    "": ["ilandithe"],
    "": ["ilandithomwa"],
    "": ["ilangele"],
    "": ["ile"],
    "": ["ileka"],
    "": ["ileke"],
    "": ["ilele"],
    "": ["ilemo"],
    "": ["ilikola"],
    "": ["ilikolela"],
    "": ["ilikolele"],
    "": ["ilikoleleni"],
    "": ["ilikolelwa"],
    "": ["ilikolomwa"],
    "": ["ilile"],
    "": ["ililela"],
    "": ["ilileni"],
    "": ["ililonga"],
    "": ["ilimoshilongo"],
    "": ["ilitha"],
    "": ["ilombwela"],
    "": ["ilombwele"],
    "": ["ilondodhe"],
    "": ["ilongadhalwa"],
    "": ["ilonge"],
    "": ["ilongela"],
    "": ["ilongele"],
    "": ["ilongeleko"],
    "": ["ilongitha"],
    "": ["ilongithwe"],
    "": ["ilongo"],
    "": ["ilongwa"],
    "": ["iluka"],
    "": ["ilukile"],
    "": ["ilukilile"],
    "": ["iluku"],
    "": ["ilungile"],
    "": ["iluudhike"],
    "": ["ilwa"],
    "": ["ilwapo"],
    "": ["ilya"],
    "": ["ilye"],
    "": ["imanana"],
    "": ["imanga"],
    "": ["imange"],
    "": ["imangeleka"],
    "": ["imangeleke"],
    "": ["imangelekela"],
    "": ["imangelekele"],
    "": ["imangelekitha"],
    "": ["imangeleleke"],
    "": ["imangeni"],
    "": ["imangulukila"],
    "": ["imangulula"],
    "": ["imbi"],
    "": ["imbila"],
    "": ["imi"],
    "": ["imike"],
    "": ["imikeni"],
    "": ["imina"],
    "": ["imitha"],
    "": ["imona"],
    "": ["imonena"],
    "": ["imonene"],
    "": ["imonikila"],
    "": ["imonikile"],
    "": ["imonitha"],
    "": ["imonithathana"],
    "": ["imonithe"],
    "": ["imonithile"],
    "": ["imono"],
    "": ["imwenena"],
    "": ["imwenenena"],
    "": ["inaamu"],
    "": ["inaandi"],
    "": ["inaanwa"],
    "": ["inaapa"],
    "": ["inaapu"],
    "": ["inaashi"],
    "": ["inaathika"],
    "": ["inaatopola"],
    "": ["inaatu"],
    "": ["inaawu"],
    "": ["inaaya"],
    "": ["inaaye"],
    "": ["inaayi"],
    "": ["inaayu"],
    "": ["inadhika"],
    "": ["inadhipwa"],
    "": ["indjipalekwe"],
    "": ["indjipalele"],
    "": ["ineli"],
    "": ["inemu"],
    "": ["inenepeka"],
    "": ["inenepeke"],
    "": ["inenepekela"],
    "": ["inenepekele"],
    "": ["ineyi"],
    "": ["ingungunina"],
    "": ["inimpila"],
    "": ["ininga"],
    "": ["ininge"],
    "": ["iningi"],
    "": ["iningila"],
    "": ["iningile"],
    "": ["iningililemo"],
    "": ["ininginitha"],
    "": ["iningitha"],
    "": ["inyatekele"],
    "": ["inyatekitha"],
    "": ["ipa"],
    "": ["ipamba"],
    "": ["ipandula"],
    "": ["ipangelwa"],
    "": ["ipangula"],
    "": ["ipitithila"],
    "": ["ipolithile"],
    "": ["ipukitha"],
    "": ["ipula"],
    "": ["ipulakenene"],
    "": ["ipulitha"],
    "": ["ipululila"],
    "": ["iputudha"],
    "": ["iputudhile"],
    "": ["ipwedha"],
    "": ["ipwililika"],
    "": ["ipwililike"],
    "": ["ishuna"],
    "": ["ishundula"],
    "": ["ishunina"],
    "": ["ishunitha"],
    "": ["isila"],
    "": ["isile"],
    "": ["isimaneka"],
    "": ["isimaneke"],
    "": ["isimanekele"],
    "": ["isisidha"],
    "": ["isitha"],
    "": ["isizimike"],
    "": ["isizimikeni"],
    "": ["istuwa"],
    "": ["isuukulula"],
    "": ["itaadhi"],
    "": ["itaaga"],
    "": ["itaage"],
    "": ["itaagu"],
    "": ["itaaka"],
    "": ["itaaku"],
    "": ["itaale"],
    "": ["itaamu"],
    "": ["itaandi"],
    "": ["itaapa"],
    "": ["itaapu"],
    "": ["itaashi"],
    "": ["itaasi"],
    "": ["itaatu"],
    "": ["itaau"],
    "": ["itaavulu"],
    "": ["itaawu"],
    "": ["itaaya"],
    "": ["itaaye"],
    "": ["itaayi"],
    "": ["itaayu"],
    "": ["itadhi"],
    "": ["itadhihala"],
    "": ["itaga"],
    "": ["itage"],
    "": ["itagi"],
    "": ["itagu"],
    "": ["itai"],
    "": ["itaka"],
    "": ["itakeka"],
    "": ["itakeke"],
    "": ["itaku"],
    "": ["itala"],
    "": ["itale"],
    "": ["italela"],
    "": ["italelako"],
    "": ["italele"],
    "": ["italeni"],
    "": ["itali"],
    "": ["italitha"],
    "": ["italu"],
    "": ["italy"],
    "": ["itamu"],
    "": ["itandi"],
    "": ["itanga"],
    "": ["itangela"],
    "": ["itangele"],
    "": ["itangitha"],
    "": ["itangomona"],
    "": ["itano"],
    "": ["itapa"],
    "": ["itapu"],
    "": ["itashe"],
    "": ["itashi"],
    "": ["itatu"],
    "": ["itau"],
    "": ["itavulu"],
    "": ["itawu"],
    "": ["itaya"],
    "": ["itaye"],
    "": ["itayela"],
    "": ["itayele"],
    "": ["itayi"],
    "": ["ite"],
    "": ["itegelele"],
    "": ["itegu"],
    "": ["iteka"],
    "": ["iteke"],
    "": ["itekela"],
    "": ["itelekele"],
    "": ["itelithigi"],
    "": ["iteluka"],
    "": ["itemu"],
    "": ["itenda"],
    "": ["itendela"],
    "": ["itendele"],
    "": ["iteshi"],
    "": ["iteta"],
    "": ["itete"],
    "": ["iteteka"],
    "": ["itetila"],
    "": ["iteya"],
    "": ["iteyela"],
    "": ["iteyele"],
    "": ["iteyelwa"],
    "": ["iteyi"],
    "": ["itha"],
    "": ["ithanathana"],
    "": ["ithanawa"],
    "": ["ithane"],
    "": ["ithanena"],
    "": ["ithanene"],
    "": ["ithaneni"],
    "": ["ithanenwa"],
    "": ["ithanenwe"],
    "": ["ithanitha"],
    "": ["ithanununwa"],
    "": ["ithanwa"],
    "": ["ithanwaokashana"],
    "": ["ithanwe"],
    "": ["ithigi"],
    "": ["ithigile"],
    "": ["ithike"],
    "": ["ithonithe"],
    "": ["itii"],
    "": ["itiiyutha"],
    "": ["itila"],
    "": ["itile"],
    "": ["ito"],
    "": ["itogu"],
    "": ["itokele"],
    "": ["itokola"],
    "": ["itokolele"],
    "": ["itompo"],
    "": ["itonatela"],
    "": ["itonateleni"],
    "": ["itongola"],
    "": ["itongomona"],
    "": ["itonywa"],
    "": ["itoo"],
    "": ["itoolele"],
    "": ["itoolongitha"],
    "": ["itope"],
    "": ["itopolelwa"],
    "": ["itopoleni"],
    "": ["itota"],
    "": ["itowu"],
    "": ["itran"],
    "": ["its"],
    "": ["itsa"],
    "": ["itse"],
    "": ["itseya"],
    "": ["itseyitha"],
    "": ["itsika"],
    "": ["itsike"],
    "": ["itsikeni"],
    "": ["itsikile"],
    "": ["itsila"],
    "": ["itsile"],
    "": ["itsiwa"],
    "": ["itsu"],
    "": ["itsuwa"],
    "": ["itsuwika"],
    "": ["itsuwike"],
    "": ["ittai"],
    "": ["itu"],
    "": ["itudha"],
    "": ["itukithwabalona"],
    "": ["itukumuna"],
    "": ["itula"],
    "": ["itulamo"],
    "": ["itule"],
    "": ["itulemo"],
    "": ["ituleni"],
    "": ["itulila"],
    "": ["itulile"],
    "": ["itulilemo"],
    "": ["itulilwa"],
    "": ["itulilwe"],
    "": ["itulimo"],
    "": ["itumba"],
    "": ["itumbaleke"],
    "": ["itumbile"],
    "": ["itumbu"],
    "": ["itumbula"],
    "": ["itunes"],
    "": ["itungila"],
    "": ["itungile"],
    "": ["itungileni"],
    "": ["itungu"],
    "": ["itutsithe"],
    "": ["itya"],
    "": ["ityaa"],
    "": ["ityaaya"],
    "": ["ityatayi"],
    "": ["iwanawa"],
    "": ["iwathela"],
    "": ["iwathelele"],
    "": ["iway"],
    "": ["iwegenyene"],
    "": ["iwete"],
    "": ["iwetike"],
    "": ["iwetikile"],
    "": ["iwinayi"],
    "": ["iwitikile"],
    "": ["iya"],
    "": ["iyaaka"],
    "": ["iyaambo"],
    "": ["iyadha"],
    "": ["iyadhaadha"],
    "": ["iyadhe"],
    "": ["iyage"],
    "": ["iyageke"],
    "": ["iyaha"],
    "": ["iyahe"],
    "": ["iyakamo"],
    "": ["iyake"],
    "": ["iyakela"],
    "": ["iyakele"],
    "": ["iyakelemo"],
    "": ["iyakelwa"],
    "": ["iyakula"],
    "": ["iyali"],
    "": ["iyaloo"],
    "": ["iyaludha"],
    "": ["iyalula"],
    "": ["iyamba"],
    "": ["iyambapaleka"],
    "": ["iyambapaleke"],
    "": ["iyambe"],
    "": ["iyambela"],
    "": ["iyambele"],
    "": ["iyambelelwa"],
    "": ["iyambelwa"],
    "": ["iyambidhidha"],
    "": ["iyambidhidhe"],
    "": ["iyambo"],
    "": ["iyambula"],
    "": ["iyambwa"],
    "": ["iyanda"],
    "": ["iyande"],
    "": ["iyanuna"],
    "": ["iyapula"],
    "": ["iyapule"],
    "": ["iyapuleni"],
    "": ["iyapulila"],
    "": ["iyapulile"],
    "": ["iyapulilii"],
    "": ["iye"],
    "": ["iyedhilile"],
    "": ["iyegulula"],
    "": ["iyekelahi"],
    "": ["iyekelehi"],
    "": ["iyekelele"],
    "": ["iyeleke"],
    "": ["iyelipwa"],
    "": ["iyelitha"],
    "": ["iyemo"],
    "": ["iyendela"],
    "": ["iyendele"],
    "": ["iyendulula"],
    "": ["iyendulule"],
    "": ["iyeta"],
    "": ["iyetele"],
    "": ["iyetelele"],
    "": ["iyethele"],
    "": ["iyi"],
    "": ["iyiimati"],
    "": ["iyinekela"],
    "": ["iyinekele"],
    "": ["iyithana"],
    "": ["iyoga"],
    "": ["iyoge"],
    "": ["iyogele"],
    "": ["iyogeni"],
    "": ["iyogo"],
    "": ["iyogwa"],
    "": ["iyolele"],
    "": ["iyondodhe"],
    "": ["iyondodhele"],
    "": ["iyone"],
    "": ["iyono"],
    "": ["iyoo"],
    "": ["iyoolola"],
    "": ["iyoololela"],
    "": ["iyoololele"],
    "": ["iyoololeni"],
    "": ["iyopaleke"],
    "": ["iyopalekitha"],
    "": ["iyopalela"],
    "": ["iyopalele"],
    "": ["iyotango"],
    "": ["iyukila"],
    "": ["iyukile"],
    "": ["iyukililitha"],
    "": ["iyula"],
    "": ["iyulika"],
    "": ["iyulike"],
    "": ["iyumbata"],
    "": ["iyumbile"],
    "": ["iyundulila"],
    "": ["iyundulile"],
    "": ["iyutha"],
    "": ["iyuthakepango"],
    "": ["iyuthe"],
    "": ["iyutheni"],
    "": ["iyuthile"],
    "": ["iyuthwa"],
    "": ["iyuva"],
    "": ["iyuvanene"],
    "": ["iyuvite"],
    "": ["iyuvitha"],
    "": ["iyuvithe"],
    "": ["iyuvu"],
    "": ["izaleke"],
    "": ["izalekeni"],
    "": ["izalekitha"],
    "": ["izata"],
    "": ["izemo"],
    "": ["izi"],
    "": ["izike"],
    "": ["kaadhipo"],
    "": ["kalelela"],
    "": ["kalelele"],
    "": ["kambakana"],
    "": ["kambakaneke"],
    "": ["kambakanwa"],
    "": ["kamuna"],
    "": ["kankameka"],
    "": ["kankameke"],
    "": ["kankamekelwa"],
    "": ["kankamekwa"],
    "": ["kankamekwe"],
    "": ["kedhiya"],
    "": ["kegala"],
    "": ["kegalikano"],
    "": ["kegameno"],
    "": ["kegandjo"],
    "": ["keganitho"],
    "": ["kegano"],
    "": ["kegeelo"],
    "": ["kegonga"],
    "": ["kegongalo"],
    "": ["kegongamwele"],
    "": ["kegoya"],
    "": ["kegulu"],
    "": ["kegumona"],
    "": ["kegwano"],
    "": ["kegwilo"],
    "": ["keha"],
    "": ["kehalakano"],
    "": ["kehale"],
    "": ["kehalo"],
    "": ["kehempululo"],
    "": ["kehenye"],
    "": ["kehepitho"],
    "": ["keholo"],
    "": ["kehomono"],
    "": ["kehugilo"],
    "": ["kehumitho"],
    "": ["kehumo"],
    "": ["keihumbato"],
    "": ["keikonaakonitho"],
    "": ["keikukutiko"],
    "": ["keikwato"],
    "": ["keilongo"],
    "": ["keimweneneno"],
    "": ["keindilo"],
    "": ["keinenepeko"],
    "": ["keipyakidhilo"],
    "": ["keithano"],
    "": ["keityo"],
    "": ["keiyuvo"],
    "": ["kekako"],
    "": ["kekalekopo"],
    "": ["kekango"],
    "": ["kekanithopo"],
    "": ["kekankameno"],
    "": ["kekano"],
    "": ["kekende"],
    "": ["kekololo"],
    "": ["kekonakono"],
    "": ["kekondjitho"],
    "": ["kekopi"],
    "": ["kekopo"],
    "": ["kekothi"],
    "": ["kekoye"],
    "": ["keku"],
    "": ["kekuku"],
    "": ["kekulukilomo"],
    "": ["kekumbu"],
    "": ["kekungululo"],
    "": ["kekuni"],
    "": ["kekuno"],
    "": ["kekwa"],
    "": ["kekwatho"],
    "": ["kekwato"],
    "": ["kekwawo"],
    "": ["kela"],
    "": ["kelalakano"],
    "": ["kelambo"],
    "": ["kelanditho"],
    "": ["kelandithopo"],
    "": ["kelandulathano"],
    "": ["kelangeko"],
    "": ["kelelo"],
    "": ["kelelogongalo"],
    "": ["kelelongeleki"],
    "": ["keli"],
    "": ["keliko"],
    "": ["kelilo"],
    "": ["keloli"],
    "": ["kelombo"],
    "": ["kelombwelo"],
    "": ["kelondo"],
    "": ["kelondodho"],
    "": ["kelongelo"],
    "": ["kelongelokalunga"],
    "": ["kelongelokumwe"],
    "": ["kelongitho"],
    "": ["kelongo"],
    "": ["kelundalalo"],
    "": ["kelundu"],
    "": ["keluudho"],
    "": ["keluwa"],
    "": ["kelwaakani"],
    "": ["kemakelo"],
    "": ["kemanguluko"],
    "": ["kemangululo"],
    "": ["kemanya"],
    "": ["kematukilo"],
    "": ["kembako"],
    "": ["kembakumbaku"],
    "": ["kembo"],
    "": ["kembugaleko"],
    "": ["kembugapalo"],
    "": ["kembwinda"],
    "": ["keme"],
    "": ["kemena"],
    "": ["kemenathana"],
    "": ["kemoniko"],
    "": ["kena"],
    "": ["kenasha"],
    "": ["kendumbakano"],
    "": ["kengela"],
    "": ["kengelele"],
    "": ["kengelelwa"],
    "": ["kengungo"],
    "": ["kengungu"],
    "": ["keni"],
    "": ["keningino"],
    "": ["keningonawa"],
    "": ["kenke"],
    "": ["kenkele"],
    "": ["kenyanana"],
    "": ["kenyaneka"],
    "": ["kenyaneke"],
    "": ["kenyanyalo"],
    "": ["kenyanyu"],
    "": ["kenyolo"],
    "": ["kepandaanda"],
    "": ["kepandja"],
    "": ["kepandje"],
    "": ["kepingakanitho"],
    "": ["kepipi"],
    "": ["kepitikilo"],
    "": ["kepitiko"],
    "": ["kepito"],
    "": ["kepopilongulu"],
    "": ["kepopitho"],
    "": ["kepuko"],
    "": ["kepulo"],
    "": ["kepumpo"],
    "": ["kepungu"],
    "": ["keputudho"],
    "": ["kepwinopo"],
    "": ["kepya"],
    "": ["keshi"],
    "": ["keshina"],
    "": ["keshininga"],
    "": ["keshito"],
    "": ["kesiku"],
    "": ["kesimano"],
    "": ["kesindano"],
    "": ["kesipa"],
    "": ["ketala"],
    "": ["ketalelo"],
    "": ["ketaneno"],
    "": ["ketanga"],
    "": ["ketango"],
    "": ["ketata"],
    "": ["ketaulilo"],
    "": ["ketayego"],
    "": ["ketegameno"],
    "": ["ketekopo"],
    "": ["ketemba"],
    "": ["ketembu"],
    "": ["keteto"],
    "": ["keteyo"],
    "": ["kethano"],
    "": ["kethele"],
    "": ["kethengununo"],
    "": ["kethigathano"],
    "": ["kethikamepo"],
    "": ["kethikilo"],
    "": ["kethimbo"],
    "": ["kethindakano"],
    "": ["keti"],
    "": ["ketilyasa"],
    "": ["ketitano"],
    "": ["ketitatu"],
    "": ["ketiyali"],
    "": ["ketongo"],
    "": ["ketopagulo"],
    "": ["ketopolathaneno"],
    "": ["ketopolitho"],
    "": ["ketosha"],
    "": ["ketotepo"],
    "": ["ketoto"],
    "": ["ketsali"],
    "": ["ketsalihangano"],
    "": ["ketseyitho"],
    "": ["ketsininoyambelo"],
    "": ["ketukuko"],
    "": ["ketulo"],
    "": ["keuliko"],
    "": ["keumbo"],
    "": ["keunda"],
    "": ["keutho"],
    "": ["keuvaneko"],
    "": ["keuvaneno"],
    "": ["keuvathano"],
    "": ["keuveko"],
    "": ["keuvitho"],
    "": ["keuyagano"],
    "": ["kevaangeli"],
    "": ["kevalo"],
    "": ["kevalululo"],
    "": ["kevi"],
    "": ["kevululuko"],
    "": ["kewa"],
    "": ["kewale"],
    "": ["kewangandjo"],
    "": ["kewawa"],
    "": ["kewe"],
    "": ["kewete"],
    "": ["kewi"],
    "": ["kewilikongundu"],
    "": ["keya"],
    "": ["keyakulo"],
    "": ["keyalelo"],
    "": ["keyalulo"],
    "": ["keyalululo"],
    "": ["keyambeko"],
    "": ["keyambukepo"],
    "": ["keyambulepo"],
    "": ["keyana"],
    "": ["keyapulo"],
    "": ["keye"],
    "": ["keyeme"],
    "": ["keyena"],
    "": ["keyi"],
    "": ["keyinda"],
    "": ["keyitaalo"],
    "": ["keyithano"],
    "": ["keyono"],
    "": ["keyumudho"],
    "": ["kezimo"],
    "": ["kiidhenga"],
    "": ["kiidhidhimikila"],
    "": ["kiifudhitho"],
    "": ["kiihaka"],
    "": ["kiihakanwa"],
    "": ["kiihehelela"],
    "": ["kiihoko"],
    "": ["kiihokolola"],
    "": ["kiihukikwanyeka"],
    "": ["kiihuna"],
    "": ["kiihwa"],
    "": ["kiikagadhi"],
    "": ["kiikalela"],
    "": ["kiikalunga"],
    "": ["kiikandjo"],
    "": ["kiikando"],
    "": ["kiikungulu"],
    "": ["kiikuni"],
    "": ["kiikunino"],
    "": ["kiikuthile"],
    "": ["kiikuti"],
    "": ["kiikutu"],
    "": ["kiikwamahupilo"],
    "": ["kiikwamela"],
    "": ["kiikwamepya"],
    "": ["kiikwamuthigululwakalo"],
    "": ["kiikwandjembo"],
    "": ["kiikwanzo"],
    "": ["kiikwapolitika"],
    "": ["kiikwawo"],
    "": ["kiikwiila"],
    "": ["kiilalo"],
    "": ["kiilandohote"],
    "": ["kiilangela"],
    "": ["kiileshwa"],
    "": ["kiilikama"],
    "": ["kiilolelo"],
    "": ["kiilonga"],
    "": ["kiilongadhalwa"],
    "": ["kiilongankondo"],
    "": ["kiilongekidha"],
    "": ["kiilongitho"],
    "": ["kiilongithomwa"],
    "": ["kiilongo"],
    "": ["kiilongomwa"],
    "": ["kiilongoyopondje"],
    "": ["kiilongwa"],
    "": ["kiiluka"],
    "": ["kiilya"],
    "": ["kiilyatelelo"],
    "": ["kiilyawala"],
    "": ["kiilyo"],
    "": ["kiilyoya"],
    "": ["kiimaliwa"],
    "": ["kiimbaambala"],
    "": ["kiimbuluma"],
    "": ["kiimenka"],
    "": ["kiimeno"],
    "": ["kiimpoko"],
    "": ["kiimpungu"],
    "": ["kiimuhole"],
    "": ["kiimuna"],
    "": ["kiina"],
    "": ["kiinagoga"],
    "": ["kiinahenda"],
    "": ["kiinakukwanithwa"],
    "": ["kiinamwenyo"],
    "": ["kiinamwnyo"],
    "": ["kiingangamithi"],
    "": ["kiinge"],
    "": ["kiingulu"],
    "": ["kiinima"],
    "": ["kiiningwanima"],
    "": ["kiinonoma"],
    "": ["kiinuma"],
    "": ["kiinyandwa"],
    "": ["kiinyengithwa"],
    "": ["kiinyolwa"],
    "": ["kiipakete"],
    "": ["kiipala"],
    "": ["kiipalanyolo"],
    "": ["kiipambele"],
    "": ["kiipangelapundi"],
    "": ["kiipangelo"],
    "": ["kiipango"],
    "": ["kiipapatsi"],
    "": ["kiipatululithityapulo"],
    "": ["kiipaykidhile"],
    "": ["kiipeko"],
    "": ["kiipeleki"],
    "": ["kiipelende"],
    "": ["kiipilangi"],
    "": ["kiipitudhilo"],
    "": ["kiiponga"],
    "": ["kiipongolo"],
    "": ["kiiponokela"],
    "": ["kiipotha"],
    "": ["kiipotoplwa"],
    "": ["kiipula"],
    "": ["kiipumbiwa"],
    "": ["kiipundi"],
    "": ["kiipupu"],
    "": ["kiiputidhilo"],
    "": ["kiiputudhilo"],
    "": ["kiiputukilo"],
    "": ["kiiputundhilo"],
    "": ["kiisha"],
    "": ["kiishana"],
    "": ["kiishangithe"],
    "": ["kiishawo"],
    "": ["kiishiindalongo"],
    "": ["kiishipotha"],
    "": ["kiishitwa"],
    "": ["kiishunitha"],
    "": ["kiisilukutumbe"],
    "": ["kiita"],
    "": ["kiitaafula"],
    "": ["kiitaasi"],
    "": ["kiitasi"],
    "": ["kiitayi"],
    "": ["kiitayingeleki"],
    "": ["kiitekela"],
    "": ["kiitenda"],
    "": ["kiitenya"],
    "": ["kiithikamena"],
    "": ["kiitopitha"],
    "": ["kiitoplwa"],
    "": ["kiitopolwa"],
    "": ["kiitopolwaa"],
    "": ["kiitopolwahogololo"],
    "": ["kiitsa"],
    "": ["kiitsambe"],
    "": ["kiitsuwa"],
    "": ["kiitukulwa"],
    "": ["kiitukutuku"],
    "": ["kiitumbuka"],
    "": ["kiitungithi"],
    "": ["kiituntu"],
    "": ["kiituthi"],
    "": ["kiitya"],
    "": ["kiityadhina"],
    "": ["kiityadhinalela"],
    "": ["kiivalelo"],
    "": ["kiiwiliki"],
    "": ["kiiyadha"],
    "": ["kiiyadhe"],
    "": ["kiiyaha"],
    "": ["kiiyaka"],
    "": ["kiiyala"],
    "": ["kiiyamakuti"],
    "": ["kiiyambelo"],
    "": ["kiiyandha"],
    "": ["kiiyelekela"],
    "": ["kiiyelo"],
    "": ["kiiyenditho"],
    "": ["kiiyetwapo"],
    "": ["kiiyimati"],
    "": ["kiiyithanene"],
    "": ["kiiyoga"],
    "": ["kiiyoge"],
    "": ["kiiyuva"],
    "": ["kiizalomwa"],
    "": ["kiizemo"],
    "": ["kodhilile"],
    "": ["kodhime"],
    "": ["kofenya"],
    "": ["kofuto"],
    "": ["kogeke"],
    "": ["kohake"],
    "": ["kohamba"],
    "": ["kohambo"],
    "": ["kohandje"],
    "": ["kohanona"],
    "": ["kohapu"],
    "": ["koholondo"],
    "": ["koholongo"],
    "": ["kohonda"],
    "": ["kohondakadhona"],
    "": ["kohulo"],
    "": ["kohungi"],
    "": ["kohwehwe"],
    "": ["kokambapila"],
    "": ["kokamitiye"],
    "": ["kokampani"],
    "": ["kokamukithi"],
    "": ["kokamwaalu"],
    "": ["kokamwayina"],
    "": ["kokamwayinamati"],
    "": ["kokanasikola"],
    "": ["kokandidate"],
    "": ["kokandingosho"],
    "": ["kokangundu"],
    "": ["kokanona"],
    "": ["kokanonamati"],
    "": ["kokantowele"],
    "": ["kokantuntu"],
    "": ["kokapana"],
    "": ["kokapangelo"],
    "": ["kokapate"],
    "": ["kokapepo"],
    "": ["kokapuka"],
    "": ["kokatana"],
    "": ["kokatanga"],
    "": ["kokatekulu"],
    "": ["kokatenda"],
    "": ["kokatokolitho"],
    "": ["kokatomeno"],
    "": ["kokatulilo"],
    "": ["kokela"],
    "": ["kokene"],
    "": ["kokitha"],
    "": ["kokithe"],
    "": ["kokolela"],
    "": ["kokoleni"],
    "": ["kokoloka"],
    "": ["kokolwa"],
    "": ["kokolwe"],
    "": ["kokomayulu"],
    "": ["kokombanda"],
    "": ["kokombandambanda"],
    "": ["kokombelewa"],
    "": ["kokomukunda"],
    "": ["kokomusati"],
    "": ["kokomwenyo"],
    "": ["kokondangwa"],
    "": ["kokondje"],
    "": ["kokongeleka"],
    "": ["kokongodhi"],
    "": ["kokonkalo"],
    "": ["kokoompadhi"],
    "": ["kokoshipa"],
    "": ["kokoshipundi"],
    "": ["kokudhengagulwa"],
    "": ["kokudhimbulukwa"],
    "": ["kokudhimbulutha"],
    "": ["kokudhina"],
    "": ["kokudhipagwa"],
    "": ["kokufula"],
    "": ["kokufuta"],
    "": ["kokufutila"],
    "": ["kokufutwa"],
    "": ["kokugagaleka"],
    "": ["kokugalikana"],
    "": ["kokugalulila"],
    "": ["kokugongela"],
    "": ["kokugukeelela"],
    "": ["kokuhogolola"],
    "": ["kokuhogololela"],
    "": ["kokuhola"],
    "": ["kokuhumbata"],
    "": ["kokuhumitha"],
    "": ["kokuhupitha"],
    "": ["kokukala"],
    "": ["kokukalamwenyo"],
    "": ["kokukaleka"],
    "": ["kokukandula"],
    "": ["kokukoleka"],
    "": ["kokukondjitha"],
    "": ["kokukonga"],
    "": ["kokukutwa"],
    "": ["kokukwatwa"],
    "": ["kokulanda"],
    "": ["kokulanditha"],
    "": ["kokulandithila"],
    "": ["kokulekule"],
    "": ["kokulela"],
    "": ["kokulesha"],
    "": ["kokulila"],
    "": ["kokulonga"],
    "": ["kokulongela"],
    "": ["kokulongitha"],
    "": ["kokulongithwa"],
    "": ["kokulopota"],
    "": ["kokululuma"],
    "": ["kokulumoho"],
    "": ["kokuluudha"],
    "": ["kokuluyapalela"],
    "": ["kokulwitha"],
    "": ["kokulyo"],
    "": ["kokuma"],
    "": ["kokumbwindila"],
    "": ["kokumona"],
    "": ["kokunana"],
    "": ["kokunanaoshimaliwa"],
    "": ["kokundjeneka"],
    "": ["kokunwa"],
    "": ["kokunyala"],
    "": ["kokunyanyangidhwa"],
    "": ["kokunyolela"],
    "": ["kokupandula"],
    "": ["kokupanga"],
    "": ["kokupata"],
    "": ["kokupatulula"],
    "": ["kokupomba"],
    "": ["kokupona"],
    "": ["kokupongola"],
    "": ["kokupopya"],
    "": ["kokusa"],
    "": ["kokushinga"],
    "": ["kokushongwa"],
    "": ["kokushuna"],
    "": ["kokusila"],
    "": ["kokusimaneka"],
    "": ["kokusinda"],
    "": ["kokutala"],
    "": ["kokutalitha"],
    "": ["kokuteya"],
    "": ["kokuthikitha"],
    "": ["kokuthimbinga"],
    "": ["kokuthiminikwa"],
    "": ["kokuti"],
    "": ["kokutidha"],
    "": ["kokutintilwa"],
    "": ["kokutsakanena"],
    "": ["kokutse"],
    "": ["kokutseyitha"],
    "": ["kokutsi"],
    "": ["kokutula"],
    "": ["kokutya"],
    "": ["kokutyatyela"],
    "": ["kokuu"],
    "": ["kokuume"],
    "": ["kokuundula"],
    "": ["kokuuninginino"],
    "": ["kokuuziilo"],
    "": ["kokuuzilo"],
    "": ["kokuvalwa"],
    "": ["kokuwalye"],
    "": ["kokuya"],
    "": ["kokuyina"],
    "": ["kokuyogitha"],
    "": ["kokwaashisha"],
    "": ["kokwaasimaneka"],
    "": ["kokwaatsakumwe"],
    "": ["kokweehamekwa"],
    "": ["kokweenda"],
    "": ["kokweeta"],
    "": ["kokwena"],
    "": ["kokwiigidha"],
    "": ["kokwiihega"],
    "": ["kokwiitekapo"],
    "": ["kokwiiyaha"],
    "": ["kokwoopalela"],
    "": ["kolaata"],
    "": ["kolekele"],
    "": ["kolekelwa"],
    "": ["kolekulula"],
    "": ["kolekwe"],
    "": ["koliha"],
    "": ["kolitheni"],
    "": ["kolo"],
    "": ["koloka"],
    "": ["kolokele"],
    "": ["kolokosha"],
    "": ["kololoka"],
    "": ["kololokwa"],
    "": ["koloma"],
    "": ["kolomoka"],
    "": ["kolomoke"],
    "": ["kolonda"],
    "": ["kolongele"],
    "": ["kolongelele"],
    "": ["kolongitha"],
    "": ["kolongithwa"],
    "": ["kolongithwe"],
    "": ["kolongwa"],
    "": ["kolongwe"],
    "": ["koluko"],
    "": ["kolupale"],
    "": ["kolupanda"],
    "": ["kolupati"],
    "": ["kolushi"],
    "": ["kolusilu"],
    "": ["koluti"],
    "": ["koluungu"],
    "": ["koluvalo"],
    "": ["kolweni"],
}
