# Generated by Django 3.1 on 2021-07-30 19:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='image',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[50, 50], upload_to='service_provider_logos'),
        ),
    ]
