# Generated by Django 3.1 on 2021-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0002_auto_20210730_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='entity_type',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('Private', 'Private'), ('Public', 'Public'), ('Parastatal', 'Parastatal')], max_length=10),
        ),
    ]
