# Generated by Django 3.1 on 2021-08-06 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equeue', '0003_auto_20210730_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuedcustomer',
            old_name='service',
            new_name='service_enrolment',
        ),
        migrations.CreateModel(
            name='ServantEnrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equeue.serviceenrolment')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equeue.serviceprovider')),
            ],
            options={
                'ordering': ['servant'],
            },
        ),
        migrations.AddConstraint(
            model_name='servantenrolment',
            constraint=models.UniqueConstraint(fields=('servant', 'service_enrolment'), name='unique_servant_enrolment'),
        ),
    ]
