# Generated by Django 3.1 on 2021-08-07 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equeue', '0004_auto_20210806_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servedcustomer',
            name='server',
        ),
        migrations.AddField(
            model_name='servedcustomer',
            name='served_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers_served', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancelledcustomer',
            name='cancelled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queuedcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queuedcustomer',
            name='service_enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_queue', to='equeue.serviceenrolment'),
        ),
        migrations.AlterField(
            model_name='servantenrolment',
            name='service_enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='equeue.serviceenrolment'),
        ),
        migrations.AlterField(
            model_name='servantenrolment',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servants', to='equeue.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='servedcustomer',
            name='service_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceenrolment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='equeue.service'),
        ),
        migrations.AlterField(
            model_name='serviceenrolment',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='equeue.serviceprovider'),
        ),
    ]
