# Generated by Django 3.1 on 2021-10-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0005_auto_20210807_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelledcustomer',
            old_name='queue_id',
            new_name='service_enrolment_id',
        ),
    ]
