# Generated by Django 3.1 on 2021-10-19 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equeue', '0007_delete_queuedcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL)),
                ('service_enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_queue', to='equeue.serviceenrolment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='queuedcustomer',
            constraint=models.UniqueConstraint(fields=('service_enrolment', 'customer'), name='unique_queuer'),
        ),
    ]
