# Generated by Django 4.2 on 2023-04-25 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefinitionExample",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("english_example", models.CharField(max_length=255)),
                ("oshindonga_example", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnglishWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                (
                    "word",
                    models.CharField(
                        error_messages={
                            "unique": "The English word you entered already exists in the dictionary."
                        },
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "word_case",
                    models.CharField(
                        choices=[
                            ("Abbreviation", "Abbreviation"),
                            ("Proper Noun", "Proper Noun"),
                            ("Normal", "Normal"),
                        ],
                        default="Normal",
                        help_text="Indicate whether the word you are entering is a normal word, abbretiation or proper noun.",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalDefinitionExample",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("english_example", models.CharField(max_length=255)),
                ("oshindonga_example", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical definition example",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEnglishWord",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "word",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "The English word you entered already exists in the dictionary."
                        },
                        max_length=50,
                    ),
                ),
                (
                    "word_case",
                    models.CharField(
                        choices=[
                            ("Abbreviation", "Abbreviation"),
                            ("Proper Noun", "Proper Noun"),
                            ("Normal", "Normal"),
                        ],
                        default="Normal",
                        help_text="Indicate whether the word you are entering is a normal word, abbretiation or proper noun.",
                        max_length=12,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical english word",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOshindongaIdiom",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("oshindonga_idiom", models.CharField(max_length=255)),
                ("meaning", models.CharField(blank=True, max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical oshindonga idiom",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOshindongaPhonetic",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("oshindonga_word", models.CharField(max_length=50)),
                ("pronunciation", models.TextField(blank=True, max_length=100)),
                (
                    "phonetics",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Phonetic trascription"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical oshindonga phonetic",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOshindongaWord",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                ("word", models.CharField(max_length=50)),
                (
                    "word_case",
                    models.CharField(
                        choices=[
                            ("Abbreviation", "Abbreviation"),
                            ("Proper Noun", "Proper Noun"),
                            ("Normal", "Normal"),
                        ],
                        default="Normal",
                        help_text="Ulika ngele oshitya wa shanga oshowala, efupipiko nenge oshityadhinalela.",
                        max_length=12,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical oshindonga word",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWordDefinition",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("time_added", models.DateTimeField(blank=True, editable=False)),
                ("time_modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("", "Select the part of speech of your definition"),
                            ("JJ", "Adjective"),
                            ("JJR", "Adjective, comparative"),
                            ("JJS", "Adjective, superlative"),
                            ("RB", "Adverb"),
                            ("RBR", "Adverb, comparative"),
                            ("RBS", "Adverb, superlative"),
                            ("CC", "Coordinating conjunction"),
                            ("CD", "Cardinal digit"),
                            ("DT", "Determiner"),
                            ("EX", "Existential there [e.g., there is]"),
                            ("FW", "Foreign word"),
                            ("UH", "Interjection"),
                            ("LS", "List marker"),
                            ("MD", "Modal"),
                            ("NN", "Noun, singular"),
                            ("NNS", "Noun, plural"),
                            ("RP", "Particle [e.g., come in/up/over]"),
                            ("PDT", "Predeterminer"),
                            ("IN", "Preposition/Subordinating conjunction"),
                            ("PRP", "Personal pronoun"),
                            ("POS", "Possessive ending [e.g., parent's]"),
                            ("PRP$", "Possessive pronoun"),
                            ("WP$", "Possessive wh-pronoun [e.g., whose]"),
                            ("NNP", "Proper noun, singular"),
                            ("NNPS", "Proper noun, plural"),
                            ("TO", "To [e.g., to + verb]"),
                            ("VB", "Verb, base form"),
                            ("VBD", "Verb, past tense"),
                            ("VBG", "Verb, gerund/present participle"),
                            ("VBN", "Verb, past participle"),
                            ("VBP", "Verb, sing. present, non-3d"),
                            ("VBZ", "Verb, 3rd person sing. Present"),
                            ("WDT", "Wh-determiner [e.g., which]"),
                            ("WP", "Wh-pronoun [e.g., who, what]"),
                            ("WRB", "Wh-abverb where [e.g., when]"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "simple_present",
                    models.CharField(
                        blank=True, help_text="Enter tense in Oshindonga", max_length=50
                    ),
                ),
                (
                    "present_participle",
                    models.CharField(
                        blank=True, help_text="Enter tense in Oshindonga", max_length=50
                    ),
                ),
                (
                    "simple_past",
                    models.CharField(
                        blank=True, help_text="Enter tense in Oshindonga", max_length=50
                    ),
                ),
                (
                    "past_participle",
                    models.CharField(
                        blank=True, help_text="Enter tense in Oshindonga", max_length=50
                    ),
                ),
                ("english_definition", models.CharField(blank=True, max_length=255)),
                ("oshindonga_definition", models.CharField(blank=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical word definition",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OshindongaIdiom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("oshindonga_idiom", models.CharField(max_length=255)),
                ("meaning", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OshindongaPhonetic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("oshindonga_word", models.CharField(max_length=50)),
                (
                    "pronunciation",
                    models.FileField(blank=True, upload_to="pronunciations"),
                ),
                (
                    "phonetics",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Phonetic trascription"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OshindongaWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("word", models.CharField(max_length=50)),
                (
                    "word_case",
                    models.CharField(
                        choices=[
                            ("Abbreviation", "Abbreviation"),
                            ("Proper Noun", "Proper Noun"),
                            ("Normal", "Normal"),
                        ],
                        default="Normal",
                        help_text="Ulika ngele oshitya wa shanga oshowala, efupipiko nenge oshityadhinalela.",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnfoundWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("time_searched", models.DateTimeField(auto_now_add=True)),
                ("search_count", models.IntegerField(default=1)),
                ("added_to_dict", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WordDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("", "Select the part of speech of your definition"),
                            ("JJ", "Adjective"),
                            ("JJR", "Adjective, comparative"),
                            ("JJS", "Adjective, superlative"),
                            ("RB", "Adverb"),
                            ("RBR", "Adverb, comparative"),
                            ("RBS", "Adverb, superlative"),
                            ("CC", "Coordinating conjunction"),
                            ("CD", "Cardinal digit"),
                            ("DT", "Determiner"),
                            ("EX", "Existential there [e.g., there is]"),
                            ("FW", "Foreign word"),
                            ("UH", "Interjection"),
                            ("LS", "List marker"),
                            ("MD", "Modal"),
                            ("NN", "Noun, singular"),
                            ("NNS", "Noun, plural"),
                            ("RP", "Particle [e.g., come in/up/over]"),
                            ("PDT", "Predeterminer"),
                            ("IN", "Preposition/Subordinating conjunction"),
                            ("PRP", "Personal pronoun"),
                            ("POS", "Possessive ending [e.g., parent's]"),
                            ("PRP$", "Possessive pronoun"),
                            ("WP$", "Possessive wh-pronoun [e.g., whose]"),
                            ("NNP", "Proper noun, singular"),
                            ("NNPS", "Proper noun, plural"),
                            ("TO", "To [e.g., to + verb]"),
                            ("VB", "Verb, base form"),
                            ("VBD", "Verb, past tense"),
                            ("VBG", "Verb, gerund/present participle"),
                            ("VBN", "Verb, past participle"),
                            ("VBP", "Verb, sing. present, non-3d"),
                            ("VBZ", "Verb, 3rd person sing. Present"),
                            ("WDT", "Wh-determiner [e.g., which]"),
                            ("WP", "Wh-pronoun [e.g., who, what]"),
                            ("WRB", "Wh-abverb where [e.g., when]"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "simple_present",
                    models.CharField(
                        blank=True, help_text="Enter tense in Oshindonga", max_length=50
                    ),
                ),
                (
                    "present_participle",
                    models.CharField(
                        blank=True, help_text="Enter tense in Oshindonga", max_length=50
                    ),
                ),
                (
                    "simple_past",
                    models.CharField(
                        blank=True, help_text="Enter tense in Oshindonga", max_length=50
                    ),
                ),
                (
                    "past_participle",
                    models.CharField(
                        blank=True, help_text="Enter tense in Oshindonga", max_length=50
                    ),
                ),
                ("english_definition", models.CharField(blank=True, max_length=255)),
                ("oshindonga_definition", models.CharField(blank=True, max_length=255)),
                (
                    "plurals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="plurals",
                        to="dictionary.oshindongaword",
                    ),
                ),
                (
                    "synonyms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="synonyms",
                        to="dictionary.oshindongaword",
                    ),
                ),
                (
                    "word_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definitions",
                        to="dictionary.oshindongaword",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="unfoundword",
            constraint=models.UniqueConstraint(
                fields=("word", "language"), name="unique_unfound_word"
            ),
        ),
        migrations.AddField(
            model_name="oshindongaword",
            name="english_word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dictionary.englishword"
            ),
        ),
        migrations.AddField(
            model_name="oshindongaword",
            name="word_phonetics",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dictionary.oshindongaphonetic",
            ),
        ),
        migrations.AddConstraint(
            model_name="oshindongaphonetic",
            constraint=models.UniqueConstraint(
                fields=("oshindonga_word", "phonetics"), name="unique_phonetics"
            ),
        ),
        migrations.AddField(
            model_name="oshindongaidiom",
            name="word_pair",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary.oshindongaword",
            ),
        ),
        migrations.AddField(
            model_name="historicalworddefinition",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalworddefinition",
            name="word_pair",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.oshindongaword",
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaword",
            name="english_word",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.englishword",
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaword",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaword",
            name="word_phonetics",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.oshindongaphonetic",
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaphonetic",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaidiom",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaloshindongaidiom",
            name="word_pair",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.oshindongaword",
            ),
        ),
        migrations.AddField(
            model_name="historicalenglishword",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinitionexample",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.worddefinition",
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinitionexample",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="definitionexample",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary.worddefinition",
            ),
        ),
        migrations.AddConstraint(
            model_name="oshindongaword",
            constraint=models.UniqueConstraint(
                fields=("english_word", "word", "word_case"), name="unique_word_pair"
            ),
        ),
    ]
