# Generated by Django 3.1.1 on 2021-02-02 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='English',
            new_name='EnglishWord',
        ),
        migrations.RenameModel(
            old_name='HistoricalEnglish',
            new_name='HistoricalEnglishWord',
        ),
        migrations.AlterModelOptions(
            name='historicalenglishword',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical english word'},
        ),
    ]
