# Generated by Django 3.1.1 on 2021-02-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_definitionexample_historicaldefinitionexample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworddefinition',
            old_name='oshindonga_word',
            new_name='word_pair',
        ),
        migrations.RenameField(
            model_name='worddefinition',
            old_name='oshindonga_word',
            new_name='word_pair',
        ),
    ]
