# Generated by Django 3.1.1 on 2021-02-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20210203_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldefinitionexample',
            name='history_change_reason',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='historicalenglishword',
            name='history_change_reason',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='historicaloshindongaword',
            name='history_change_reason',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='history_change_reason',
            field=models.TextField(default=None),
        ),
    ]
