# Generated by Django 3.1.1 on 2021-02-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20210210_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldefinitionexample',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalenglishword',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaloshindongaword',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
