# Generated by Django 3.1.1 on 2021-02-15 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0008_auto_20210210_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper', 'Proper'), ('Normal', 'Normal')], default='Normal', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalenglishword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper', 'Proper'), ('Normal', 'Normal')], default='Normal', max_length=12),
        ),
        migrations.AddField(
            model_name='historicaloshindongaword',
            name='plural',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicaloshindongaword',
            name='tense',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicaloshindongaword',
            name='variants',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicaloshindongaword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper', 'Proper'), ('Normal', 'Normal')], default='Normal', max_length=12),
        ),
        migrations.AddField(
            model_name='oshindongaword',
            name='plural',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='oshindongaword',
            name='tense',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='oshindongaword',
            name='variants',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='oshindongaword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper', 'Proper'), ('Normal', 'Normal')], default='Normal', max_length=12),
        ),
        migrations.CreateModel(
            name='OshindongaIdiom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateField(auto_now_add=True)),
                ('time_modified', models.DateField(auto_now=True)),
                ('oshindonga_idiom', models.TextField()),
                ('oshindonga_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.oshindongaword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalOshindongaIdiom',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('time_added', models.DateField(blank=True, editable=False)),
                ('time_modified', models.DateField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('oshindonga_idiom', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oshindonga_word', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionary.oshindongaword')),
            ],
            options={
                'verbose_name': 'historical oshindonga idiom',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
