# Generated by Django 3.1.1 on 2021-02-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20210215_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloshindongaword',
            name='plural',
        ),
        migrations.RemoveField(
            model_name='historicaloshindongaword',
            name='tense',
        ),
        migrations.RemoveField(
            model_name='historicaloshindongaword',
            name='variants',
        ),
        migrations.RemoveField(
            model_name='oshindongaword',
            name='plural',
        ),
        migrations.RemoveField(
            model_name='oshindongaword',
            name='tense',
        ),
        migrations.RemoveField(
            model_name='oshindongaword',
            name='variants',
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='plural',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='tense',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='variants',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='plural',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='tense',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='variants',
            field=models.JSONField(null=True),
        ),
    ]
