# Generated by Django 3.1.1 on 2021-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20210216_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='plural',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='tense',
            field=models.JSONField(blank=True, default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='variants',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='plural',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='tense',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='variants',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
