# Generated by Django 3.1.1 on 2021-02-20 00:51

import dictionary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_auto_20210219_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitionexample',
            name='english_example',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='definitionexample',
            name='oshindonga_example',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldefinitionexample',
            name='english_example',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldefinitionexample',
            name='oshindonga_example',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaloshindongaidiom',
            name='oshindonga_idiom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='english_definition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='oshindonga_definition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='plural',
            field=models.JSONField(default=dictionary.models.plural_default),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='tense',
            field=models.JSONField(default=dictionary.models.tense_default),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='variants',
            field=models.JSONField(default=dictionary.models.variants_default),
        ),
        migrations.AlterField(
            model_name='oshindongaidiom',
            name='oshindonga_idiom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='english_definition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='oshindonga_definition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='plural',
            field=models.JSONField(default=dictionary.models.plural_default),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='tense',
            field=models.JSONField(default=dictionary.models.tense_default),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='variants',
            field=models.JSONField(default=dictionary.models.variants_default),
        ),
    ]
