# Generated by Django 3.1.1 on 2021-02-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_auto_20210220_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloshindongaidiom',
            old_name='oshindonga_word',
            new_name='word_pair',
        ),
        migrations.RenameField(
            model_name='oshindongaidiom',
            old_name='oshindonga_word',
            new_name='word_pair',
        ),
        migrations.AlterField(
            model_name='englishword',
            name='word',
            field=models.CharField(error_messages={'unique': 'The English word you entered already exists in the dictionary.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper Noun', 'Proper Noun'), ('Normal', 'Normal')], default='Normal', help_text='Indicate whether the word you are entering is a normal word, abbretiation or proper noun.', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalenglishword',
            name='word',
            field=models.CharField(db_index=True, error_messages={'unique': 'The English word you entered already exists in the dictionary.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalenglishword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper Noun', 'Proper Noun'), ('Normal', 'Normal')], default='Normal', help_text='Indicate whether the word you are entering is a normal word, abbretiation or proper noun.', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicaloshindongaword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper', 'Proper'), ('Normal', 'Normal')], default='Normal', help_text='Ulika ngele oshitya wa shanga oshowala, efupipiko nenge oshityadhinalela.', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('Noun', 'Noun'), ('Pron.', 'Pronoun'), ('Verb', 'Verb'), ('Adj.', 'Adjective'), ('Adv.', 'Adverb'), ('Prep.', 'Preposition'), ('Conj.', 'Conjunction'), ('Int.', 'Interjection')], max_length=5),
        ),
        migrations.AlterField(
            model_name='oshindongaword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper', 'Proper'), ('Normal', 'Normal')], default='Normal', help_text='Ulika ngele oshitya wa shanga oshowala, efupipiko nenge oshityadhinalela.', max_length=12),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('Noun', 'Noun'), ('Pron.', 'Pronoun'), ('Verb', 'Verb'), ('Adj.', 'Adjective'), ('Adv.', 'Adverb'), ('Prep.', 'Preposition'), ('Conj.', 'Conjunction'), ('Int.', 'Interjection')], max_length=5),
        ),
    ]
