# Generated by Django 3.1.1 on 2021-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20210221_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='definitionexample',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
        migrations.AddField(
            model_name='historicaldefinitionexample',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
        migrations.AddField(
            model_name='historicalenglishword',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
        migrations.AddField(
            model_name='historicaloshindongaidiom',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
        migrations.AddField(
            model_name='historicaloshindongaword',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
        migrations.AddField(
            model_name='oshindongaidiom',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
        migrations.AddField(
            model_name='oshindongaword',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='_change_reason',
            field=models.CharField(help_text='Enter the reason for updating this record.', max_length=225, null=True, verbose_name='Change reason'),
        ),
    ]
