# Generated by Django 3.1.1 on 2021-02-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_auto_20210222_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definitionexample',
            name='_change_reason',
        ),
        migrations.RemoveField(
            model_name='englishword',
            name='_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicaldefinitionexample',
            name='_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalenglishword',
            name='_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicaloshindongaidiom',
            name='_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicaloshindongaword',
            name='_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalworddefinition',
            name='_change_reason',
        ),
        migrations.RemoveField(
            model_name='oshindongaidiom',
            name='_change_reason',
        ),
        migrations.RemoveField(
            model_name='oshindongaword',
            name='_change_reason',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='_change_reason',
        ),
        migrations.AlterField(
            model_name='historicaldefinitionexample',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalenglishword',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloshindongaidiom',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloshindongaword',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
