# Generated by Django 3.1.1 on 2021-02-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0016_auto_20210222_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworddefinition',
            name='past_participle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='plural1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='plural2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='plural3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='present_participle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='simple_past',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='simple_present',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='past_participle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='plural1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='plural2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='plural3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='present_participle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='simple_past',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='simple_present',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaloshindongaword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper Noun', 'Proper Noun'), ('Normal', 'Normal')], default='Normal', help_text='Ulika ngele oshitya wa shanga oshowala, efupipiko nenge oshityadhinalela.', max_length=12),
        ),
        migrations.AlterField(
            model_name='oshindongaword',
            name='word_case',
            field=models.CharField(choices=[('Abbreviation', 'Abbreviation'), ('Proper Noun', 'Proper Noun'), ('Normal', 'Normal')], default='Normal', help_text='Ulika ngele oshitya wa shanga oshowala, efupipiko nenge oshityadhinalela.', max_length=12),
        ),
    ]
