# Generated by Django 3.1.1 on 2021-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0018_auto_20210226_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworddefinition',
            name='synonym2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='synonym3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalworddefinition',
            name='synonym4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='synonym2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='synonym3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='synonym4',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
