# Generated by Django 3.1.1 on 2021-02-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0020_auto_20210227_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('Noun [C]', 'Noun [C]'), ('Noun [U]', 'Noun [U]'), ('Pron.', 'Pronoun'), ('Verb', 'Verb'), ('Adj.', 'Adjective'), ('Adv.', 'Adverb'), ('Prep.', 'Preposition'), ('Conj.', 'Conjunction'), ('Int.', 'Interjection')], max_length=8),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('Noun [C]', 'Noun [C]'), ('Noun [U]', 'Noun [U]'), ('Pron.', 'Pronoun'), ('Verb', 'Verb'), ('Adj.', 'Adjective'), ('Adv.', 'Adverb'), ('Prep.', 'Preposition'), ('Conj.', 'Conjunction'), ('Int.', 'Interjection')], max_length=8),
        ),
    ]
