# Generated by Django 3.1.1 on 2021-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0022_auto_20210308_0531'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='oshindongaword',
            constraint=models.UniqueConstraint(fields=('english_word', 'word', 'word_case'), name='unique_word_pair'),
        ),
    ]
