# Generated by Django 3.2 on 2021-04-19 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0023_auto_20210328_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOshindongaPhonetic',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('time_added', models.DateTimeField(blank=True, editable=False)),
                ('time_modified', models.DateTimeField(blank=True, editable=False)),
                ('oshindonga_word', models.CharField(max_length=50)),
                ('pronunciation', models.TextField(max_length=100)),
                ('phonetics', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical oshindonga phonetic',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OshindongaPhonetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('oshindonga_word', models.CharField(max_length=50)),
                ('pronunciation', models.FileField(upload_to='pronunciations')),
                ('phonetics', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='oshindongaphonetic',
            constraint=models.UniqueConstraint(fields=('oshindonga_word', 'phonetics'), name='unique_phonetics'),
        ),
        migrations.AddField(
            model_name='historicaloshindongaphonetic',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaloshindongaword',
            name='word_phonetics',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionary.oshindongaphonetic'),
        ),
        migrations.AddField(
            model_name='oshindongaword',
            name='word_phonetics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.oshindongaphonetic'),
        ),
    ]
