# Generated by Django 3.2 on 2021-04-25 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0024_auto_20210419_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oshindongaword',
            name='word_phonetics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.oshindongaphonetic'),
        ),
    ]
