# Generated by Django 3.2 on 2021-05-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0025_alter_oshindongaword_word_phonetics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloshindongaphonetic',
            name='phonetics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oshindongaphonetic',
            name='phonetics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
