# Generated by Django 3.2 on 2021-05-09 20:26

import dictionary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0026_auto_20210509_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloshindongaphonetic',
            name='phonetics',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phonetic trascription'),
        ),
        migrations.AlterField(
            model_name='historicaloshindongaphonetic',
            name='pronunciation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloshindongaword',
            name='word_phonetics',
            field=models.ForeignKey(blank=True, db_constraint=False, default=dictionary.models.get_phonetics_default, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionary.oshindongaphonetic'),
        ),
        migrations.AlterField(
            model_name='oshindongaphonetic',
            name='phonetics',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phonetic trascription'),
        ),
        migrations.AlterField(
            model_name='oshindongaphonetic',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='pronunciations'),
        ),
        migrations.AlterField(
            model_name='oshindongaword',
            name='word_phonetics',
            field=models.ForeignKey(blank=True, default=dictionary.models.get_phonetics_default, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.oshindongaphonetic'),
        ),
    ]
