# Generated by Django 3.2 on 2021-05-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0027_auto_20210509_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloshindongaphonetic',
            name='phonetics',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Phonetic trascription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaloshindongaphonetic',
            name='pronunciation',
            field=models.TextField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oshindongaphonetic',
            name='phonetics',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Phonetic trascription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oshindongaphonetic',
            name='pronunciation',
            field=models.FileField(blank=True, default='', upload_to='pronunciations'),
            preserve_default=False,
        ),
    ]
