# Generated by Django 3.2 on 2021-05-16 21:12

import dictionary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0028_auto_20210516_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oshindongaword',
            name='word_phonetics',
            field=models.ForeignKey(default=dictionary.models.get_phonetics_default, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.oshindongaphonetic'),
        ),
    ]
