# Generated by Django 3.2 on 2021-05-16 21:42

import dictionary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0030_auto_20210516_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloshindongaword',
            name='word_phonetics',
            field=models.ForeignKey(blank=True, db_constraint=False, default=dictionary.models.get_phonetics_default, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dictionary.oshindongaphonetic'),
        ),
        migrations.AlterField(
            model_name='oshindongaword',
            name='word_phonetics',
            field=models.ForeignKey(default=dictionary.models.get_phonetics_default, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.oshindongaphonetic'),
        ),
    ]
