# Generated by Django 4.0.1 on 2022-03-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0031_auto_20210516_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnfoundWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('time_searched', models.DateTimeField(auto_now_add=True)),
                ('total_searches', models.IntegerField(default=1)),
                ('added_to_dict', models.BooleanField(default=False)),
            ],
        ),
    ]
