# Generated by Django 4.0.1 on 2022-03-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0032_unfoundword'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unfoundword',
            constraint=models.UniqueConstraint(fields=('word', 'language'), name='unique_unfound_word'),
        ),
    ]
