# Generated by Django 4.0.1 on 2022-03-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0033_unfoundword_unique_unfound_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unfoundword',
            old_name='total_searches',
            new_name='search_count',
        ),
    ]
