# Generated by Django 4.0.5 on 2022-07-05 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0034_rename_total_searches_unfoundword_search_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworddefinition',
            name='synonym1',
        ),
        migrations.RemoveField(
            model_name='historicalworddefinition',
            name='synonym2',
        ),
        migrations.RemoveField(
            model_name='historicalworddefinition',
            name='synonym3',
        ),
        migrations.RemoveField(
            model_name='historicalworddefinition',
            name='synonym4',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='synonym1',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='synonym2',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='synonym3',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='synonym4',
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='synonyms',
            field=models.ManyToManyField(related_name='synonyms', to='dictionary.oshindongaword'),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='english_definition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='oshindonga_definition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('adjective', 'adjective'), ('adposition', 'adposition'), ('adverb', 'adverb'), ('auxiliary', 'auxiliary'), ('coordinating conjunction', 'coordinating conjunction'), ('determiner', 'determiner'), ('interjection', 'interjection'), ('noun', 'noun'), ('numeral', 'numeral'), ('particle', 'particle'), ('pronoun', 'pronoun'), ('proper noun', 'proper noun'), ('punctuation', 'punctuation'), ('subordinating conjunction', 'subordinating conjunction'), ('symbol', 'symbol'), ('verb', 'verb'), ('other', 'other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='english_definition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='oshindonga_definition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('adjective', 'adjective'), ('adposition', 'adposition'), ('adverb', 'adverb'), ('auxiliary', 'auxiliary'), ('coordinating conjunction', 'coordinating conjunction'), ('determiner', 'determiner'), ('interjection', 'interjection'), ('noun', 'noun'), ('numeral', 'numeral'), ('particle', 'particle'), ('pronoun', 'pronoun'), ('proper noun', 'proper noun'), ('punctuation', 'punctuation'), ('subordinating conjunction', 'subordinating conjunction'), ('symbol', 'symbol'), ('verb', 'verb'), ('other', 'other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='word_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='dictionary.oshindongaword'),
        ),
    ]
