# Generated by Django 4.0.5 on 2022-07-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0035_remove_historicalworddefinition_synonym1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('adjective', 'Adjective'), ('adposition', 'Adposition'), ('adverb', 'Adverb'), ('auxiliary', 'Auxiliary'), ('coordinating conjunction', 'Coordinating conjunction'), ('determiner', 'Determiner'), ('interjection', 'Interjection'), ('noun', 'Noun'), ('numeral', 'Numeral'), ('particle', 'Particle'), ('pronoun', 'Pronoun'), ('proper noun', 'Proper noun'), ('punctuation', 'Punctuation'), ('subordinating conjunction', 'Subordinating conjunction'), ('symbol', 'Symbol'), ('verb', 'Verb'), ('other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('adjective', 'Adjective'), ('adposition', 'Adposition'), ('adverb', 'Adverb'), ('auxiliary', 'Auxiliary'), ('coordinating conjunction', 'Coordinating conjunction'), ('determiner', 'Determiner'), ('interjection', 'Interjection'), ('noun', 'Noun'), ('numeral', 'Numeral'), ('particle', 'Particle'), ('pronoun', 'Pronoun'), ('proper noun', 'Proper noun'), ('punctuation', 'Punctuation'), ('subordinating conjunction', 'Subordinating conjunction'), ('symbol', 'Symbol'), ('verb', 'Verb'), ('other', 'Other')], max_length=25),
        ),
    ]
