# Generated by Django 4.0.5 on 2022-07-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0036_alter_historicalworddefinition_part_of_speech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddefinition',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='synonyms', to='dictionary.oshindongaword'),
        ),
    ]
