# Generated by Django 4.0.5 on 2022-07-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0037_alter_worddefinition_synonyms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worddefinition',
            name='synonyms',
        ),
    ]
