# Generated by Django 4.0.5 on 2022-07-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0038_remove_worddefinition_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddefinition',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='synonyms', to='dictionary.oshindongaword'),
        ),
    ]
