# Generated by Django 4.0.5 on 2022-08-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0039_worddefinition_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('ADJ', 'Adjective'), ('ADP', 'Adposition'), ('ADV', 'Adverb'), ('AUX', 'Auxiliary'), ('CCONJ', 'Coordinating conjunction'), ('DET', 'Determiner'), ('INTJ', 'Interjection'), ('NOUN', 'Noun'), ('NUM', 'Numeral'), ('PART', 'Particle'), ('PRON', 'Pronoun'), ('PROPN', 'Proper noun'), ('SCONJ', 'Subordinating conjunction'), ('VERB', 'Verb')], max_length=25),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='part_of_speech',
            field=models.CharField(choices=[('', 'Select the part of speech of your definition'), ('ADJ', 'Adjective'), ('ADP', 'Adposition'), ('ADV', 'Adverb'), ('AUX', 'Auxiliary'), ('CCONJ', 'Coordinating conjunction'), ('DET', 'Determiner'), ('INTJ', 'Interjection'), ('NOUN', 'Noun'), ('NUM', 'Numeral'), ('PART', 'Particle'), ('PRON', 'Pronoun'), ('PROPN', 'Proper noun'), ('SCONJ', 'Subordinating conjunction'), ('VERB', 'Verb')], max_length=25),
        ),
    ]
