# Generated by Django 4.1 on 2022-08-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0041_alter_historicalworddefinition_part_of_speech_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalworddefinition",
            name="plural1",
        ),
        migrations.RemoveField(
            model_name="historicalworddefinition",
            name="plural2",
        ),
        migrations.RemoveField(
            model_name="worddefinition",
            name="plural1",
        ),
        migrations.RemoveField(
            model_name="worddefinition",
            name="plural2",
        ),
        migrations.AddField(
            model_name="worddefinition",
            name="plurals",
            field=models.ManyToManyField(
                blank=True, related_name="plurals", to="dictionary.oshindongaword"
            ),
        ),
    ]
