# Generated by Django 4.1 on 2022-08-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0042_remove_historicalworddefinition_plural1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalworddefinition",
            name="part_of_speech",
            field=models.CharField(
                choices=[
                    ("", "Select the part of speech of your definition"),
                    ("JJ", "Adjective"),
                    ("JJR", "Adjective, comparative"),
                    ("JJS", "Adjective, superlative"),
                    ("RB", "Adverb"),
                    ("RBR", "Adverb, comparative"),
                    ("RBS", "Adverb, superlative"),
                    ("CC", "Coordinating conjunction"),
                    ("CD", "Cardinal digit"),
                    ("DT", "Determiner"),
                    ("EX", "Existential there [e.g., there is]"),
                    ("FW", "Foreign word"),
                    ("UH", "Interjection"),
                    ("LS", "List marker"),
                    ("MD", "Modal"),
                    ("NN", "Noun, singular"),
                    ("NNS", "Noun, plural"),
                    ("RP", "Particle [e.g., come in/up/over]"),
                    ("PDT", "Predeterminer"),
                    ("IN", "Preposition/Subordinating conjunction"),
                    ("PRP", "Personal pronoun"),
                    ("POS", "Possessive ending [e.g., parent's]"),
                    ("PRP$", "Possessive pronoun"),
                    ("WP$", "Possessive wh-pronoun [e.g., whose]"),
                    ("NNP", "Proper noun, singular"),
                    ("NNPS", "Proper noun, plural"),
                    ("TO", "To [e.g., to + verb]"),
                    ("VB", "Verb, base form"),
                    ("VBD", "Verb, past tense"),
                    ("VBG", "Verb, gerund/present participle"),
                    ("VBN", "Verb, past participle"),
                    ("VBP", "Verb, sing. present, non-3d"),
                    ("VBZ", "Verb, 3rd person sing. Present"),
                    ("WDT", "Wh-determiner [e.g., which]"),
                    ("WP", "Wh-pronoun [e.g., who, what]"),
                    ("WRB", "Wh-abverb where [e.g., when]"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="historicalworddefinition",
            name="past_participle",
            field=models.CharField(
                blank=True, help_text="Enter tense in Oshindonga", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicalworddefinition",
            name="present_participle",
            field=models.CharField(
                blank=True, help_text="Enter tense in Oshindonga", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicalworddefinition",
            name="simple_past",
            field=models.CharField(
                blank=True, help_text="Enter tense in Oshindonga", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicalworddefinition",
            name="simple_present",
            field=models.CharField(
                blank=True, help_text="Enter tense in Oshindonga", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="worddefinition",
            name="part_of_speech",
            field=models.CharField(
                choices=[
                    ("", "Select the part of speech of your definition"),
                    ("JJ", "Adjective"),
                    ("JJR", "Adjective, comparative"),
                    ("JJS", "Adjective, superlative"),
                    ("RB", "Adverb"),
                    ("RBR", "Adverb, comparative"),
                    ("RBS", "Adverb, superlative"),
                    ("CC", "Coordinating conjunction"),
                    ("CD", "Cardinal digit"),
                    ("DT", "Determiner"),
                    ("EX", "Existential there [e.g., there is]"),
                    ("FW", "Foreign word"),
                    ("UH", "Interjection"),
                    ("LS", "List marker"),
                    ("MD", "Modal"),
                    ("NN", "Noun, singular"),
                    ("NNS", "Noun, plural"),
                    ("RP", "Particle [e.g., come in/up/over]"),
                    ("PDT", "Predeterminer"),
                    ("IN", "Preposition/Subordinating conjunction"),
                    ("PRP", "Personal pronoun"),
                    ("POS", "Possessive ending [e.g., parent's]"),
                    ("PRP$", "Possessive pronoun"),
                    ("WP$", "Possessive wh-pronoun [e.g., whose]"),
                    ("NNP", "Proper noun, singular"),
                    ("NNPS", "Proper noun, plural"),
                    ("TO", "To [e.g., to + verb]"),
                    ("VB", "Verb, base form"),
                    ("VBD", "Verb, past tense"),
                    ("VBG", "Verb, gerund/present participle"),
                    ("VBN", "Verb, past participle"),
                    ("VBP", "Verb, sing. present, non-3d"),
                    ("VBZ", "Verb, 3rd person sing. Present"),
                    ("WDT", "Wh-determiner [e.g., which]"),
                    ("WP", "Wh-pronoun [e.g., who, what]"),
                    ("WRB", "Wh-abverb where [e.g., when]"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="worddefinition",
            name="past_participle",
            field=models.CharField(
                blank=True, help_text="Enter tense in Oshindonga", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="worddefinition",
            name="present_participle",
            field=models.CharField(
                blank=True, help_text="Enter tense in Oshindonga", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="worddefinition",
            name="simple_past",
            field=models.CharField(
                blank=True, help_text="Enter tense in Oshindonga", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="worddefinition",
            name="simple_present",
            field=models.CharField(
                blank=True, help_text="Enter tense in Oshindonga", max_length=50
            ),
        ),
    ]
