# Generated by Django 3.1 on 2021-07-18 13:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210715_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile_pics/default.png', force_format=None, keep_meta=True, quality=0, size=[200, 200], upload_to='profile_pics'),
        ),
    ]
