# Generated by Django 3.1 on 2021-07-30 19:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210718_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile_pics/default.apng', force_format=None, keep_meta=True, quality=100, size=[200, 200], upload_to='profile_pics'),
        ),
    ]
