# Generated by Django 4.0.1 on 2022-03-12 08:42

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_email_remove_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='product_pics/placeholder.png', force_format=None, keep_meta=True, quality=100, size=[640, 360], upload_to='product_pics'),
        ),
    ]
